app/views/public_health/index.html.erb
test/system/components/public_health_monitoring/actions.rb
test/system/components/public_health_monitoring/reports.rb
test/system/lib/system_test_utils.rb

Browser recalls most recent dashboard tab by saving it as a local storage variable
**Submitter:**
**Reviewer:**
Name:

Browser recalls most recent dashboard tab

---

app/controllers/application_controller.rb
app/javascript/components/admin/Admin.js

This PR contains a quick fix for a bug that caused a double rendering call when a user must both reset their password and also setup 2FA. The fix, forces a password change followed by 2FA creation.

Fix double render route on password change

---

Gemfile
Gemfile.lock
README.md
app/jobs/purge_job.rb
app/mailers/user_mailer.rb
app/models/patient.rb
app/views/user_mailer/purge_notification.html.erb
app/views/user_mailer/unformatted_html/purge_notification.html.erb
config/sara/sara.yml
config/schedule.rb
lib/tasks/mailers.rake
test/models/patient_test.rb

**Summary**
This PR contains changes to the user record purging job. The job now takes place once per week, defaulting to Saturday at 11:59pm. A notification will go out to all public health users several days before, again defaulting to Thursday at 12:00pm.
The email contains the number of user records that are currently marked as purgeable. At the time of the purge, the system will only purge the records that were considered purgeable at the time of the last warning (marked_for_purge).
**Design Decisions**
The email notification uses inline html styling to provide a professional feel for a critical email that users will be receiving weekly. Currently the Sara Alert logo is added as a header to the email, however not all email platforms will properly display the logo, which shouldn't …

189 record purge

---

app/controllers/patients_controller.rb
app/models/user.rb
app/views/patients/edit.html.erb
app/views/patients/new.html.erb
app/views/patients/new_group_member.html.erb
test/models/user_test.rb
test/system/workflow_test.rb

- Epi enrollers can only assign patients to jurisdictions within their hierarchy during enrollment
- Epi enrollers can no longer view patients outside of hierarchy even if they enrolled them

Fix: Viewable patients by epi enrollers

---

app/models/condition.rb
test/factories/condition.rb
test/factories/symptom.rb
test/models/condition_test.rb
test/test_helpers/symptom_test_helper.rb

This PR also adds some error checking to `Condition#build_symptoms` and adds a new feature to the method that will create symptoms even given that at least one symptom provided is valid.

Condition model tests

---

app/controllers/application_controller.rb
app/models/user.rb
config/sara/sara.yml
db/migrate/20200511151627_add_authy_enforced_to_user.rb
db/schema.rb
lib/tasks/demo.rake
test/fixtures/users.yml

This PR removes the use of environment variable `two_factor_auth_enabled` and replaces it with a new db column `authy_enforced`. It is important to note that `authy_enforced` is only applicable to users who do not have `authy_enabled`. If a user has `authy_enabled` they will still be presented with the 2FA screen as this routing is done by the authy gem itself.
To setup an Authy by-passable account, use the following commands in rails console:
```
user = User.find_by(email: 'username@example.com')
user.authy_enforced = false
user.authy_enabled = false      // If authy account already setup
user.authy_id = nil             // If authy account already setup
user.save!
```

Authy Enforced Per User

---

app/javascript/components/enrollment/steps/Exposure.js
app/javascript/components/subject/CaseStatus.js
app/javascript/components/subject/MonitoringStatus.js
app/javascript/components/subject/SymptomOnset.js
app/javascript/components/util/InfoTooltip.js
app/javascript/packs/stylesheets/layout.scss
app/models/patient.rb
app/views/public_health/_patients.html.erb
package.json
yarn.lock

The functionality behind some parts of the SaraAlert Tool might not be immediately clear to the user. Based on User feedback, this PR adds hover-able Question Marks that provide helpful tips, tutorials, and explanations for certain labels/buttons. An example of a tooltip is shown here:

Adds Info Tooltip to UI

---

app/javascript/components/util/InfoTooltip.js
app/javascript/components/util/ReportError.js
app/views/public_health/_patients.html.erb

Datatables was adding a `20px padding-right` which was blowing up the font-awesome question-circle svg. Adding bootstrap's `px-0` class forces that to zero, making the icon not blow up

fixes weird padding issue for datatables tooltip svg

---

app/javascript/components/dashboard/MonitorAnalytics.js

On the Analytics Dashboard, the User may download a screencapture of the dashboard. The CDC Maps component use by Sara has Tables of data beneath it that cause this to fail. These tables are removed just prior to the screencapture and then the page is re-loaded. The manner in which these tables were removed created an error with earlier versions of Internet Explorer. This PR changes that removal to use a legacy method that works across all browsers.

Removes IE11 support for Monitor Analytics Image Capture

---

app/models/laboratory.rb
app/models/patient.rb
test/models/patient_test.rb

JIRA: [https://jira.mitre.org/browse/SARAALERT-336](https://jira.mitre.org/browse/SARAALERT-336)
Current description from JIRA ticket:
If they have not had a test to determine if they are still contagious, they can leave home after these two things have happened:
At least 10 days have passed since the date of their first positive test
AND
they continue to have no symptoms since the test.
[CDC description](https://www.cdc.gov/coronavirus/2019-ncov/hcp/disposition-in-home-patients.html):
At least 10 days have passed since the date of their first positive COVID-19 diagnostic test assuming they have not subsequently developed symptoms since their positive test. If they develop symptoms, then the symptom-based or test-based strategy should be used. Note, because symptoms cannot be used to …

SARAALERT-336: Add asymptomatic recovery definition

---

Gemfile
Gemfile.lock
app/jobs/cache_analytics_job.rb
app/models/assessment.rb
app/models/history.rb
app/models/jurisdiction.rb
app/models/patient.rb
app/models/reported_condition.rb
lib/tasks/demo.rake
test/factories/assessment.rb
test/factories/reported_condition.rb
test/fixtures/histories.yml
test/fixtures/patients.yml
test/jobs/analytics_job_test.rb
test/models/history_test.rb
test/models/reported_condition_test.rb

Demo script data population and cache analytics job are improved by using the bulk import function from the [activerecord-import](https://github.com/zdennis/activerecord-import) gem. Beforehand, individual queries to the db were made for every insert of:
- patients, laboratories (demo:populate task)
- monitoree_counts, monitoree_snapshots (cache_analytics job)
Although the [insert_all](https://apidock.com/rails/v6.0.0/ActiveRecord/Persistence/ClassMethods/insert_all) function does bulk inserts as well, it only accepts hashes for the insert and not ActiveRecord models. Neither the insert_all nor activerecord-import import functions support bulk inserts with associated records as well. This feature only works for postgres unfortunately, which means doing bulk inserts on records with …

Demo script and cache analytics improvements

---

app/controllers/application_controller.rb
app/controllers/devise_authy_controller.rb
config/initializers/authy.rb
config/routes.rb

**Overview**
This PR attempts to address an issue where a user who does not have authy enforced is able to access the 2FA registration screen. The system will now redirect them away from it. This is a niche case only seen in testing.
Additionally, this PR cleans up some of the authy application filter logic, making it far more clear when rerouting is happening.
Lastly, this PR overrides a function in the `devise-authy` gem in order to add our `authy_enforced` logic into the processing of devise. Now if a user has `authy_enforced` set to false but `authy_enabled` set to true. They should still be able to bypass the 2FA screen.
**Simplified Console Commmand**
As a result the new console command to allow bypass of 2FA can be simplified to:
`User.where(email: …

Authy redirect

---

lib/tasks/demo.rake

Check for existing demo jurisdictions before failing silently on demo:setup task.
This patch gathers all demo jurisdictions into a hash for easier `nil` checking before proceeding to create users in each demo jurisdiction. It will print a helpful error/reminder to run the `admin:import_or_update_jurisdiction` task if the `nil` check is successful.

Check for Jurisdictions in demo.rake

---

lib/tasks/model_coverage.rake

Add rake task to check how much of each model is covered by its respective unit test.
It will output something like this when run:
Useful for making sure that we are independently testing the model's methods and not getting extra coverage from integration or system tests.

Independent Model Coverage Task

---

app/javascript/components/import/Import.js
test/system/lib/public_health_monitoring/dashboard.rb

Clarified some of the text Import section. Now, during the Import process, the user has the ability to stop the process. This will not add any more records. The already-imported records will remain in the system. This functionality has been made plain with descriptive text.

Adds STOP IMPORT to Import Page

---

API.md

minor issue, but without two whitespaces at the end of a line in markdown, it'll automatically merge consecutive lines, so this change prevents that by formatting a list

fix list formatting

---

app/controllers/export_controller.rb
app/helpers/import_export_helper.rb
app/javascript/components/subject/DownloadMonitoreeExcel.js
test/system/lib/public_health_monitoring/export_verifier.rb

to recreate:
While using the Public Health role in Safari when I go to an individual record and click download Excel file of record the Safari browser has an icon spin as if it is trying to download, but then no file is downloaded. 
fix: set loading bool to false instead of reloading the entire page

Excel individual export bug

---

app/helpers/import_export_helper.rb
app/models/patient.rb

Performance testing:
20,394 monitorees (14228 exp/6166 iso)
- LL exposure = 5.205 => 4.947
- LL isolation = 8.375 => 3.335
- SAF exposure = 31.362 => 17.056
- SAF isolation = 15.392 => 9.258
- Full export = 155.44 => 134.265
- 14228 monitorees: 50.838 (280/s) => 25.292 (562/s)
- 58998 assessments: 34.388 (1716/s)
- 6388 labs: 3.605 (1772/s)
- 119410 histories: 67.208 (1776/s)

Improve export performance via bulk queries

---

app/javascript/components/subject/CaseStatus.js

This PR is for [JIRA 375](https://jira.mitre.org/browse/SARAALERT-375).  Spoke with @hackrm and the following changes were made to the isolation workflow only:
- Changing from 'Confirmed' or 'Probable' to 'Suspect', 'Unknown' or 'Not a Case' now has the following language: `This case will be moved to the exposure workflow and will be placed in the symptomatic, non-reporting, or asymptomatic line list as appropriate to continue exposure monitoring.`
- Any case status changing to 'Confirmed' or 'Probable' does not show the case status modal, rather just update the case status and reload the page.  One question is if we still want to reload the page. In my opinion I think it helps the user know their change was accepted, which is why I left it in
The code is a hair janky but gets it done the …

Case status modal changes for isolation workflow

---

app/javascript/components/layout/Breadcrumb.js

takes care of [JIRA 409](https://jira.mitre.org/browse/SARAALERT-409)
I added a special case to check if the browser is safari to account for the history.go bug.  we'll have to remove this once that bug is fixed in safari

add special case to adjust the index if browser is safari

---

app/javascript/components/dashboard/widgets/RiskFactors.js
app/jobs/cache_analytics_job.rb
test/jobs/analytics_job_test.rb

Monitoree counts by country of exposure is currently not being displayed saying "no country data available" when there is data available.

Fix monitoree counts by country of exposure not being displayed

---

app/jobs/cache_analytics_job.rb
app/models/monitoree_map.rb
db/migrate/20200619192502_create_monitoree_maps.rb
db/schema.rb
lib/tasks/demo.rake
test/fixtures/patients.yml
test/jobs/analytics_job_test.rb

Wanted to actually put this PR out early to hopefully get this into the next release so that by the time the front end stuff is released, there will some existing historical data for the timeline already.
I decided to leave the value of states/counties in `monitoree_maps` as `null` for the categories where those fields are not present for patients that way we can be flexible with deciding/updating the wording of it in the front end whenever we want

Add monitoree maps to analytics

---

app/models/patient.rb

For [JIRA 459](https://jira.mitre.org/browse/SARAALERT-459)
Added a check to confirm that preferred contact method is email before sending - before if the preferred contact method was not set, it would sneak into this else.
See JIRA for recreate steps.  Can test using `Patient.find_by(id: <ID>).send_assessment` and changing the line in the conditional to `deliver_now`.

add additional check for preferred contact method when emailing web link

---

app/helpers/import_export_helper.rb
app/models/patient.rb
app/models/symptom.rb
test/system/roles/public_health/dashboard/export_verifier.rb
test/system/roles/public_health/public_health_test.rb

-[x] refactor assessments export code and fix bug
Patients: 41,720 (22,240 exposure / 19,489 isolation)
Assessments: 104,814
Laboratories: 29,840
Histories: 249,102
All monitorees excel: 5:19.778
Line list csv (exposure): 8.939
Line list csv (isolation): 18.856
Sara alert format (exposure): 28.195
Sara alert format (isolation): 36.259

Fix assessment symptoms not showing up in export bug

---

app/jobs/export_job.rb
config/environments/test.rb

Here are some numbers for non-system tests.
```
bundle exec rake test  10.39s user 1.88s system 85% cpu 14.313 total
bundle exec rake test  10.97s user 1.66s system 87% cpu 14.494 total
bundle exec rake test  10.42s user 1.72s system 87% cpu 13.915 total
bundle exec rake test  12.67s user 1.92s system 87% cpu 16.616 total
bundle exec rake test  11.39s user 1.89s system 87% cpu 15.146 total
bundle exec rake test  11.90s user 2.00s system 87% cpu 15.883 total
```
I'll let the system test run on this branch and see if that speaks for itself...

Disable logging when running tests unless env set

---

app/javascript/components/assessment/steps/SymptomsAssessment.js
config/locales/en.yml
config/locales/es.yml

This PR covers [JIRA 429](https://jira.mitre.org/browse/SARAALERT-429)
The solution we went with involved adding a 'I am not experiencing any symptoms' checkbox beneath all the boolean symptoms.  This checkbox is disabled if any of the boolean symptoms are selected.  In addition, the boolean symptoms are all disabled if the no symptom checkbox is selected.  This should also work in spanish.

Add no symptoms option to monitoree assessment

---

app/jobs/purge_job.rb

Was debating between putting this in the purge job vs cache analytics job and decided to go with putting it in the purge job because:
- putting it in the cache analytics job would slow it down a bit
- this isn't necessarily something that needs to happen every hour
If putting it in the cache analytics job or somewhere else makes more sense, I would be more than happy to change that.
I also set the cutoff to 1 month for now, but happy to change that as well. Currently, our analytics controller only fetches past analytics up to 2 weeks old.

Purge old analytics

---

app/javascript/components/dashboard/widgets/GeographicSummary.js

Before, the UI was showing 10 days ago by default. This PR changes that to show the most recent day first, and allows the user to scrub back (up to 10 days ago). The **10** day variable is configurable in the code.

Changes the initial day shown to the most recent day

---

app/javascript/components/dashboard/MonitorAnalytics.js
app/javascript/components/dashboard/widgets/GeographicSummary.js

If the analytics data was missing or not quite up to date, the front-end could crash. This PR now show error/warnings messages client-side to let the user know. This is unlikely to occur in production, but handles possible edge cases.

adds some checks for empty objects in the front-end

---

app/controllers/patients_controller.rb
app/javascript/components/assessment/steps/SymptomsAssessment.js
app/javascript/components/enrollment/steps/Contact.js
app/javascript/components/enrollment/steps/Exposure.js
app/javascript/components/subject/LastDateExposure.js
app/javascript/components/subject/MonitoringStatus.js
app/models/patient.rb
app/views/patients/show.html.erb
config/locales/en.yml
config/locales/es-PR.yml
config/locales/es.yml
config/locales/fr.yml
test/models/patient_test.rb
test/system/roles/enroller/enrollment/form_validator.rb

- Unknown is now the default contact method on enrollment
- Change LDE now resets continuous exposure status
- When no-symptoms is selected, make sure to blank out any other existing boolean options
- On close case in isolation, prompt for updating LDE for household contacts in exposure WF
- Added continuous exposure toggle to enrollment wizard (Exposure step)
- Line lists show "Continuous Exposure" for End of Monitoring column if continuous exposure is enabled

Address UAT-14 feedback

---

.github/PULL_REQUEST_TEMPLATE/bugfix_template.md
.github/PULL_REQUEST_TEMPLATE/default_template.md
.github/PULL_REQUEST_TEMPLATE/feature_template.md

Adds a few options for PR templates to our repository. 
This helps with ensuring that the same important information is readily available for reviewers of PRs. 
Because I've included multiple templates rather than just one (since there are different kinds of PRs), GitHub doesn't automatically pre-populate the PR body. In order to do so, you will need to manually navigate to the URL of the specific Markdown file you want to pre-populate in the pull request form.
For example, one of our templates for the most generic PR use case is `default_template.md`. When I'm ready to create a new pull request, to pre-populate my pull request form with the content of the `default_template.md` file, I need to navigate to the appropriate URL by passing an additional template parameter:
``` …
```

Adding PR Templates

---

app/javascript/components/layout/Breadcrumb.js

When logged in as an enroller. After clicking Finish and then Return to Dashboard, the user is returned to the start of the data entry dialog, not the dashboard.
1. Log in as enroller
2. Edit monitoree and click finish
3. Click Return to Dashboard
Added extra check in breadcrumb component for enrollers
This fix was tested on the following browsers:

Add extra check for return to dashboard for enrollers

---

app/javascript/components/analytics/widgets/CountyLevelMaps.js

Previously, the heat legend obstructed the view of Florida 
This has been changed so that it is now vertical and no longer obstructs any states or counties.
The Insular Maps still show a Horizontal Heat Legend as it does not obstruct any insular areas.
`CountyLevelMaps.js`

Align Heat Legend Vertical for Mainland USA Map

---

app/javascript/components/subject/MonitoringStatus.js
test/system/lib/system_test_utils.rb
test/system/roles/public_health/patient_page/actions.rb
test/system/roles/public_health/patient_page/history_verifier.rb
test/system/roles/public_health/public_health_test.rb
test/system/roles/public_health/public_health_test_helper.rb

Updating assigned user and monitoring reason on patient page does not save to db
1. Visit patient page as an epi
2. Update assigned user or monitoring status (with monitoring reason)
Change javascript variables in diffState from using camel case to underscore to match patient fields
`MonitoringStatus.js`
- Change javascript variables in diffState from using camel case to underscore to match patient fields
Added some extra assertions in system tests to ensure that something like this would be caught in the future if it happens again

Fix update assigned user and monitoring reason bug

---

app/javascript/components/subject/LastDateExposure.js
app/javascript/components/util/InfoTooltip.js

This Pull Request adds `End of Monitoring` Date to the Monitoree Detail Page for the Exposure Workflow. It comes with the associated `<InfoTooltip/>` to help show users where exactly it is derived from.

Adds End of Monitoring to Exposure Workflow Monitoree Detail Page

---

app/javascript/components/enrollment/steps/Review.js

Addresses [SARAALERT-581](https://jira.mitre.org/browse/SARAALERT-581)
Some users on IE were able to submit duplicates of a monitoree by clicking the submit button multiple times.
app/javascript/components/enrollment/steps/Review.js
- Calling submit method in setState callback to guarantee button disable before patient submission.
This fix was tested on the following browsers:
For some reason on IE11 and Safari I get a 500 when enrolling a monitoree on master and this branch, but I did confirm that I was unable to click the button more than once. Would love to know if reviewers can replicate the 500 locally for those two browsers.
You should never be able to click the "Finish" button or "Finish and Add Household Member" button when enrolling a new monitoree more than once. Please also …

SARAALERT-581: Prevent multiple patient submissions.

---

app/javascript/packs/stylesheets/application.scss

The analytics styling-code was removed from `application.scss` and put into its own file: `analytics.scss`. This file, however, was never included with the rest of the project, causing the County Level Maps to look wonky

Adds analytics stylesheet

---

app/controllers/assessments_controller.rb
app/controllers/export_controller.rb
app/controllers/fhir/r4/api_controller.rb
app/controllers/histories_controller.rb
app/controllers/laboratories_controller.rb
app/controllers/patients_controller.rb
app/jobs/close_subjects_job.rb
app/jobs/consume_assessments_job.rb
app/mailers/patient_mailer.rb
app/models/history.rb

Addresses SARAALERT-389
Refactor the way histories are created to use methods on the History model. Add in history entries for dependents when their head of household is contacted, when the system automatically closes a monitoree, and when a welcome message is sent.
`history.rb`
- Added several new class methods for creating a History.
- Added new types of history to support the feature request.
`consume_assessment_job.rb`
- Did not use the class methods for inserting dependent history for a small optimization.
`close_subjects_job.rb`
- Consolidated logic
- Create a History when the system closes out a monitoree.
`patient_mailer.rb`
- Create a new type of History when a welcome email is sent.

Log Additional System Actions in History

---

app/javascript/components/subject/CaseStatus.js

Jira Ticket: SARAALERT-573
https://jira.mitre.org/browse/SARAALERT-573
In the PUI line list, if the "Case Status" is changed to “suspect”, “unknown”, and “not a case”, the record stays in the PUI workflow until the User manually sets “Public Health Action” to None. The action that actually triggers the record to move is not “Case status”, but is “Latest Public Health Action”. The intention is that setting “suspect”, “unknown”, and “not a case” for Case Status will automatically change “Latest Public Health Action” to none (and thus move the record off PUI to appropriate Exposure line list).
- Select a monitoree from the PUI line list
- Change their cast status to 'Suspect', 'Unknown' or 'Not a Case' 
- Latest public health action does not update to 'None' (remains whatever it was …

Automatically update public health action when case status is changed

---

app/views/admin/index.html.erb

Right now USA Admins get 504s when trying to access the admin page because the query takes too long and exceeds the 15 second timeout. This PR updates the query for the Admin page data to be a lot faster. It's really a temporary fix until the Admin page refactor goes in. 
It does this by removing calls to the `jurisdiction_path` method in the User model and using a join instead to access the jurisdiction path. This reduces the number of queries overall pretty significantly. 
For each version of the query, I ran it 10 times with 7117 users and took the average of the runtime. 
(When running the old version once it took 28 seconds pretty consistently, when running 10 times in a row and averaging it went to 40+ seconds, which I think is a result of my computer struggling …

(Hotfix) Updating query in Admin view to be faster

---

app/jobs/send_assessments_job.rb
app/mailers/patient_mailer.rb
app/models/patient.rb

Description*
Various tweaks to improve job performance and simplify database interactions
Changes include:
- Set last_assessment_reminder_sent in bulk instead of individually
`patient.rb`
- Return id if reached the end of the send assessment method (nil otherwise)
`patient_mailer.rb`
- Removed extra updates for last assessment sent
`send_assessment_job.rb`
- Collect ids of patients who were sent notifications, then do a bulk update

Tweaks to improve assessment send job performance

---

app/javascript/components/enrollment/Enrollment.js
app/javascript/components/enrollment/steps/Identification.js

Addresses SARAALERT-522
This PR allows the Enrollers to adjust the workflow from within the `Monitoree Detail` page.
`app/javascript/components/enrollment/Enrollment.js`
`app/javascript/components/enrollment/steps/Identification.js`
1. When enrolling Households, members of the household will assume the workflow of the Head of Household
2. When viewing the Exposure linelists, any new monitorees will assume the `Exposure` workflow. The same is true from the `Isolation` workflow
3. The React-Select component on the `Monitoree Detail` page has had its styling changed so the cursor is now a pointer.

Change workflow in details

---

app/javascript/components/subject/MonitoringStatus.js

Jira Ticket: [SARAALERT-533](https://jira.mitre.org/browse/SARAALERT-533)
Currently, when a user transfers a case in the Isolation dashboard out of their jurisdiction, Sara Alert loads the page after the transfer so the user is on the Exposure Dashboard view. I would expect the Isolation Dashboard view to load instead. Update Sara Alert so that after a case is transferred out of the jurisdiction, the user will be brought back to the Isolation dashboard instead of the exposure dashboard.
Log in as `state1_epi_enroller`. Navigate to the isolation workflow and select a monitoree.  Change the jurisdiction to something in State 2 and click submit.  You are redirected to the exposure workflow.
Before, when `location.reload(true)` goes to reload the page fresh from the server, however the …

After case transferred out, user taken back to correct dashboard

---

config/initializers/sidekiq.rb

Increases the network timeout as described [here](https://github.com/mperham/sidekiq/wiki/Using-Redis#life-in-the-cloud) to help potentially address timeout issues with slower commands on production.
Still want to read more about any repercussions here, and need to test - though not entirely sure there's much testing we can do other than checking everything works fine on test and demo.

(WIP) Increasing Sidekiq Redis network timeout

---

app/javascript/packs/authy.js
app/views/devise/devise_authy/enable_authy.html.erb

Jira Ticket: [SARAALERT-530](https://tracker.codev.mitre.org/browse/SARAALERT-530)
Authy enable country code dropdown improperly renders on demo server only but works locally
Have an admin enable authy on your demo server account and view the enable page
Not sure if this fixes the problem so TBD
`authy.js`
Reviewer: holmesie
Checklist:
Reviewer: kylietmo
Checklist:

fix authy styling on the demo server

---

app/controllers/patients_controller.rb
app/jobs/consume_assessments_job.rb
app/jobs/purge_job.rb
app/models/patient.rb

Jira Ticket: SARAALERT-590
This is a really small ticket - just wrote a new method called `dependents_exclude_self` in the `Patient` model for ease of use since we make this query often.
There should be no functionality changes as part of this PR. That being said, we can test that the following functionality still propagates to dependents correctly:
- Updating the monitoring status
- Any sort of edits that should propagate to dependents
- Updating the history of dependents when consuming an assessment

SARAALERT-590: Patient model method for getting dependents except self

---

.github/PULL_REQUEST_TEMPLATE.md
app/controllers/patients_controller.rb
app/javascript/components/util/InfoTooltip.js
app/mailers/patient_mailer.rb
app/models/patient.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-724](https://tracker.codev.mitre.org/browse/SARAALERT-724)
**This PR addresses the following:**
- A bug where HoHs that are out of the monitoring period (current date is > LDE+14) will not receive notifications for active dependents. This is because of an extra check we were doing in the `reminder_eligible` scope that wasn't necessary given the [checks](https://github.com/SaraAlert/SaraAlert/blob/bcd8152b71d57520f66362854053370ef301413f/app/models/patient.rb#L456) done currently in `send_assessment`.
For context: `monitoring` is true for a given patient in the following cases (assuming not purged and not manually closed):
- within monitoring period (LDE + 14 days) (exposure workflow)
- continuous_exposure is true (exposure workflow)
- in isolation (isolation …

SARAALERT-724: Update reminder_eligible scope, Patient mailers, and toggle continuous_exposure off when closed.

---

app/controllers/import_controller.rb
app/controllers/patients_controller.rb
app/javascript/components/enrollment/Enrollment.js
app/javascript/components/public_health/Import.js
app/models/patient.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-376](https://tracker.codev.mitre.org/browse/SARAALERT-376)
This PR updates the class method on the Patient model for detecting duplicates records to return more information that the frontend can use to communicate what the match criteria for the duplicate was exactly. It will show the number of records that meet the duplicate criteria as follows:
- matching first name, last name, sex, AND DoB
OR
- matching state/local ID
Import example:
Enrollment example:
- Updating `matches` class method to be called `duplicate_data` and return more information.
`app/controllers/import_controller.rb` and `app/controllers/patients_controller.rb`
- Changed to call new updated in Patient model
`app/javascript/components/enrollment/Enrollment.js`
- Showing a …

SARAALERT-376:  Show duplicate match criteria for duplicate detection on import and enroll UI message

---

app/javascript/packs/stylesheets/bootstrap.scss
app/views/layouts/application.html.erb

Adds a watermark to explicitly indicate (beyond the yellow warning banner) that a demo instance is a demo instance.
`app/views/layouts/application.html.erb`
- Inject background css class if in demo mode
`app/javascript/packs/stylesheets/bootstrap.scss`
- Added SVG based background for demo mode

Added watermark for demo instances

---

app/jobs/consume_assessments_job.rb
app/mailers/patient_mailer.rb
app/models/patient.rb

**This PR does the following:**
- Fixes bug in ConsumeAssessmentsJob where assessments wouldn't be made for a patient after they responded if they were closed but had continuous_monitoring toggled on. 
- Breaks out logic checking for what I've been calling "active dependents" into a Patient model method to avoid this in the future. Basically, this check is necessary in these places because there could be dependents (including the HoH) that are not being monitored that no longer are eligible for an assessment within a household. All of the other notification eligibility checks for the HoH will have been done prior.  …

Fixed logic for edge case in ConsumeAssessmentJob and broke logic out into new Patient method.

---

app/views/patients/show.html.erb

https://tracker.codev.mitre.org/browse/SARAALERT-598
"USA" should not show up in the Jurisdiction transfer list in the patient view page
Open up a patient, search  for "USA", in the jurisdiction list, it should not be there.

Omit USA jurisdiction from jurisdictionPaths

---

app/jobs/export_job.rb
app/mailers/user_mailer.rb
app/views/user_mailer/download_email.html.erb

Limits number of records considered for a single export file to handle max file size limit, in response to errors seen on production. Doesn't exclude data, just breaks it up into separate files if record limit is reached.

Break exports up into batches of 10k patients

---

app/javascript/packs/stylesheets/bootstrap.scss

Jira Ticket: [SARAALERT-741](https://tracker.codev.mitre.org/browse/SARAALERT-741)
User can see other elements behind certain dropdown menus (datepicker, react select) even when they are open.  See screenshots in the JIRA ticket for additional examples.
On master, login as an admin and click `add user` or `edit` in one of the user rows.  Open up the jurisdiction or role dropdown menu and you will be able to see text that is not contained in that menu.  You can also recreate this with the primary language dropdown and some datepicker fields when enrolling a monitoree.
This actually ended up not being an issue with the dropdowns but rather the react `<Form.Check>` element we use.  React bootstrap adds a class (`.custom-control`) to the check element that sets the z-index at 1, causing it to …

Fix issue with dropdown modals being transparent

---

app/jobs/close_subjects_job.rb
app/models/patient.rb

Jira Ticket: SARAALERT-743
We removed logic recently specifically checking for LDE as it was causing the bug where HoHs that were out of the monitoring period but with active dependents were not getting messages. That same line was both causing that bug and preventing messages from being sent to folks past their monitoring period but not closed out in exposure (on the non-reporting line list). This PR adds a check back in that handles that case, but does not reintroduce the HoH bug. 
This is the PR that removed this logic and fixed the HoH bug: https://github.com/SaraAlert/SaraAlert/pull/334/files#diff-9c324f49a7c201a8392c7c309c6477f2L79
The key thing to note is that checking for `monitoring` actually isn't sufficient, because we do not set monitoring to false when folks are on the …

SARAALERT-743: Logic updates to send_assessment and CloseSubjectsJob

---

app/javascript/components/assessment/steps/SymptomsAssessment.js
app/javascript/components/close_contact/CloseContact.js
app/javascript/components/history/HistoryComponent.js
app/javascript/components/laboratory/Laboratory.js

Jira Ticket: [SARAALERT-756](https://tracker.codev.mitre.org/browse/SARAALERT-756)
Double clicking the "Submit"  or "Create" button many times very fast it will create duplicate objects.  This applies to the following buttons:
- `Add New Lab Result` in the lab results section
- `Add New Report` in the reports section
- `Add Comment` in history section
- `Add New Close Contact` in close contact section
I _think_ these are all the buttons that will result in creating multiple objects when clicked fast, but someone else should double check this.
Pick one of the buttons above and click really fast when you submit.  You should see many new objects that are all the same appear.
Created a loading boolean that is kept in state and use that to disable/enable the submit button
Please list important …

Multiple click button bug

---

app/jobs/export_job.rb

Adds back missing extension. As of right now, for this particular export folks have to manually add the extension back.
`app/jobs/export_job.rb`
- Adds missing variable.
Can test locally by manually running job for `full_history_purgeable` export.

Add extension to filename for full_history_purgable export.

---

app/views/patients/show.html.erb

SARAALERT-776: Updating reports table to horizontally scroll and sorting columns.
- To handle more symptoms, reports table needs to scroll. We also want columns to be sorted to be consistent.

SARAALERT-776: Updating reports table to horizontally scroll and sorting columns.

---

app/javascript/components/enrollment/steps/Contact.js
app/javascript/components/enrollment/steps/Exposure.js
app/javascript/components/public_health/PatientsTable.js
app/javascript/components/subject/ExtendedIsolation.js
app/javascript/components/subject/LastDateExposure.js
app/javascript/components/subject/SymptomOnset.js
app/javascript/components/util/InfoTooltip.js
config/locales/es-PR.yml
config/locales/es.yml
config/locales/fr.yml
config/locales/so.yml
config/sara/jurisdictions.yml
test/system/roles/enroller/enrollment/form_validator.rb

Smaller updates before 1.12 release.
- Updated language in tooltips, modals,  validation based on product team feedback.
- Adding tooltip to extended isolation line list column.
- Removing min date for symptom onset and LDE only, maintaining for Extended Isolation per product team request.
- Adding locale translations.
- Updated default `jurisdictions.yml` to use new symptoms. 
NOTE: This is already deployed on demo for testing.

1.12 Updates

---

app/javascript/components/admin/AdminTable.js

Jira Ticket: SARAALERT-699
It is expected that when an Admin user sorts the table based on one of the columns, when that user does some action that updates the table (such as add a new user, view the next page of users, or search across the Admin table) the table records remain sorted based.
Sort the Admin table by Jurisdiction so users with USA jurisdiction appear at the top.
Search for USA in search box.
Observe that the table is no longer sorted based on jurisdiction and won't be until the user clicks on it again.
Whenever a column in the admin table was sorted, the state was not actually updated, so whenever another filter was applied, the sorting params would be lost. This is now fixed by updating the state with the sorting params.
Please list important files (meaning substantial or …

SARAALERT-699: Fix admin table sort persistence

---

app/javascript/components/assessment/steps/SymptomsAssessment.js
app/javascript/components/enrollment/steps/Exposure.js
app/javascript/components/enrollment/steps/Identification.js
app/javascript/components/public_health/actions/CloseRecords.js
app/javascript/components/public_health/actions/UpdateCaseStatus.js
app/javascript/components/subject/CaseStatus.js
app/javascript/components/subject/LastDateExposure.js
app/javascript/components/subject/MonitoringStatus.js
app/javascript/components/util/InfoTooltip.js

Jira Ticket: SARAALERT-796
Disabled CE when record is closed. Added tooltips for more information about CE. CE toggle is now a checkbox.
`app/javascript/components/subject/LastDateExposure.js `
- Disabled CE when record is closed. Added tooltips for more information about CE. CE toggle is now a checkbox.
`app/javascript/components/util/InfoTooltip.js `
- New CE tooltip

Disable CE when closed; CE Tooltips

---

app/javascript/components/subject/LastDateExposure.js
app/javascript/components/subject/MonitoringStatus.js

Jira Ticket: [SARAALERT-780](https://tracker.codev.mitre.org/browse/SARAALERT-780)
Incorporates the changes described in these mockups: https://tracker.codev.mitre.org/secure/attachment/30816/monitoringstatusupdate.pptx 
New modal breaks up monitoring status from LDE changes.  Use a monitoree in the isolation workflow that is the head of household to view these changes.
These changes apply to all modals in `MonitoringStatus.js` which include monitoring status, monitoring plan, exposure risk assessment, jurisdiction, assigned user, public health action, isolation and notifications .  Be sure to check these modals to make sure everything makes sense as it did before.
Please list important files (meaning substantial or …

Improve clarity of monitoring status modal

---

app/views/user_mailer/download_email.html.erb

Jira Ticket: [SARAALERT-769](https://tracker.codev.mitre.org/browse/SARAALERT-769)
We realized we are not actually imposing the 24 hour deadline on exports, and didn't need to. So this PR removes that language from the export download email. 
Before: 
After:
`app/views/user_mailer/download_email.html.erb`
- Updated language.
Run locally with Redis and Sidekiq running and do an export to see updated text email.

SARAALERT-769: Update text on Download email.

---

app/views/user_mailer/download_email.html.erb

Jira Ticket: [SARAALERT-820](https://tracker.codev.mitre.org/browse/SARAALERT-820)
Add a blank line between paragraphs and format the numbers with commas in the download email text.
`download_email.html.erb`: added text formatting
Run `UserMailer.download_email(User.first, 'full_history_all', [{lookup: 'blah', filename: 'blah'}], 10000).deliver_now` in the rails console and the email will open in chrome for viewing.

Download email text formatting

---

app/controllers/patients_controller.rb

Jira Ticket: [SARAALERT-811](https://tracker.codev.mitre.org/browse/SARAALERT-811)
Only self-reporters and HoHs should be receiving enrollment notifications. Currently, dependents will receive an empty email notification, for example, which should not be the case. 
`app/controllers/patients_controller.rb`
- Adds a check before sending an enrollment notification.
To test this fix, run locally on `master` and enroll a new monitoree with email as preferred contact method and a provided email, and then a household member underneath that monitoree (with the same preferences - email can be different).  You'll see an email go out to both the HoH and the dependent, but the dependent email will be empty. If you then do the same on this PR branch, you'll notice the dependent will no longer get an …

SARAALERT-811: Do not send enrollment notifications to non-reporters

---

app/controllers/patients_controller.rb
app/javascript/components/public_health/actions/CloseRecords.js
app/javascript/components/public_health/actions/UpdateCaseStatus.js
app/javascript/components/subject/CaseStatus.js
app/javascript/components/subject/ExtendedIsolation.js
app/javascript/components/subject/LastDateExposure.js
app/javascript/components/subject/MonitoringStatus.js
app/javascript/components/subject/PauseNotifications.js
app/javascript/components/subject/SymptomOnset.js
app/models/assessment.rb
app/models/history.rb
test/system/roles/public_health/patient_page/history_verifier.rb
test/system/workflow/workflow_test.rb

Jira Ticket: SARAALERT-675
Log any changes to `last_date_of_exposure`, `symptom_onset`, `continuous_exposure`, `extended_isolation` dates in history. For symptom onset, log system changes as well and indicate if it was a user or system change.

SARAALERT-675: Log changes to LDE, symptom onset, continuous exposure, extended isolation in history

---

app/javascript/components/subject/CaseStatus.js

Jira Ticket: [SARAALERT-763](https://tracker.codev.mitre.org/browse/SARAALERT-763)
Bug 2.2 is not behaving quite right in this JIRA ticket (see below to recreate)
Select a monitoree in the isolation workflow with a case status that is not `blank`.  Change the case status to `blank` and the monitoree is no longer in the isolation workflow.
An additional check if the new case status is `blank` was missing in the current logic.
`CaseStatus.js`: added an additional check for if case status is blank …

additional check for if case_status is blank

---

app/controllers/patients_controller.rb
app/javascript/components/close_contact/CloseContact.js
app/javascript/components/enrollment/steps/Contact.js

Jira Ticket: SARAALERT-747
Per user request, it would be nice if, when enrolling a Close Contact, the Close Contact's notes were pre-populated into the Exposure Notes in the final card in the enrollment carousel. 
`app/javascript/components/close_contact/CloseContact.js`
- Added placeholder text depending on the Monitoree's Workflow. The logic is quite simple.
``` 
this.closeContactNotePlaceholder = this.props.patient.isolation
? 'enter additional information about case'
: 'enter additional information about monitoree’s potential exposure';
```
`app/controllers/patients_controller.rb`
- Now pre-fills the exposure notes when enrolling a Close Contact that has Notes
`app/javascript/components/enrollment/steps/Contact.js`
- Now checks for the existence of an email address to decide whether …

Pre-fills the Exposure Notes section when Enrolling Close Contact

---

app/models/patient.rb

Jira Ticket: [SARAALERT-826](https://tracker.codev.mitre.org/browse/SARAALERT-826)
1. Click on a record that is eligible for notifications.
2. Move the record to the closed line list by changing the Monitoring Status to "Not Monitoring."
3. Notice that the eligibility icon has not changed.
Added a check to the logic that supports that eligibility icon to check the monitoring status.
- Added check to see if the record is actively being monitored. 
Replicate the above steps and notice the icon now updates appropriately.

SARAALERT-826: (Bugfix) Updating the UI eligibility icon logic to check for closed records.

---

app/models/patient.rb
test/models/patient_test.rb

The current logic for the close job for 1.13 uses the asymptomatic scope logic, but that is not enough as we need to check that a monitoree has submitted an assessment _that day_ before closing them out. This of course needs to be based on their timezone as well. Without this more strict check on the `latest_assessment_at`, folks could get closed out on their last day of monitoring if they submitted an assessment within the past 24 hours, when really they needed to have submitted an assessment that day. 
- Updated logic in `close_eligible` method to handle this case.
`test/models/patient_test.rb`
- Removed now obselete tests and added new ones.
The automated tests are still passing, and more testing on demo will need to be done as well. For testing locally, you can …

(Bugfix) 1.13 Close Job Logic Update

---

app/controllers/patients_controller.rb
app/controllers/public_health_controller.rb
app/javascript/components/subject/MoveToHousehold.js
config/routes.rb

Jira Ticket: [SARAALERT-745](https://tracker.codev.mitre.org/browse/SARAALERT-745)
When logged in as enroller, an error occurs when trying to move a monitoree to a household.
- login as enroller
- view a patient that is not part of a household
- click on 'Move To Household'
- moved household members endpoint from public health to patients controller

SARAALERT-745: Cannot add monitoree to household in enroller role

---

app/controllers/patients_controller.rb
app/javascript/components/subject/CaseStatus.js
app/javascript/components/subject/ExtendedIsolation.js
app/javascript/components/subject/LastDateExposure.js
app/javascript/components/subject/MonitoringStatus.js
app/models/history.rb

Jira Ticket: [SARAALERT-853](https://tracker.codev.mitre.org/browse/SARAALERT-853)
Address bugs 1, 2, 3, and 5 here:
https://mitre.sharepoint.com/:p:/s/CoVDT/EV_Gowrz3RBFrFwwB_bKnJkB3F95f7_z8674ndyCst0mcg?e=B9tXcx
See ppt
Bug 1
- clearing PH action after case status change between not a case/unkown/suspect happens in the back end instead of front end now for custom history message
Bug 2
- add separate messages for modals when monitoree is closed
Bug 3
- replaced "toggled" with "turned"
- added "on/off" to modal message
Bug 5
- do not use monitoree's existing monitoring_reason for future Monitoring Status changes
- …

SARAALERT-853: Address 1.14 testing bugs

---

app/models/patient.rb
test/controllers/fhir/r4/api_controller_test.rb
test/models/patient_test.rb

This is taking over from #375 because I couldn't push changes to @Sepiidae fork.
This PR will calculate the age of the patient on create when using the FHIR API. 
To accomplish this I've added new functions in `models/patient.rb` which attempt to parse the provided date of birth in the 3 valid FHIR `date` formats. (Found [here](https://www.hl7.org/fhir/datatypes.html#date)) and switched the current calculate date to use a static method so the code for calculating the date is not duplicated.

Calculate patient age api create

---

app/models/patient.rb
test/models/patient_test.rb

- Updates language for when a record is closed and not part of a household.
- Updated logic so that if a HoH is past their monitoring period but has monitored dependents they are still eligible.

Eligibility Tooltip Fixes

---

app/models/patient.rb

Make assessment eligibility logic (eligibility icon/send_assessments method) fall back on created_at if LDE is nil.
`app/models/patient.rb `
- Default to created_at if LDE is nil in send_assessment and eligibility calc

Report Eligibility calcs should fall back on created_at if no LDE

---

test/controllers/admin_controller_test.rb

Jira Ticket: [SARAALERT-728](https://tracker.codev.mitre.org/browse/SARAALERT-728)
Admin controller tests would fail every so often because of improper setup for the tests. 
`test/controllers/admin_controller_test.rb`
- Clearing ActionMailer deliveries on setup rather than teardown.
- Swapping params on assertion so expected and actual were accurate.

SARAALERT-728: Admin Controller tests failing intermittently

---

app/jobs/close_patients_job.rb
test/jobs/close_patients_job_test.rb

Currently it is possible for a record to have a nil last date of exposure AND continuous exposure set to false. We are currently working on preventing this in 1.15. However, as of right now, this causes an issue in the close job for those records due to a missing nil check. This PR adds the check and also adds a test to cover this case in the future.
`app/jobs/close_patients_job.rb`
- Added nil check.
`test/jobs/close_patients_job_test.rb`
- Added test to cover this case.
New test should cover this, but run the close job when there is a monitoree with a nil LDE, continuous exposure set to false, and that was created more than 14 days ago.

(Bugfix) Addressing Edge Case for Close Patients Job

---

config/initializers/filter_parameter_logging.rb

Jira Ticket: SARAALERT-855
Adds PII/PHI parameters so that built-in Rails filtering will hide these values from from application logs.
`config/initializers/filter_parameter_logging.rb`
- Add fields/columns to be filtered for various models/tables

Add pii/phi fields to parameter logging filters

---

app/controllers/patients_controller.rb
app/javascript/components/subject/LastDateExposure.js

Jira Ticket: SARAALERT-886
It should not be possible for continuous exposure to be turned on for a closed record. This is prevented in other ways, but we needed to handle the case where a user chooses to update all household members when updating the continuous exposure for a record in a household. This PR handles that case by updating the language when updating continuous exposure for household members to specify non-closed members, and from preventing the change from happening to closed records. 
New language in modal when updating continuous exposure:
Language is unchanged when updating LDE.
`app/controllers/patients_controller.rb`
- Updated `update_fields()` method to prevent continuous exposure from being updated for closed records. …

SARAALERT-886: Prevent records from continuous exposure of household members that are closed.

---

.github/workflows/anchore-analysis.yml
.github/workflows/static.yml
.github/workflows/test.yml

Running actions on only `push` rather than both on `push` and on `pull_request` as that was redundant. You may have noticed them running twice on PRs because of this.

GitHub Actions Update

---

app/javascript/components/layout/CustomTable.js
app/javascript/packs/stylesheets/custom_table.scss

Jira Ticket: SARAALERT-692
Fixing UI issue where the pagination drop down for the Custom Table wasn't sizing properly in Internet Explorer.
_Original issue_:
_Resolved and displays as_:
1. Run Sara Alert 
2. Open up Sara Alert on Internet Explorer and login as either an Admin or Public Health User
3. Scroll to the bottom of the table and you will find the pagination drop down renders improperly as shown in the above screenshot 
Updated the Custom Table class to ensure the row that encloses the pagination drop down is sized large enough.
`CustomTable.js`
- Set a fixed size for the row that encloses the pagination drop down so it is large enough for each browser.
1. Run Sara Alert 
2. Open up Sara …

UI fix for IE11

---

app/controllers/patients_controller.rb

Jira Ticket: [SARAALERT-793](https://tracker.codev.mitre.org/browse/SARAALERT-793)
Case Status field should not auto-populate for dependents upon enrollment
Go to an existing monitoree and click `edit details`.  From there, click `Finish and Add a Household Member` and go through the enrollment process.  For isolation workflow, a case status option will show up in the carousel, this should have the case status of the HoH.  For exposure, continue through the carousel and submit - the new monitoree will have the same case status as the HoH.
In `patients_controller.rb`, there is a `group_member_subset` list that indicates all the fields that should be copied over from the HoH.  Removing `case_status` from this list fixes this bug.
Please list important files (meaning substantial or integral …

SARAALERT-793: Case Status field should not auto-populate for dependents upon enrollment

---

README.md

This PR updates `README.md` to indicate that Redis should be running before running the tasks to initialize the database. It also adds a note that the README contains installation instructions for Redis.
`README.md`

Update README to indicate when to start Redis

---

app/controllers/public_health_controller.rb
app/javascript/components/layout/CustomTable.js
app/javascript/components/public_health/PatientsTable.js
app/javascript/packs/stylesheets/datatables.scss

Jira Ticket: [SARAALERT-732](https://tracker.codev.mitre.org/browse/SARAALERT-732)
Add designation for HoH on the monitoree linelists - use H icon in the name column
`public_health_controller.rb`
- Added is_hoh bool to the linelist fields, which is used to hide/show HoH icon
`CustomTable.js`
- Pass in additional HoH bool to the col filter method
`PatientsTable.js`
- Updated linkPatient method to add H icon for HoH
Please describe the tests needed to verify your changes. Provide instructions for reproducing these tests. List any relevant details …

Add HoH designation to the monitoree column of the line list

---

app/javascript/components/public_health/PatientsTable.js
app/javascript/packs/stylesheets/bootstrap.scss
app/javascript/packs/stylesheets/datatables.scss

Jira Ticket: [SARAALERT-732](https://tracker.codev.mitre.org/browse/SARAALERT-732)
Update Head of Household designation in the linelist to reduce confusion of people thinking it means hospital.  Also add a tooltip that says: "Monitoree is Head of Household that reports on behalf of household members"
`PatientsTable.js`
- removed `H` icon and inserted a `HoH` badge instead with a clarifying tooltip
`bootstrap.scss`
- moved styling from `datatables.scss` to here because now it modifies the bootstrap badge
Please describe the tests needed to verify …

Updates to the Head of Household Icon

---

app/jobs/send_purge_warnings_job.rb
app/mailers/user_mailer.rb
app/views/user_mailer/send_purge_warnings_job_email.html.erb
test/jobs/send_purge_warnings_job_test.rb

This PR update the  `SendPurgeWarningsJob` so it sends an email outlining if for any reason it fails or couldn't send an email to users. It required a bit of a refactor of where the logic lives which makes it more consistent with other jobs and `UserMailer` functions anyway.
`app/jobs/send_purge_warnings_job.rb`
- Pulled in logic from `UserMailer` to iterate through users and send email with number emails sent, not sent, and eligible.
`app/mailers/user_mailer.rb`
- Updated original `purge_notification` mailer method to have less logic (since it's been moved into the job). 
- Added `send_purge_warnings_job_email` method.
`app/views/user_mailer/send_purge_warnings_job_email.html.erb`
- Added new email template.
`test/jobs/send_purge_warnings_job_test.rb`
- Adding tests for this job (WIP).
- …

Updating Send Purge Warnings Job to send email to verify run

---

app/javascript/components/util/InfoTooltip.js

Updates latest public health action tooltip message in isolation to be more clear
`InfoTooltip.js`
- update latest public health action tooltip message in isolation

Update latest public health action tooltip message in isolation

---

app/controllers/public_health_controller.rb
docker-compose.prod.yml
docker-compose.yml
nginx.conf

Jira Ticket: [SARAALERT-787](https://tracker.codev.mitre.org/browse/SARAALERT-787)
This adds separates out the API to run on a separate Sara Alert instance in a separate Docker container from the core application.
`docker-compose.yml`
- Added a `service` for the API. Aside from the name, this is identical to `sara-alert-enrollment`. This means they the same MySQL database and Redis instance.
`docker-compose.prod.yml`
- Just the corresponding entry for the API service here that pulls the `latest` tag.
`nginx.conf`
- Now routes API and OAuth requests to the API instance, based on a URL path regex.
There are no tests relevant to these changes. We will want to manually test this on the demo server …

SARAALERT-787: Dockerize API

---

app/controllers/fhir/r4/api_controller.rb

Enrollment notifications should only be received by self-reporters. This PR just makes that logic consistent in the API.

Making Enrollment Notification Logic Consistent in API

---

app/javascript/components/subject/MonitoringStatus.js

Jira Ticket: SARAALERT-837
When changing the `Exposure Risk Assessment` it had been impossible to change back to `null/blank` after selecting an Exposure Risk Assessment Value. This PR removes that disabled flag. It also ensures the resultant prompt is worded properly (not saying `"Are you sure you want to set the value to ''?"`).
`app/javascript/components/subject/MonitoringStatus.js`
- Removes the `disabled` flag for `Exposure Risk Assessment` select
The existing logic for this `<select/>` prompts the user "Are you sure you want to change XXX to YYY?". This lead to the prompt asking `Are you sure you want to exposure risk assessment to ""?`. This is obviously not ideal. I reached out to the ticket reporter Lauren Buttling and asked her opinion on the exact wording. She said "I think we …

allows the user to set 'Exposure Risk Assessment' to null

---

app/javascript/components/enrollment/Enrollment.js
app/javascript/components/enrollment/steps/AdditionalPlannedTravel.js
app/javascript/components/enrollment/steps/Address.js
app/javascript/components/enrollment/steps/Arrival.js
app/javascript/components/enrollment/steps/Contact.js
app/javascript/components/enrollment/steps/Exposure.js
app/javascript/components/enrollment/steps/Identification.js
app/javascript/components/enrollment/steps/Review.js
app/javascript/components/subject/LastDateExposure.js
app/javascript/components/util/DateInput.js
test/system/roles/enroller/enrollment/form_validator.rb

Jira Ticket: [SARAALERT-835](https://tracker.codev.mitre.org/browse/SARAALERT-835)
Essentially, we want to make sure that a given monitoree must have a valid LDE OR continuous exposure turned on. 
- Allow a monitoree to be enrolled into exposure workflow without having to add an LDE ONLY IF they select continuous exposure.
- When continuous exposure is turned off for a monitoree, they should be prompted to enter an LDE. It should NOT be possible for a monitoree to have both no LDE and continuous exposure turned off.
- When continuous exposure is turned on, the user should be prompted and the LDE should be cleared out. If a monitoree has continuous exposure turned on, there should not also be a LDE. 
`LastDateExposure.js`
- updated modal messages depending on LDE and CE state
- added date …

SARAALERT-835: Handle monitoree LDE state

---

app/javascript/components/enrollment/Enrollment.js
app/javascript/components/enrollment/steps/Exposure.js
app/javascript/components/enrollment/steps/Review.js

Jira Ticket: SARAALERT-835
- modifies LDE/CE input validation behavior in enrollment so that instead of LDE being disabled when CE is checked, CE will be turned off when LDE is populated
- fixes 'Finish and Add a Household Member' button in enrollment so that household member will always be enrolled as a dependent of HoH and not another household member
- fixes exposure enrollment page validation when starting enrollment from isolation but changing to exposure from identification page

SARAALERT-835: LDE/CE Validations

---

app/controllers/patients_controller.rb
app/javascript/components/history/HistoryComponent.js
app/views/patients/show.html.erb

Jira Ticket: SARAALERT-713
The previous behavior was that the client maintained a duplicate list of the HISTORY_TYPES for filtering in the History Component. If any items were added to the back-end, they had to be copied over to the client. This PR changes the behavior so that the HISTORY_TYPES are sent to the front-end as `props`. This object is then formatted for the `<select/>`.
`app/controllers/patients_controller.rb`
- Adds the list of `HISTORY_TYPES` to the controller
`app/views/patients/show.html.erb`
- Includes the `HISTORY_TYPES` as props for the `HistoryComponent` component.
`app/javascript/components/history/HistoryComponent.js`
- Formats the new props object to be used in the `<select/>` filter.

SARAALERT-713

---

app/javascript/components/close_contact/CloseContact.js
app/javascript/components/enrollment/steps/Exposure.js
app/javascript/packs/stylesheets/layout.scss

Jira Ticket: SARAALERT-887
This PR sets a limit for the characters allowed in the Close Contact Notes section. If a Close Contact was enrolled, and their notes section was (previously) over 2,000 characters than the user would run into errors enrolling them. By limiting the characters to a length of 2,000 any overflow errors are avoided.
`SaraAlert/app/javascript/components/close_contact/CloseContact.js`
- added character limit

Limits Character limit for Close-Contact Notes 

---

app/javascript/components/history/HistoryComponent.js

Jira Ticket: SARAALERT-883
Adds a filter option to see only history objects created by a specific user or by the SARA-Alert system 
`app/javascript/components/history/HistoryComponent.js`
* [Y] Firefox
Spin up the service, login as a public health user or another role …

SARA-883 histories filter

---

app/controllers/patients_controller.rb
app/javascript/components/enrollment/steps/Contact.js
app/models/patient.rb
config/routes.rb

Jira Ticket: SARAALERT-568
Refactor of send_assessment method to simplify (and clarify) logic. Made emails follow similar timing checks to text and voice. Removed old send reminder route.
`app/controllers/patients_controller.rb `
- Removed old send reminder method
`config/routes.rb`
- Removed old send reminder method route
`app/javascript/components/enrollment/steps/Contact.js `
- Made preferred contact time option pop up for email
- Refactor of send_assessment method to simplify (and clarify) logic. Made emails follow similar timing checks to text and voice.
Enroll new monitoree, and give them preferred contact time. Run send assessment query in console. Test on demo.

SARAALERT-568: Preferred Contact Time for emails, send_assessment tests

---

app/javascript/components/public_health/Import.js

Jira Ticket: SARAALERT-638
The `age` field was not being computed for monitorees when they were imported. This PR computes the `age` for each monitoree going to be imported. It then includes this field when the monitoree data is sent server-side. This mimics the behavior for standard enrollment and solves the bug.
Previously:
1. Enroll a monitoree by importing them
2. View their details and notice that the `age` field is blank.
Now:
1. Import a monitoree
2. View their details and notice that the `age` field is *not* blank.
The `age` field (during standard enrollment) is calculated client-side during the enrollment process. This PR adds client-side calculations for the `age` field to the Import process.
`app/javascript/components/public_health/Import.js`
- Adds `age` computation for each …

Import Component now adds 'age' field when importing monitorees

---

app/controllers/public_health_controller.rb
lib/tasks/demo.rake

Jira Ticket: SARAALERT-825
Some date fields were not properly sorting. This was caused by the fact that some values might be strings instead of dates. 
`app/controllers/public_health_controller.rb`
- Changed the query behavior for `end_of_monitoring` and `eligible purge date` to properly sort the different date values (and the other strings that can appear there). If the values are the same (i.e. the same string), they will sort with the created_at date.

'Eligible For Purge After X Date' now correctly sorts

---

app/controllers/import_controller.rb
app/lib/import_export.rb

Jira Ticket: SARAALERT-710
On import, any inputs in the Lab Test Type and Lab Results columns are now validated as enums and are validated while being cast to lower case and stripped of spaces. 
Error messages now display if improper input was supplied for the Lab Type and Results columns.
1. Create an import file with various type of input for the Lab Test Type & Result columns. Some with extra spaces, some with varying capitalization.
2. Import that file.
3. Obverse that the Lab Test Types and Results that had extra spaces and/or had some capitalized characters included did not import. 
Lab Results and Test Types are now validated as enums on import. The value the user supplies is now checked against a set list of options that are valid for each data element. …

SARAALERT-710: Import validation for lab test type and result fields

---

app/controllers/public_health_controller.rb
app/javascript/components/util/InfoTooltip.js

This PR addresses some behavior that was not the desired behavior. It does not fix a bug, merely changes the way sorting works.
Previously, monitorees that had `continuous exposure` would always be sorted to the most recent time. AKA they would show at the top/bottom if sorting by ascending/descending. The desired behavior is actually that they always show at the bottom, regardless of sorting direction.
As a result, a ternary operator is added in this PR. If the sorting is `ascending`, keep the `now()` behavior. Else use a time way in the past (so they are forced to the bottom). In this case, the epoch timestamp was chosen.
This PR also fixes a whitespace that was angering the linter.

fixes sort behavior so all continuous exposure are at the bottom

---

app/javascript/components/subject/PauseNotifications.js

Jira Ticket: [SARAALERT-851](https://tracker.codev.mitre.org/browse/SARAALERT-851)
"Resume Notifications" confirmation message needs to be updated
Click the resume notifications button and notice the language does not make sense
Click the resume notifications button and notice the language now makes sense

Bugfix: add back in resume notifications confirmation language

---

app/javascript/components/subject/LastDateExposure.js

Jira Ticket: SARAALERT-835
Allow LDE to be cleared out on patient page and turn on CE
`LastDateExposure.js`
- allow LDE to be cleared out and turn on CE

Allow LDE to be cleared out on patient page and turn on CE

---

app/javascript/components/subject/PauseNotifications.js
app/lib/roles.rb
app/views/admin/index.html.erb

This PR makes the following small updates for 1.15.0:
1. Updated Pause Notifications button tooltip text.
2. Removed "None" option from selectable roles on Admin Panel page.
`app/javascript/components/subject/PauseNotifications.js`
- Changes for update 1.
`app/lib/roles.rb`
`app/views/admin/index.html.erb`
- Changes for update 2.
Please test the following:

Small Fixes for 1.15.0

---

app/javascript/components/history/HistoryComponent.js

In the past 2 weeks, there have been several changes to the HistoryComponent page. Somehow, the git diff between these PRs was slightly messed up and certain code was not included (when it should have been). This PR re-adds this correct code. It also slightly modifies inefficient behavior.
It is possible that when `1.16` is merged into `master`, git will get upset at a similar diff occurring in both places. If such a thing happens, the following code should be included/used to resolve any merge conflicts.
```
/// ... line 145-ish in HistoryComponent.js
<Select
closeMenuOnSelect={false}
isMulti
name="Filters"
options={this.filterOptions} // <--this is where any merge-conflicts may or may not occur.
className="basic-multi-select w-25 pl-2"
classNamePrefix="select"
placeholder="Filter by …
```

History component fixes

---

.github/workflows/test.yml
README.md
docker-compose.yml

Jira Ticket: SARAALERT-889
Fixes CI failures due to changes and bug-fixes in the 8.0.22 version of MySQL being used in CI. This PR updates versions of MySQL across CI/CD to use versions compatible with v5.7 which is used in production.
Update to 8.022 of MySQL and run the test suite.
Lock versions to 5.7 or 5.7 compatible versions.

Update MySQL versions and README

---

API.md
app/controllers/fhir/r4/api_controller.rb
app/controllers/patients_controller.rb
app/models/patient.rb
test/controllers/fhir/r4/api_controller_test.rb

Jira Ticket: [SARAALERT-915](https://tracker.codev.mitre.org/browse/SARAALERT-915)
This PR does two main things:
1. Makes sure that when `monitoring` is updated to be false through the API (aka when the record is closed via the API), other necessary actions/updates occur. Specifically, `closed_at` is updated, a closed email goes out if the patient was a reporter, and a detailed history item is created.
2. Changes the `update` method to set omitted fields to `nil` as is expected for a `PUT`. We plan on supporting `PATCH` in the future. This change also fixed the bug where `monitoring` could not be set to false.
NOTE: As this is, there are obvious questions about validating which fields should be allowed to be set to `nil` if omitted. I believe the API data validation PR here should catch …

SARAALERT-915: Changes & fixes to API Update Handling 

---

app/controllers/patients_controller.rb
app/controllers/public_health_controller.rb
app/models/patient.rb
db/migrate/20201015215616_add_head_of_household_to_patient.rb
db/schema.rb
test/controllers/patients_controller_test.rb
test/factories/patient.rb
test/models/patient_test.rb

Jira Ticket: SARAALERT-930
Adds new column to `patient` table, `head_of_household` that stores a boolean. This column is updated with `around_save` and `around_destroy` callbacks on the `Patient` model where an updated patient "informs" its old/new head of household that it is a head of household.
In the case where a dependent has not been updated to trigger setting this new attribute, the query performance is improved to `COUNT` instead of loading the dependents to show the icon.
`app/model/patient.rb`
- Pay attention to the `around_save` and `around_destroy`.
I've added a test with the three cases (create, update, destroy) of manipulating heads of household.

Improve public health controller linelist load through caching

---

app/models/patient.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-919](https://tracker.codev.mitre.org/browse/SARAALERT-919)
This PR updates the definition of an "active dependent" to be more accurate. This will make sure dependents aren't receiving notifications when they should not be and that HoH aren't being kept in the system when they should be purged.
For a given monitoree whose responder is another monitoree in the system, they must meet the following criteria to be considered an active dependent:
- Not purged and not closed 
**AND**
- Any of the following:
- In isolation
- In continuous exposure
- Within monitoring period (based on LDE, if no LDE uses date of creation)
NOTE: The `active_dependents` method is used in a few other important places that should be known in order to understand the effects of this change:
- …

SARAALERT-919: Updating logic for "Active Dependents"

---

app/controllers/public_health_controller.rb

There was a bug that allowed dates to occur after `Continuous Exposure` when sorting the linelists.
The desired behavior is to always have the ContinuousExposure values at the bottom when sorting. To accomplish this, they were given the date of `now()` when sorting. This works great as long as no dates can occur in the future. However, some dates are allowed to be in the future.
~~This PR changes the behavior so that, instead of assigning a value of `now()` to the `ContinuousExposure` items, they are instead assigned a date of `now() + 31 days + 14 days`. The 14 days is the monitoring period of covid19. The 31 days is 30 + 1. The 30 is the number of day the user can select the last date of exposure into the future, and the 1 is to prevent any off-by-one errors.~~
This PR cleans up the …

refactored a bug in the filtering

---

app/mailers/patient_mailer.rb

remove unnecessary 'number' when computing history message

history typo fix

---

app/javascript/components/admin/AdminTable.js
app/views/admin/index.html.erb
app/views/analytics/index.html.erb

Now that the Analytics can be access through their own tab, it does not need a breadcrumb pointing back to the root page. Additionally, this PR makes the Admin Panel consistent with other views by adding a breadcrumb and updating the margin on the AdminTable component for alignment.
Analytics Before:
Analytics After:
Admin Before:
Admin After:
`app/views/admin/index.html.erb`
- Adding breadcrumb to Admin Panel.
`app/javascript/components/admin/AdminTable.js`
- Adding padding for alignment with breadcrumb.
`app/views/analytics/index.html.erb`
- Removing now unnecessary conditional and just always showing the same breadcrumb for analytics.
To test:

Update Breadcrumbs for Admin Panel and Analytics

---

app/controllers/fhir/r4/api_controller.rb
app/models/concerns/date_validator.rb
app/models/concerns/email_validator.rb
app/models/concerns/phone_number_validator.rb
app/models/concerns/primary_contact_validator.rb
app/models/patient.rb
test/controllers/fhir/r4/api_controller_test.rb
test/models/patient_test.rb

Jira Ticket: SARAALERT-962
This PR refactors the API validation error messages added in #455 to more closely follow the style of the validation error messages added in #413. Specifically, the error messages on the model now all only describe the error, they do not include the invalid value, or the attribute that the error is on. 
Note that this just begins to address 962, it doesn't refactor all validation. I've just broken it out so that we can maintain consistency for error messages on the model.
- Added function to add attribute and value information to error messages.
`patient.rb` and `app/models/concerns/*_validator.rb`
- Removed attribute and value information from the error messages.
`patient_test.rb`
- Fixes failing tests that were using invalid …

Refactor validation error messages

---

app/javascript/components/layout/Header.js
app/javascript/packs/stylesheets/layout.scss

Vertically aligns all items in the Header navbar. Reduces overall navbar height by doing so (adjustable if we want to add more padding). Removed some padding on the nav-links that was adding height when they were displayed so that the height of the navbar was consistent between login and home page. Also removes a redundant check that was leftover in the component.

Aligning navbar items.

---

.github/workflows/static.yml
Gemfile
Gemfile.lock
config/locales/devise.en.yml
config/locales/devise.security_extension.en.yml
config/locales/en.yml
config/locales/fr.yml
lib/tasks/spellcheck.rake

Jira Ticket: SARAALERT-913
This PR is for spelling fixes found by Hunspell checking. 
Creates a new rake task that will run spell checking on locales and add in a static GitHub actions test that runs the task. 
The rake task runs spellchecking on all locales (en_US, es_PR, fr_FR) except so.yml because I did not find a dictionary for it. If we do find one then it would be easy to add it in. The GitHub action runs under the static analysis group. If one or more spelling errors are detected then the test will fail itself. To ease correction of issues the script will also produce descriptive output of where the error was found in the YAML hierarchy (see example snippet below).
```
...
CHECKING LOCALE: config/locales/es-PR.yml with dictionary es_PR
es-PR => assessments => symptoms => pulse-ox …
```

Saraalert 913 Hunspell

---

app/controllers/fhir/r4/api_controller.rb
app/helpers/patient_helper.rb
app/helpers/validation_helper.rb
app/models/oauth_application.rb
app/models/patient.rb
test/controllers/fhir/r4/api_controller_test.rb

Jira Ticket: SARAALERT-689
This adds support for the field 'Full Assigned Jurisdiction Path' to the API. There is a corresponding PR in the FHIR IG repo: https://github.com/SaraAlert/saraalert-fhir-ig/pull/4. Also note that this is not the completion of SARAALERT-689. The task includes many more fields, but this one is going in first, because it's a priority for 1.16.0.
- Added a step to validate the requested jurisdiction on `update` and `create`, validation based on the client application's jurisdiction.
- Remove previous code that sets the patient's jurisdiction to the resource creator's jurisdiction
`patient.rb`
- Mapping to and from FHIR
`patient_helper.rb`
- Helpers for the FHIR mapping. Note the generic string extension mappers will be reused when I add more …

Add support for Full Assigned Jurisdiction Path to API

---

app/controllers/admin_controller.rb
db/migrate/20201028204903_add_is_api_proxy_to_users.rb
db/schema.rb
lib/tasks/admin.rake
test/controllers/admin_controller_test.rb
test/fixtures/users.yml
test/system/roles/admin/admin_test_helper.rb

Jira Ticket: [SARAALERT-958](https://tracker.codev.mitre.org/browse/SARAALERT-958)
"API proxy users" are user accounts specifically created for OAuth Apps using the API and the backend services workflow so that changes can be made under a specific email/associated user account. They cannot (and should not) be logged into by real people (already handled as they are locked upon creation without a password reset), nor should they be displayed on the Admin Panel or exported (handled in this PR). 
This PR does the following to achieve the above:
- Adds a new column to the User table called `is_api_proxy` that tracks whether the user is an API proxy user or not. This migration includes an update to all existing API proxy users.
- Updates the …

SARAALERT-958: Handle API Proxy Users

---

app/javascript/components/patient/Patient.js

Remove stray $ in monitoree details

Monitoree details bugfix

---

Gemfile
Gemfile.lock
app/jobs/consume_assessments_job.rb
app/jobs/produce_assessment_job.rb
docker-compose.prod.yml
docker-compose.yml
lib/tasks/reports.rake
test/jobs/consume_assessments_job_test.rb

Jira Ticket: SARAALERT-1007
Migrate from PUB/SUB approach to RPOPLPUSH for bridge. Parallelize consume job to increase throughput.
`Gemfile` & `Gemfile.lock`
- Added redis-queue gem
`app/jobs/consume_assessments_job.rb`
- Use queue
- More logging statements for invalid stuff
`app/jobs/produce_assessment_job.rb`
- Use queue
`lib/tasks/reports.rake`
- Fork `CONSUME_WORKERS` ConsumeAssessmentsJobs

SARAALERT-1007: Utilize RPOPLPUSH for split arch bridge with a queue; Parallelize report processing

---

app/javascript/data/supportedLanguages.json

Jira Ticket: [SARAALERT-896](https://tracker.codev.mitre.org/browse/SARAALERT-896)
Primary and secondary language options include now include Amharic and Farsi/Persian
`supportedLanguages.json`
- Added Ahmaric and Farsi to supportedLanguages json file

SARAALERT-896: add Amharic and Farsi to supported languages

---

app/controllers/patients_controller.rb

Jira Ticket: SARAALERT-947
The system does not log when a user is added or removed from a household or when the Head of Household is changed.
There are 3 items we need to test and we will need a household with at least 3 people in it. 
1) Create your own household by adding monitorees to a household. Verify the messages in the history show that the user was added to a household.
2) With your household of [A<HoH>, B, C, ...] change the HoH from A to B. Verify that A and B both have a message in the history stating that the HoH was changed. Verify that [C, ...] do not have a message.
3) Choose a member of the household and remove them from that household. Verify the message in the history that the …

SARAALERT-947: Add history to Household changes

---

API.md

Jira Ticket: SARAALERT-689
Updates the patient snippets in our examples in API.md to include Full Assigned Jurisdiction Path.
`API.md`
- Updated the snippets
Just look at [API.md on my branch](https://github.com/SaraAlert/SaraAlert/blob/689-jurisdiction-path-examples/API.md) and confirm it looks right.

Add jurisdiction path examples in API.md

---

app/controllers/patients_controller.rb

Jira Ticket: [SARAALERT-1041](https://tracker.codev.mitre.org/browse/SARAALERT-1041)
The UI was switched to be FirstName LastName instead of LastName, FirstName. This updates the history messages for the HoH to match.
There are 3 items we need to test and we will need a household with at least 3 people in it. 
1) Create your own household by adding monitorees to a household. Verify the messages in the history show that the user was added to a household.
2) With your household of [A<HoH>, B, C, ...] change the HoH from A to B. Verify that A and B both have a message in the history stating that the HoH was changed. Verify that [C, ...] do not have a message.
3) Choose a member of the household and …

SARAALERT-1041: Update HoH Messages

---

app/javascript/components/layout/CustomTable.js

Jira Ticket: SARAALERT-961
Fixes a bug related to not resetting the page when sorting. This affected both the `AdminTable` and `PatientsTable`.
1. Go to a page other than page 1 of a line list or admin table.
2. Sort column
3. Notice that the data is for page 1 after sorting but the page number did not update
Reset the page in the query passed to the table update callback in CustomTable whenever sorting occurs.

SARAALERT-961: Bugfix for sorting not resetting page count on tables

---

app/controllers/import_controller.rb
test/system/roles/public_health/dashboard/import_verifier.rb
test/system/roles/public_health/public_health_import_export_test.rb

Until we get more confirmation from our jurisdictions, we want to avoid deploying anymore import validation. This PR comments out the case status validation introduced in [this PR.](https://github.com/SaraAlert/SaraAlert/pull/485) There doesn't appear to be anything broken/wrong, but this is a safety precaution to make sure we don't disrupt workflows right before Thanksgiving break.
@hackrm Let me know if anything else needs to be updated to temporarily remove those changes.
To be clear, this reverts to previous functionality which was that case status was NOT imported at all in the Exposure workflow, and in the isolation workflow it checks that it is ANY of the possible strings.

Case Status Validation Temporary Removal

---

README.md
app/jobs/send_patient_digest_job.rb
app/jobs/send_purge_warnings_job.rb
app/mailers/user_mailer.rb
app/models/patient.rb
app/views/user_mailer/send_patient_digest_job_email.html.erb
config/schedule.rb
db/migrate/20201116214553_add_send_digest_to_jurisdictions.rb
db/schema.rb
lib/tasks/admin.rake
lib/tasks/mailers.rake

Jira Ticket: SARAALERT-1001
Creates an hourly email digest containing links to all patients reported as symptomatic in the last hour, delivered to superusers, public health users, and public health enrollers. The email is opt-in by jurisdiction: there is a nullable boolean field for the jurisdiction model called "send_digest", which defaults to false and determines whether the digest is sent. 
app/jobs/send_patient_digest_job.rb - new file containing the logic for the job. 
app/mailers/user_mailer.rb - has the logic to send the email
app/views/user_mailer/send_patient_digest_job_email.html.erb - format of the email. 
To verify the email job, run the command: bundle exec rake …

1001 patient digest

---

app/controllers/fhir/r4/api_controller.rb
test/controllers/fhir/r4/api_controller_test.rb

Jira Ticket: [SARAALERT-938](https://tracker.codev.mitre.org/browse/SARAALERT-938)
This PR adds error handling for when the body of a POST or PUT is invalid JSON. Previously a 500 was returned, with no indication of what was wrong. Now a 400 is returned, with an error message indicating that parsing JSON failed.
- Added rescue blocks to the end of the `update` and `create` methods to catch JSON parse errors specifically, and return a 400 status with an informative error message.
To test try making a POST and PUT request to the API with invalid JSON. You can test both workflows, but I can't see how the different flows would make a difference here. 
This PR should likely go in after https://github.com/SaraAlert/SaraAlert/pull/522, since #522 adds a PATCH endpoint. I've …

SARAALERT-938: Check JSON validity in api endpoints

---

app/jobs/consume_assessments_job.rb
test/jobs/consume_assessments_job_test.rb
test/test_helpers/consume_assessments_job_test_helper.rb

The message sent to ConsumeAssmentsJob, can be sent from the web form with a list of specific reported symptoms (the `reported_symptoms_array`) or in the case of an assessment completed via SMS or Voice will have a `experiencing_symptoms` parameter because the SMS and Voice options do not collect individual symptom information. The reported_symptoms_array and experiencing_symptoms parameters are mutually exclusive in the message sent to the ConsumeAssessmentsJob. The troublesome line of code that was changed `assessment.symptomatic = assessment.symptomatic? || message['experiencing_symptoms']` was changed because `message['experiencing_symptoms']` will be `nil` when that particular line is hit which means that symptomatic will result to `nil` if `assessment.symptomatic?` is false. THIS is …

Remove logic for nil experiencing_symptoms parameter

---

test/factories/symptom.rb

Fixes a small issue in the `Symptom` factory generating an ID above max integer.
Can be seen in [this test run](https://github.com/SaraAlert/SaraAlert/runs/1444866354?check_suite_focus=true)

Update integer for condition_id to not be above max int

---

app/controllers/public_health_controller.rb
app/javascript/components/public_health/AdvancedFilter.js
app/jobs/consume_assessments_job.rb

Jira Ticket: [SARAALERT-1003](SARAALERT-1003)
Add a relative date option to advanced filters.  Example case: users want to see all monitorees with Symptom Onset Date in the past X days
- Added new type `relative` for relative dates that supports filtering by today, tomorrow, yesterday and custom options that include in the `past/next` `number` `days/weeks/months`
- Added a second date advanced filter (in addition to the hardcoded dates) to the following fields: LDE, enrolled, symptom onset and latest report
`public_health_controller.rb`
- Necessary backend changes for supporting all relative date options
This fix was …

SARAALERT-1003: add advanced filter by relative date

---

app/javascript/components/public_health/AdvancedFilter.js

Jira Ticket: [SARAALERT-1003](https://tracker.codev.mitre.org/browse/SARAALERT-1003)
Select one of the relative date options in the advance filter and hit apply without changing anything, the today filter will not work
Adding missing line to set the relativeOption at the beginning

Relative date advanced filter bugfix

---

API.md
Gemfile
Gemfile.lock
app/controllers/fhir/r4/api_controller.rb
config/routes.rb
test/controllers/fhir/r4/api_controller_test.rb

Jira Ticket: [SARAALERT-940](https://tracker.codev.mitre.org/browse/SARAALERT-940)
This adds support for PATCH in the API. The body of the PATCH request should follow the [JSON Patch](https://tools.ietf.org/html/rfc6902) specification.
- Add support for processing PATCH requests on a Patient. A PATCH proceeds by getting the existing resource, converting it to FHIR, and then applying the patch to get updated FHIR. That updated FHIR then follows the same flow as when an updated FHIR Patient is directly specified in a PUT.
`routes.rb`
- Adds a PATCH endpoint for Patient that routes to `update`.
`API.md`
- Documentation on PATCH
Test sending PATCH updates to existing Patient resources. Here is an example PATCH:
```
[
{ "op": "remove", "path": "/communication" },
{ "op": …
```

SARAALERT-940: Support Patch in API

---

app/views/user_mailer/download_email.html.erb
test/system/lib/system_test_utils.rb
test/system/roles/enroller/enroller_enrollment_test.rb

- When running all tests at once `bundle exec rails test test/system`, then rails would complain that the `EnrollerTest` had duplicate test names. This was because `enroller_enrollment_test.rb` and `enroller_dashboard_test.rb` had the same class name and the same test names. I changed the class name of `enroller_enrollment_test.rb` to `EnrollerEnrollmentTest` to fix this. It REALLY seems like these two test classes contain some of the same exact tests - as in I think we could just delete `enroller_enrollment_test.rb`.
- I noticed a test failing because it would not wait enough time after enrollment, so I increased `ENROLLMENT_SUBMISSION_DELAY` by one second

Activestorage test fix

---

Gemfile
Gemfile.lock

Jira Ticket: [SARAALERT-940](https://tracker.codev.mitre.org/browse/SARAALERT-940)
This PR updates the `Gemfile` to point to version `1.3.7` of the `hana` gem. We had been pointing to our fork of the gem, but the changes we made got merged and released into `1.3.7`, so we no longer need to point at our local fork.
`Gemfile`
- Require `1.3.7` or higher for `hana`.
You can do a quick test to ensure the code we added is in version `1.3.7` by testing out a JSON Patch that triggers some of the error handling we added. One example would be doing a `replace` on a field that doesn't exist:
```
[
{ "op": "replace", "path": "/foo", "value": "1" }
]
```
In previous versions of `hana`, this would not cause any errors, but in version `1.3.7`, you should see an error like 
```
"Unable to apply patch: …
```

Update hana to 1.3.7

---

app/controllers/import_controller.rb
test/system/roles/public_health/dashboard/import_verifier.rb

Jira Ticket: [SARAALERT-983](https://tracker.codev.mitre.org/browse/SARAALERT-983)
The validation error for 'Sex' on import does not give the acceptable values.
Import data with 'Sex' as 'Puppy'. The validation error should specify the acceptable values. The attached Excel file can be used for the import
[SARAALERT-983.xlsx](https://github.com/SaraAlert/SaraAlert/files/5637912/SARAALERT-983.xlsx)

SARAALERT-983: Update Error Message

---

app/helpers/fhir_helper.rb
test/controllers/fhir/r4/api_controller_test.rb

Jira Ticket: [SARAALERT-1051](https://tracker.codev.mitre.org/browse/SARAALERT-1051)
This adds support for reading and writing the State/Local ID in the API. See the Jira ticket for full context if interested, but we decided to implement this in FHIR as a `Patient.identifier`, with an `Identifier.system` that we define (`http://saraalert.org/SaraAlert/state-local-id`). There is no validation. A corresponding PR for the IG will be coming soon, but should not block this review. Also, I will update the docs for this when we have a final decision for how we're tracking our Wiki pages.
`fhir_helper.rb`
- Simple mapping between the Sara Alert …

1051: Add support for State/Local ID in the API

---

app/jobs/consume_assessments_job.rb
app/mailers/patient_mailer.rb
test/mailers/patient_mailer_test.rb

If there are multiple responders (id==responder_id) that have the same primary telephone, then ALL of those responders (and their dependents) should get history items indicating that the relevant primary_telephone had replied with STOP (or START).
Create 2 responders with the same phone number, send a STOP message and copy the flow execution ID (retrievable from the studio flow logs) into an opt_out (or opt_in) POST to your report/twilio endpoint with a body such as `{"response_status": "opt_out", 
"patient_submission_token": "FN0a152d1994de69ed7f8d91639bc78e22"}`. You'll notice only the FIRST monitoree with the primary_telephone referenced in the flow execution had history items indicating the number blocking (or …

Duplicate responders blocked

---

app/javascript/components/public_health/PublicHealthHeader.js
app/lib/import_export.rb
public/Sara Alert Import Format.xlsx
test/system/roles/public_health/dashboard/export_verifier.rb

Jira Ticket: [SARAALERT-765](https://tracker.codev.mitre.org/browse/SARAALERT-765)
This ticket updates the Import Format Guidance. 
Updated the Import Modal to include the last updated date
1. Verify that `Sara Alert Import Format.xlsx` has an Updates Tab and that in the Formatting Guidance Rows 4 and 5 are gray and yellow.
2. Verify that selecting `Import` brings up a modal that has the last updated date as shown above.

SARAALERT-765: Update Import Template

---

app/javascript/components/enrollment/steps/Exposure.js
app/javascript/components/patient/Patient.js
app/javascript/tests/patient/Patient.test.js

Jira Ticket: SARAALERT-696
- Hide edit button for `Potential Exposure Info` section when in isolation workflow
- Fixed spacing for risk factors list in enrollment

Monitoree details updates

---

app/controllers/fhir/r4/api_controller.rb
test/controllers/fhir/r4/api_controller_test.rb

Jira Ticket: [SARAALERT-943](https://tracker.codev.mitre.org/browse/SARAALERT-943)
Most tests in the `api_controller_test.rb` file were duplicated, once for the `USER` workflow, and once for the `SYSTEM` (machine to machine) workflow. In most cases, this duplication wasn't really necessary, because the test was not testing any workflow specific logic. This PR removes the `USER` workflow version of tests that were duplicated unnecessarily.
`api_controller_test.rb`
- Removed duplicate `USER FLOW` tests.
- Re-organized tests to be grouped by function. Now if there is a function that requires both `USER` and `SYSTEM` tests, those tests are alongside each other, not split into two sections.
- Add a few small tests for some lines that were not being covered before.
The diff is not an easy read, …

SARAALERT-943: Remove duplication in API controller tests

---

app/javascript/components/patient/Patient.js
app/javascript/tests/patient/Patient.test.js

Jira Ticket: [SARAALERT-696](https://tracker.codev.mitre.org/browse/SARAALERT-696)
Added edit button for notes section in monitoree details.  when clicked it should open the edit case info page (if in isolation) or the edit exposure info page (if in exposure)

added edit button for notes section

---

app/controllers/public_health_controller.rb
app/javascript/components/public_health/AdvancedFilter.js
app/javascript/components/public_health/actions/CloseRecords.js
app/javascript/components/subject/LastDateExposure.js
app/javascript/components/subject/monitoring_actions/MonitoringStatus.js
app/javascript/components/util/InfoTooltip.js
app/javascript/tests/subject/monitoring_actions/MonitoringStatus.test.js
app/models/patient.rb
app/views/patients/show.html.erb
lib/tasks/demo.rake
test/controllers/public_health_controller_test.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-1052](SARAALERT-1052)
This PR adds support in the Advanced Filter for finding records that meet the new CDC quarantine criteria outlined here: 
https://www.cdc.gov/coronavirus/2019-ncov/more/scientific-brief-options-to-reduce-quarantine.html
It adds the following:
- New 10-day quarantine advanced filter following criteria specified in scope comment
- New 7-day quarantine advanced filter following criteria specified in scope comment
- New reason for closure (monitoring reason)
- Updated end of monitoring tooltip text
`app/controllers/public_health_controller.rb`
- New advanced filter option support added
`app/javascript/components/public_health/AdvancedFilter.js`
- New advanced filter option support added
- Slight update to tooltip rendering functions …

SARAALERT-1052: Support for new CDC Quarantine Guidance in Advanced Filter

---

app/javascript/components/enrollment/steps/Contact.js

Jira Ticket: [SARAALERT-1075](https://tracker.codev.mitre.org/browse/SARAALERT-1075)
If you enroll a new monitoree with a preferred contact method of Unknown, it shows up as null in the monitoree details and when you use the advanced filter on preferred contact method.
Steps to recreate [here](https://teams.microsoft.com/l/file/1C336B99-88E0-4AC8-AE31-33BA1D20EF2E?tenantId=c620dc48-1d50-4952-8b39-df4d54d74d82&fileType=pptx&objectUrl=https%3A%2F%2Fmitre.sharepoint.com%2Fsites%2FCoVDT%2FShared%20Documents%2FGeneral%2FProduct%20Owner%20Materials%2FTesting%2FBug%20Reports%2Fpreferred%20reporting%20field%20bug.pptx&baseUrl=https%3A%2F%2Fmitre.sharepoint.com%2Fsites%2FCoVDT&serviceName=teams&threadId=19:00d3d45c64ca457795d58c2764d517cd@thread.skype&groupId=7de0f318-3170-4f1c-82eb-95bfe132bfe9) …

SARAALERT-1075: added null option to preferred contact method dropdown

---

app/controllers/assessments_controller.rb
app/jobs/consume_assessments_job.rb

Move reported_condition and assessment saving into a transaction that explicitly saves the reported_condition and assessment, ensuring that both will not be saved if there were errors saving either.

Assessment transaction

---

app/models/patient.rb

The `patient_diff` function is used both by the `patient_controller` and by the `api_controller` and at the moment, they pass the updated attributes differently (as strings or symbols). This functionality will be updated in a future PR that I have been working on for consolidating update logic, but for now this supports both and fixes the issue.
- Changed Assigned Jurisdiction of existing record in Enrollment/Edit Wizard
- Notice the Record Edit history item uses jurisdiction IDs instead of paths
1. Edit Assigned Jurisdiction in Enrollment/Edit Wizard and make sure the Record Edit history item has the full jurisdiction paths.
2. Quickly use Postman to test the API and make a PUT with a jurisdiction change and make sure that History item also shows up correctly.

Bugfix: History comment when changing Assigned Jurisdiction in Enrollment/Edit Wizard

---

app/javascript/components/analytics/PublicHealthAnalytics.js
app/javascript/components/analytics/widgets/CustomizedAxisTick.js
app/javascript/components/analytics/widgets/Demographics.js
app/javascript/components/analytics/widgets/ExposureSummary.js
app/javascript/components/analytics/widgets/MonitoreeFlow.js
app/javascript/components/analytics/widgets/MonitoreesByEventDate.js
app/javascript/components/analytics/widgets/PreferredReportingMethod.js
app/javascript/components/util/InfoTooltip.js
app/javascript/packs/stylesheets/analytics.scss
app/jobs/cache_analytics_job.rb
test/system/roles/analyst/dashboard/monitoree_counts_verifier.rb

Jira Ticket: SARAALERT-951
This is a followup commit to address some feedback received from the Analytics Overhaul page.
In summary this PR:
1. Fixes a SQL query bug that was selecting incorrect values for the Monitorees by Event Date component
2. Clears up confusion about whether Analytics Data was coming from All Records or Active Records
3. Clears up confusion about any discrepancies in the Analytics data and the linelists (explains the cached nature of the analytics in the UI).
4. Fixes a bug where two labels had been accidentally swapped

Analytics tweaks

---

app/models/assessment.rb
app/views/patients/show.html.erb

Speedups for Patient show page, specifically for the Reports table.
- We were calling `get_reported_symptom_by_name` a ton and get a huge speedup by just storing that in a variable. We were doing that query like 5 times per assessment.
- We were populating the columns using a lot of expensive operations. This change gets us a speedup from ~2.379 s -> ~0.022 seconds for a record with 500 assessments.

Speeding up show.html.erb.

---

app/javascript/components/close_contact/CloseContact.js

Fix close contact phone numbers
Create close contact with phone number and notice how phone number is not shown after save
Phone number needs to be converted to E164 before being saved in the database in order to be shown properly

fix close contact phone numbers

---

app/javascript/components/enrollment/Enrollment.js

Jira Tickets:
[SARAALERT-1075](https://tracker.codev.mitre.org/browse/SARAALERT-1075): When enrolling, the default `preferred_contact_method` of `Unknown` is not stored and is set as null when you finish enrollment.
[SARAALERT-1119](https://tracker.codev.mitre.org/browse/SARAALERT-1119): When enrolling a close contact, all the fields ('first_name', 'last_name', 'primary_telephone', 'email', 'contact_of_known_case', 'contact_of_known_case_id', 'exposure_notes') all are not set when submit.
Enroll a close contact, only fill out the required fields and don't touch the preferred contact method dropdown.  Once you submit, you'll see none of these fields were saved.
Please list important files (meaning substantial or integral to the PR) along with a list of the general changes that should be …

SARAALERT-1075 & SARAALERT-1119: Bugs where info is not saved upon enrollment

---

app/controllers/patients_controller.rb

Jira Ticket: [SARAALERT-1119](https://tracker.codev.mitre.org/browse/SARAALERT-1131)
Duplicate detection was unknowingly not working when the `allowed_params` method was changed.
Try and enroll a duplicate and notice it is not detected. Duplicates are either:
- matching first name, last name, sex, and DoB
OR
- matching state/local id
Fixing use of `allowed_params` method since it has been updated to already permit the params.

(Bugfix) Bug with allowed_params was preventing dup detection.

---

Gemfile
Gemfile.lock
app/controllers/assessments_controller.rb
app/helpers/assessment_query_helper.rb
app/javascript/components/admin/AdminTable.js
app/javascript/components/admin/AuditModal.js
app/javascript/components/assessment/Assessment.js
app/javascript/components/layout/CustomTable.js
app/javascript/components/patient/PatientReportsTable.js
app/javascript/components/patient/ReportModal.js
app/javascript/components/public_health/PatientsTable.js
app/javascript/packs/stylesheets/bootstrap.scss
app/models/assessment.rb
app/views/patients/show.html.erb
config/routes.rb
test/system/roles/public_health/patient_page/reports.rb

Jira Ticket: [SARAALERT-1111](https://tracker.codev.mitre.org/browse/SARAALERT-1111)
This PR refactors the Patient reports/assessments table from a DataTable to a React component. The purpose for this change is so that we can finally paginate the assessments and gain a huge performance increase as jurisdictions such as GLITC are having trouble loading the Patient page due to many assessments. 
Visual changes:
- Actions button is now the leftmost column for easier access and is in a consistent style with the rest of the application.
- Input for entries per page is now below the table and looks more consistent with other tables in the application.
- Search bar is updated. 
Functional changes:
- Search bar only allows searching by ID or reporter. Before it was sort of a catch all for any …

SARAALERT-1111: Refactor Reports Table into React Component

---

app/helpers/assessment_query_helper.rb
app/javascript/components/patient/Patient.js
app/javascript/tests/patient/Patient.test.js
app/jobs/consume_assessments_job.rb
app/lib/import_export.rb
app/mailers/twilio_sender.rb
app/models/assessment.rb

We are seeing a few failures on prod after 1.18.0 that seem to stem from unexpected prod data and needed nil checks. 
1. For some reason, the fetch for phone number when getting an opt-in/opt-out message appears to be failing/have unexpected data on prod. This requires further investigation, but for now, it needs to be caught to avoid causing an error in ConsumeAssessments.
2. Nil check needed on export when extracting assessment details. Looks like something related to a nil condition (still investigating).
Please test these changes locally and on demo and verify that exporting assessments still works as expected, and that the consume assessments job runs and can handle an error in the Twilio Sender helper method as expected.

(Bugfixes) 1.18.0 Fixes

---

app/controllers/patients_controller.rb

After 1.19.0, we are seeing users hit an error when trying to access `laboratories` on a nil `Patient`. This happens if they try to navigate to a Patient record they do not have access to, so it's not a big issue. Previously, they would just be redirected to the home page (which is also something we already have a ticket to improve actually: [SARAALERT-876](https://tracker.codev.mitre.org/browse/SARAALERT-876)).
Here's the related Sentry error:
This PR just properly grabs the `@laboratories` and `@close_contacts` _after_ the check for a nil record and redirect.
Try and navigate to a record that you don't have access to (make sure you're not logged in as a USA level user) (maybe a dependent in a household that is out of your jurisdiction).
Make sure to check for nil patient before anything …

(Bugfix) Moving queries until after check for nil Patient.

---

app/javascript/components/patient/PatientReportsTable.js
app/models/assessment.rb

As of 1.19.0 with the Patient Reports Table refactor, we have been seeing a small number of occurrences of the following error:
The `symptoms` returned in `response.data.symptoms` should never be null/undefined as we get them [here](https://github.com/SaraAlert/SaraAlert/blob/master/app/helpers/assessment_query_helper.rb#L73) and send an empty array if somehow nil [here](https://github.com/SaraAlert/SaraAlert/blob/master/app/helpers/assessment_query_helper.rb#L101).
At the moment we believe this error may be occurring when there is an interruption in the request. We specifically investigated the patients we saw this error occur on and found the method returned a number of symptoms properly.
This PR adds correct checks to avoid the error in this case, and also adds a nil check to the …

(Bugfix/Error Handling) Additional checks before updating Reports table

---

app/controllers/export_controller.rb
app/helpers/patient_query_helper.rb
app/jobs/export_job.rb
app/lib/import_export.rb

We are seeing significant memory issues with custom exports, and have had to temporarily scale up our production resources in the interim. The main issue seems to be the lack of batching when getting all the export data to write to files, as we did previously. This PR adds that additional batching functionality back and makes a few other optimizations.

(Bugfix) More Batching in Exports to reduce Memory Usage

---

app/models/patient.rb
test/models/patient_test.rb

Jira Ticket: Aims to help address (in the short term): [SARAALERT-1151](https://tracker.codev.mitre.org/browse/SARAALERT-1151)
The SendAssessmentsJob is currently taking too long during peak sending time of the day and it's causing duplicate assessments to be sent as it overlaps with the same job at the next hour. This PR aims to make small and low-risk updates to the `reminder_eligible` scope that will reduce the number of records iterated over for the job run. 
There is an existing PR ( https://github.com/SaraAlert/SaraAlert/pull/518) that is the more longterm solution for this and has further updates to this logic. Given that needs more time for testing, this is a short term solution.
- Updated `reminder_eligible` to account for `preferred_contact_method` and …

SARAALERT-1151: Small Assessment Sending Optimizations

---

app/javascript/components/subject/ClearReports.js
app/javascript/tests/subject/ClearReports.test.js

Jira Ticket: [SARAALERT-1089](https://tracker.codev.mitre.org/browse/SARAALERT-1089)
See JIRA for suggested bold text in `Mark All As Reviewed` reports modal
`ClearReports.js`
- Added specified bold text
- Swapped to inline binding
`ClearReports.test.js`
- Added full test suite for this component

SARAALERT-1089: Bold "unless" language in the Review Symptom Report pop up

---

app/javascript/components/analytics/widgets/CountyLevelMaps.js

Jira Ticket: SARAALERT-1056
Changes the county level maps settings to be resizable to DC is visible. The original code changes are not mine: David had a fix ready when I was assigned the task, and I've used his solution here. 
Screenshots pending
-  app/javascript/components/analytics/widgets/CountyLevelMaps.js - The only file changed, makes the user able to resize, drag, and wheel the map chart. 

County level maps zoom functionality

---

app/controllers/assessments_controller.rb
test/controllers/assessments_controller_test.rb

Jira Ticket: SARAALERT-1101
Write assessment controller tests & track float/integer/bool symptoms in history properly
- checkout master
- change a symptom in a test or on local server
- verify that the created history message does NOT contain a `Symptom updates: _____` sentence.
The original state of the change tracking was not properly saving boolean symptoms and not attempting to track float or integer symptoms. This PR addresses both issues.
`app/controllers/assessments_controller.rb`
- bug fix for patient find using an old key
- fix bug with history tracking on boolean symptom update
- add history tracking for updates on float and integer symptoms
`test/controllers/assessments_controller_test.rb`
- New test file …

SA-1101 Assessment update history message fixes

---

app/helpers/patient_query_helper.rb
app/models/jurisdiction.rb
test/models/jurisdiction_test.rb

Jira Ticket: [SARAALERT-1153](https://tracker.codev.mitre.org/browse/SARAALERT-1153)
This PR updates what patients can be shown in the transferred in/out linelists with the following changes:
- Closed records should show up on both linelists.
- Purged records should NOT show up on either of the transfer linelists.
It also adds tests for these methods on the Jurisdiction model.
`app/helpers/patient_query_helper.rb`
- Allow closed records to show up on these linelists.
`app/models/jurisdiction.rb`
- Don't allow purged records to show up on these linelists.
`test/models/jurisdiction_test.rb`
- Added tests for the `transferred_out_patients` and `transferred_in_patients` methods.
Please describe the …

SARAALERT-1153: Update Transfer Linelist Logic

---

app/javascript/components/public_health/CustomExport.js
test/system/roles/public_health/dashboard/dashboard.rb
test/system/roles/public_health/public_health_custom_export_test.rb

Jira Ticket: [SARAALERT-1148](https://tracker.codev.mitre.org/browse/SARAALERT-1148)
We have found that the CSV custom exports are getting too large on prod as they are not compressed as Excel files are. As a result, we are temporarily removing the option for CSV custom exports until we have migrated exports to AWS S3.
Before change:
After change:
`app/javascript/components/public_health/CustomExport.js`
- Removed CSV/Excel button option.
- Added note at the top to state what the file format will be.

SARAALERT-1148: Temporarily Remove Custom Export CSV Option

---

app/controllers/tokens_controller.rb
config/routes.rb

Jira Ticket: [SARAALERT-1038](https://tracker.codev.mitre.org/browse/SARAALERT-1038)
This adds additional logging to the API, so that when investigating issues we may have an easier time figuring out what is going wrong for an API user.
`tokens_controller.rb`
- This file contains a definition of a new `TokensController` class which inherits from `Doorkeeper::TokensController`, and adds some additional logging. This is the only change, so that in all other ways the class will works as defined originally by the Doorkeeper gem. When the response is 4xx or 5xx, we now log the body of the response, to hopefully help with debugging.
I looked into adding more logging to the `APIController`, but I wasn't sure it made a ton of sense. In many of the cases, the status code is descriptive enough (aka …

SARAALERT-1038: Improve API Logging

---

app/helpers/fhir_helper.rb
test/controllers/fhir/r4/api_controller_test.rb

When updating a patient with the FHIR api, only the first race matching race was being set to true
The selector was changed to match any instead of only the first.  The update test checks this condition, and if any additional tests should be updated let me know.

Bugfix for updating multiple races with FHIR

---

app/javascript/components/layout/Header.js
config/routes.rb

Jira Ticket: SARAALERT-1146
Exposes the Sidekiq UI interface for USA admins only.
Allows USA admins to reach `/sidekiq`, and USA admins have a helper link in the app header to get to this endpoint.

SARAALERT-1146: Expose Sidekiq UI

---

app/javascript/components/public_health/ConfirmExport.js
app/javascript/components/public_health/CustomExport.js
app/javascript/components/public_health/Export.js
app/javascript/tests/mocks/mockExportPresets.js
app/javascript/tests/mocks/mockJurisdiction.js
app/javascript/tests/mocks/mockQueries.js
app/javascript/tests/mocks/mockTabs.js
app/javascript/tests/public_health/ConfirmExport.test.js
app/javascript/tests/public_health/Export.test.js
app/javascript/tests/subject/monitoring_actions/Jurisdiction.test.js
app/javascript/tests/subject/monitoring_actions/MonitoringActions.test.js

Jira Ticket: [SARAALERT-1118](https://tracker.codev.mitre.org/browse/SARAALERT-1118)
When exporting a file, the user is able to click the "Start Export" button multiple times after clicking it once and before the modal closes. Because of the export limitation that we have this doesn't actually cause multiple exports, but it will result in a red message popping up for each extra click telling the user they can't export more. See attached screenshot for the button being referred to.
`ConfirmExport.js`
- Added loading state variable to disable the `StartExport` button when clicked
`ConfirmExport.test.js`
- Added test suite for this …

SARAALERT-1118: Should not be able to click "Export" button multiple times

---

app/mailers/twilio_sender.rb

Jira Ticket: SARAALERT-1143
This fixes an issue with the TO and FROM phone numbers to be pulled from REST Triggered Studio Flow executions **and** from executions that were triggered via an incoming message.
In the rails console:
```
@client = Twilio::REST::Client.new(ENV['TWILLIO_API_ACCOUNT'], ENV['TWILLIO_API_KEY'])
execution = @client.studio.v1.flows(ENV['TWILLIO_STUDIO_FLOW']).executions(<opt out execution ID triggered via Twilio REST Trigger>).execution_context.fetch
trigger_message = execution&.context&.[]('trigger')&.[]('message')
execution = @client.studio.v1.flows(ENV['TWILLIO_STUDIO_FLOW']).executions(<opt out execution ID triggered via Incoming message>).execution_context.fetch
trigger_message = execution&.context&.[]('trigger')&.[]('message')
```
In the rails console:
``` …
```

Get number from existing execution

---

app/javascript/components/subject/ClearSingleReport.js
app/javascript/tests/subject/ClearSingleReport.test.js

Jira Ticket: [SARAALERT-1089](https://tracker.codev.mitre.org/browse/SARAALERT-1089)
Added bolded language to review singular report modal.
`ClearSingleReport.js`
- Updated bolded language
- In line function binding
`ClearSingleReport.test.js`
- Added test suite for singular clear reports modal

SARAALERT-1089 (continued): Bold "unless" language in the Review Symptom Report pop up

---

app/mailers/patient_mailer.rb
app/models/patient.rb
test/mailers/patient_mailer_test.rb
test/models/patient_test.rb

Jira Ticket: SARAALERT-1183
If SendAssessmentJob runs become unwieldy (taking longer than the normal 1 hour), the potential for overlap in eligibility can result in multiple emails (etc.) being sent during the same period. This adds a specific check before anything is sent in the send_assessments method to ensure if this situation arises, multiple messages will not be sent.
`app/mailers/patient_mailer.rb`
- Do update of last_assessment_reminder_sent upfront (before external call is done to Twilio/SMTP)
- If message failed to send for whatever reason, nil out last_assessment_reminder_sent
- Check last_assessment_reminder_sent in case a …

SARAALERT-1183: Handle potential overlap in report mailer scheduling

---

docs/api/api-specification.md

Add documentation of Content-Type for PATCH endpoint since it's different from the other endpoints. There's no Jira ticket for this since it's small, and it just came out of Deloitte/PA's confusion testing testing on demo.

Add documentation of Content-Type for PATCH endpoint

---

docs/api/api-coming-soon.md
docs/api/api-release-notes.md

This PR contains some minor updates to the "Release Notes" and "Coming Soon" pages so that the API docs are ready to deploy once 1.20.0 is out.
- Add release notes for 1.20.0. Note that 1.19.0 is skipped, since nothing user facing was added to the API during that release).
- Change the coming soon version to 1.21.0. As I understand we don't have anything user facing strictly planned for 1.21.0, but I can update this if that's not the case.

Update API docs for 1.20.0

---

app/helpers/validation_helper.rb
app/javascript/components/analytics/PublicHealthAnalytics.js
app/javascript/components/analytics/widgets/GeographicSummary.js
app/javascript/components/public_health/PatientsTable.js
app/javascript/components/public_health/Workflow.js
app/javascript/components/public_health/actions/CloseRecords.js
app/javascript/components/subject/monitoring_actions/MonitoringActions.js
app/javascript/components/subject/monitoring_actions/MonitoringStatus.js
app/javascript/tests/mocks/mockMonitoringReasons.js
app/javascript/tests/subject/monitoring_actions/MonitoringActions.test.js
app/javascript/tests/subject/monitoring_actions/MonitoringStatus.test.js
app/models/patient.rb
app/views/patients/show.html.erb
app/views/public_health/exposure.html.erb
app/views/public_health/isolation.html.erb

Jira Ticket: SARAALERT-1081
This PR consolidates all of the Monitoree Reasons into one place
`app/javascript/components/public_health/PatientsTable.js`
- Adds Monitoring Reasons as a prop
`app/javascript/components/public_health/Workflow.js`
- Adds Monitoring Reasons as a prop
`app/javascript/components/public_health/actions/CloseRecords.js`
- Iterates over new Monitoring_Reaons for `Select` Dropdown
`app/javascript/components/subject/monitoring_actions/MonitoringActions.js`
- Adds Monitoring Reasons as a prop
`app/javascript/components/subject/monitoring_actions/MonitoringStatus.js`
- Iterates over new Monitoring_Reaons for `Select` Dropdown
`app/views/patients/show.html.erb`
- Adds Monitoring Reasons as a prop
`app/views/public_health/exposure.html.erb`
- Adds Monitoring Reasons as a …

SARAALERT-1081: Consolidates the Monitoree Reasons into one place

---

app/helpers/patient_query_helper.rb
app/models/patient.rb
app/views/patients/show.html.erb

Jira Ticket: SARAALERT-1224
* Removes unneeded `Arel.sql` statements. 
* Updates existing statements to be compatible with the new internal unsafe query method
* Updates existing statements to be compatible with the future unsafe query method > Rails 6.1.1
`patient.rb`
- slight refactor of `order_by_risk` which is a bit more lines/verbose but cleans up logic a lot and makes the actual query string frozen.
Please describe the tests needed to verify your changes. Provide instructions for reproducing these tests. List any relevant details for your …

SARAALERT-1224: Additional order fixes and prep statements for next Rails release 

---

app/javascript/components/public_health/query/AdvancedFilter.js

Jira Ticket: [SARAALERT-1157](https://tracker.codev.mitre.org/browse/SARAALERT-1157)
An applied filter will sometimes revert back to its previous saved version upon page navigation.
Steps: 
-  Open a saved advanced filter
- Choose a different field and set up a completely different filter
- Click Update
- Click Apply
- Open a record
- Click back button
- Click Advanced Filter
- Original filter parameters are shown
- Clicking Cancel, clear all filters, and then opening the saved filter will show the new changes
This ended up being a bug where axios returned a cached response [here](https://github.com/SaraAlert/SaraAlert/blob/1.21.0/app/javascript/components/public_health/query/AdvancedFilter.js#L222) instead of pulling the new data.  Adding a timestamp to the request url makes it unique …

SARAALERT-1157: Saved advanced filter bug

---

app/javascript/components/public_health/query/AdvancedFilter.js

Jira Ticket: [SARAALERT-1161](https://tracker.codev.mitre.org/browse/SARAALERT-1161)
Clicking "Cancel" in Advanced Filter modal does not clear modal or filter name
Currently if you set up a new advanced filter (i.e., choose a field to filter by and set parameters) and click "Cancel":
- The modal closes and you return to the dashboard (the filter you created is not applied)–this is correct behavior
- When you then click "Advanced Filter" it shows the parameters you had previously entered–this is incorrect behavior. The modal should revert to its previous state (the last filter that was applied, or blank if no filter was applied)
Currently if you have a filter applied and then select a saved advanced filter (i.e., from the drop-down) and click "Cancel":
- The modal closes and you return to …

SARAALERT-1161: Advance Filter Cancel Clearing Bug

---

app/javascript/components/assessment/AssessmentTable.js
app/javascript/components/history/HistoryComponent.js
app/javascript/components/patient/PatientPage.js
app/javascript/components/subject/DownloadMonitoree.js
app/views/patients/show.html.erb
test/system/roles/enroller/enroller_dashboard_test.rb
test/system/roles/enroller/enroller_test_helper.rb
test/system/roles/enroller/patient_page/patient_page_verifier.rb

Jira Ticket: [SARAALERT-1231](https://tracker.codev.mitre.org/browse/SARAALERT-1231)
When the reports table was refactored as part of 1.19.0, the frontend check to not render the component unless the user can view assessments was not added back in. This means roles that don't have access (such as Enrollers) see an empty reports table. It never loads the assessments for these roles as we have additional checks on the backend, but it still renders an empty table with the create, log, and pause action buttons. It doesn’t allow these roles to create a report or log a contact attempt, but it does allow them to pause/resume notifications.
This PR fixes the above and also adds system tests to check the patient page rendered components for Enrollers (hence the added IDs for easy selection).
Login …

SARAALERT-1231: Reports Table Component Permissions

---

app/controllers/patients_controller.rb
app/javascript/components/public_health/actions/UpdateCaseStatus.js
config/routes.rb

Jira Ticket: [SARAALERT-1045](https://tracker.codev.mitre.org/browse/SARAALERT-1045)
If one or more monitorees are selected for bulk actions and the Case Status bulk action is selected, the resulting modal was not displaying the currently selected value for the monitoree(s). Expected behavior is that a default value should be displayed if (1) a single monitoree is selected or (2) multiple moniotrees are selected and they all hold the same case status value. This PR addresses this issue so a default value is correctly displayed in these situations
1. In the Patient Table view, select a monitoree for bulk actions that is known to have a Cases Status value that is not blank.
2. In the Bulk Actions drop down, select Case Status.
3. In the resulting modal, observe that the default value is …

SARAALERT-1045: Bug fix - Case Status Bulk Action Modal default value

---

app/javascript/components/patient/Patient.js
app/javascript/packs/stylesheets/layout.scss

Jira Ticket: SARAALERT-1155
There had been a bug where the Assigned Jurisdiction and Assigned User in the MonitoreeDetail Page had not been displaying properly on MSEdge. This PR engineers that problem out, by transitioning the top section of the Monitoree Detail page to a more responsive design. This guarantees that the Assigned Jurisdiction and Assigned User box always has enough space.
Previously, the width of the responsive columns had been "auto" which has the potential for undesirable behavior. By defining the breakpoints for the columns, this guarantees that there will always be enough space for the data.
` …

SARAALERT-1155: Fix UI Bug in MS Edge

---

app/lib/import_export.rb
app/models/transfer.rb
test/models/transfer_test.rb

Jira Ticket: SARAALERT-1144
Transfer.latest_transfers scope written with test & update import_export.rb to use scope
[PR where bug was originally found](https://github.com/SaraAlert/SaraAlert/pull/625#discussion_r549416079)
There is a rare edge case we believe could crop up for the transfer data in exports if two transfers have the same timestamp. With the example below, all 3 transfers would be returned instead of the expected 2.
| patient_id | created_at                           |
| ---------- | ------------------------------------ |
| 1          | Fri, 25 Dec 2020 19:02:04 UTC +00:00 |
| 2          | Fri, 25 Dec 2020 19:02:04 UTC +00:00 |
| 2          | Sat, 26 Dec 2020 20:17:20 UTC +00:00 |
The solution was to write a new scope in the transfer model that does a proper tuple …

SARAALERT-1144: Latest transfer edge case

---

app/helpers/patient_details_helper.rb
app/lib/import_export.rb
app/models/patient.rb
lib/tasks/demo.rake
test/system/roles/public_health/dashboard/export_verifier.rb

Jira Ticket: [SARAALERT-1205](https://tracker.codev.mitre.org/browse/SARAALERT-1205)
The timestamps for fields in exports are not consistently formatted. The PO team would like them to be consistent and the desired format is `YYYY-MM-DD hh:mm:ss UTC`.
Perform a custom export, csv export, and comprehensive export and take a look at the timestamps.
Remove the `rfc2822` formatting for timestamps.

SARAALERT-1205: Format dates in custom export consistently

---

app/controllers/fhir/r4/api_controller.rb
app/controllers/patients_controller.rb
app/helpers/fhir_helper.rb
app/helpers/patient_helper.rb
app/javascript/components/subject/monitoring_actions/Jurisdiction.js
app/models/assessment.rb
app/models/history.rb
app/models/patient.rb
app/models/user.rb
test/controllers/fhir/r4/api_controller_test.rb
test/controllers/patients_controller_test.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-944](https://tracker.codev.mitre.org/browse/SARAALERT-944)
This PR consolidates the logic that existed on the `PatientsController` (specifically in the `update_fields` function) onto the `Patient` model, so that the logic can be used via both the `PatientsController`, and the `APIController`. This logic includes side effects that happen when a certain field is updated (ex: If `monitoring` is set to `false`, then `closed_at` is set), and generation of `History` items (ex: Adding a history item that indicates that `monitoring` changed).
- Added `update_all_patient_history` function, and called it in `update` so that `History` items are generated when updates are made via the API
- Added a line to create a `Transfer` if a Patient is transferred to …

SARAALERT-944: Consolidate field update logic in application so it can be used in API updates

---

config/application.rb

This is in response to a change in Rails 6.1 that changed the default queue user for ActionMailer jobs from `mailers` to `default`.
`config/application.rb`
- Changing the default mailer queue name explicitly to be `mailers`.
To test, do the following:
- Run sidekiq on the default queue in one window
- Run sidekiq on the mailers queue in another
- Run something like `PatientMailer.assessment_sms(Patient.last).deliver_later` and notice it get enqueue in the `mailers` queue …

Setting Default Mailer Queue in Application Configuration

---

app/javascript/components/enrollment/steps/Exposure.js

As part of 1.21 we changed the ID on the isolation/case notes field which caused issues because the `handleChange` function expects the ID to match the field name which is `exposure_notes` in both cases. 
Open enrollment wizard in isolation and try and type in case notes field.
See above description.
`app/javascript/components/enrollment/steps/Exposure.js`
- Above fix.

(Bugfix) Fix for Isolation Notes field in Enrollment/Edit Wizard

---

app/jobs/cache_analytics_job.rb
app/models/transfer.rb
test/jobs/analytics_job_test.rb
test/models/transfer_test.rb

Jira Ticket: [SARAALERT-1154](https://tracker.codev.mitre.org/browse/SARAALERT-1154)
Transfer columns do not include sub-jurisdictions which needs to be changed to include them.
Transfer a monitoree from `USA, State 1, County 1` to `USA, State 1, County 2`, view analytics before and after running analytics and notice that the transfer numbers do not change.
- query transfers from jurisdiction subtree instead of only the immediate jurisdiction

SARAALERT-1154: Analytics Transfer Data is inconsistent

---

app/controllers/patients_controller.rb
app/javascript/components/subject/ChangeHOH.js
app/javascript/components/subject/MoveToHousehold.js
app/javascript/components/subject/RemoveFromHousehold.js
config/routes.rb
test/controllers/patients_controller_test.rb

Jira Ticket: [SARAALERT-1093](https://tracker.codev.mitre.org/browse/SARAALERT-1093)
This PR does the following:
- Addresses bugs related to simultaneous household edits
- Refactors actions for household updates
- Adds additional error checking and many tests for household updates
This PR fixes various issues when a edits to households are happening simultaneously.
**A) Move To Household: User being able to set a HoH as a dependent:**
1. Open two different records (record A and record B) where the monitorees are self reporting (do not select a HH dependent or a HoH).
2. Click “Move To Household” button on both records.
3. In the modal for record A, search for record B and select it as a HoH.
4. In the modal for record B, select any other record.
5. Notice that record B is both a HoH and a …

SARAALERT-1093: Household updates refactor, bugfixes, and tests

---

app/jobs/send_purge_warnings_job.rb
app/models/jurisdiction.rb

Jira Ticket: [SARAALERT-1223](https://tracker.codev.mitre.org/browse/SARAALERT-1223)
Locked admins should not receive emails about purge notices.
1. Create a locked admin and an unlocked admin with jurisdiction over USA, State 1
2. Create a purge eligible patient in that jurisdiction
3. Start sidekiq up
4. Using the Ruby console enter `SendPurgeWarningsJob.perform_now`
5. Verify that the unlocked admin receives an email while the locked admin does not

SARAALERT-1223: Don't send purge emails to locked Admins

---

app/javascript/components/public_health/PublicHealthHeader.js
public/Sara Alert Import Format.xlsx

Jira Ticket: [SARAALERT-1274](https://tracker.codev.mitre.org/browse/SARAALERT-1274)
This updates the formatting guidance to no longer contain an invalid value for the "Foreign Monitored Address State" field on the "Example" tab.
`public/Sara Alert Import Format.xlsx`
- On the "Example" tab, the invalid value of "Emahaven" was replaced with "Minnesota" in the "Foreign Monitored Address State" column, since this field is constrained to be a US State.
- On the "Guidance" tab, the description of the "Foreign Monitored Address State" column was updated to indicate that this field must be a US State (or an abbreviation).
Previously, if you downloaded the formatting guidance for import, and then used the …

SARAALERT-1274: Update "Foreign Monitored Address State" in Import Formatting Guidance

---

app/javascript/components/enrollment/Enrollment.js
app/javascript/components/enrollment/steps/Exposure.js

Jira Ticket: [SARAALERT-1098](https://tracker.codev.mitre.org/browse/SARAALERT-1098)
While using the enrollment wizard if you changed the jurisdiction, clicked next and confirm the change, then click previous, click next again the same popup would appear to confirm the change again. 
This change will make it so a popup is only shown when changing the jurisdiction to a value that is different than the original value (last saved jurisdiction) or a new selection that is different than the last selection and the original value. 
While editing a monitoree if you typed in the jurisdiction field and then saved, even if it ended up being the same value it would save that as a transfer.
Test dialog changes …

SARAALERT-1098: Changing Jurisdiction to same value should not count as a transfer

---

app/javascript/components/public_health/query/AdvancedFilter.js

Small update to the autoclose time on a longer error message.
1. Set `MAX_USER_FILTERS` to be something small, like 2.
2. Create max number of advanced filters and then try and create one more
3. Notice error messages stays on screen for longer

Increased timer on Advanced Filter Toast

---

app/javascript/components/public_health/query/AdvancedFilter.js
app/javascript/tests/public_health/query/AdvancedFilter.test.js

Jira Ticket: [SARAALERT-1274](https://tracker.codev.mitre.org/browse/SARAALERT-1275)
Deleting first filter in advanced filter makes second blank filter assume first value
1. Open new advanced filter
2. Select an option from the dropdown
3. Click the plus-sign to add new filter
4. click the minus on the first option and note that the yet-unselected filter assumes the deleted value
When a value isn't set in the Options Select, the value would be `undefined`, which does not trigger an update back to the placeholder.  Updated to make sure that value is `null`, which does trigger the placeholder update.
- Ensure the …

SARAALERT-1275: Advanced Filter Delete/Clearing Bug

---

app/javascript/components/admin/AuditModal.js

Jira Ticket: SARAALERT-1120
Before, in the admin audit table user roles would render as the values we use to represent them in the backend: lower-case, separated by underscores. This adds formatting to make them consistent with how we represent the roles elsewhere such as in the dropdown menu. 
Screenshots:
app/javascript/components/admin/AuditModal.js
- only file changed, adds formatting code to the original and modified role values. 
To replicate the test, start the server and log in as an admin user. Pick a user at random from the admin table, change their role value a few times, then look at the audit table.

SARAALERT-1120: Reformatting role names in admin audit table

---

app/controllers/fhir/r4/api_controller.rb

Jira Ticket: SARAALERT-1302
This adds a few logging statements to the ApiController in order to make debugging in demo and prod easier. In reviewing, please verify that no PII/PHI could end up being logged.
The changes here are pretty low risk, but it's late in the game so let me know if you want me to retarget to 1.24.0.
- Added several logging statements
You can test that each of the cases does in fact log and logs the correct info:
- Logs client info in User workflow
- Logs client info in M2M workflow
- Logs error message and stacktrace on 500 error from any controller method (suggest adding a `throw StandardError` in controller method to test)
- Logs validation errors on 422

SARAALERT-1302: API Logging

---

app/javascript/components/layout/CustomTable.js
app/javascript/packs/stylesheets/custom_table.scss

Jira Ticket: SARAALERT-1248
The Pagination Component at the bottom of the CustomTable was not behaving in a responsive manner. At smaller viewports, it would either sit over the left-hand content, or be pushed off to the side of the parent container, or both! (as shown in this image). 
This pull request adds custom styling to prevent this issue from occurring. It adds a custom viewport breakpoint using media queries which pushes the pagination down onto a new line. This remains properly formatted until EXTREMELY small viewports (smaller than this project supports).
Other ideas were tested with the Pagination Component remaining always on the second line, or maybe being centered on the second line. But these ideas were not favored, and so this PR only includes the drop-down at the viewport …

SARAALERT-1248: Making CustomTable Pagination Responsive 

---

app/javascript/components/close_contact/CloseContact.js
app/javascript/tests/close_contact/CloseContact.test.js

Jira Ticket: SARAALERT-1099
This Pull Request is a followup to SARAALERT-616. It updates the CloseContact Modal to better fit the new elements. The previous pull request lead to the Modal getting too vertically long. This pull request adds a two-column system that better makes use of the screen real estate. It is responsive across all major viewports (the two-to-one column breakpoint change iis at the LG (large) viewport breakpoint). 
This PR also adds required fields per user feedback. The Modal may not be submitted without at least one of First Name, Last Name, Email, or Phone.
This PR also refactors the tests which had been designed with the one-column system in mind.
(The little **D** emoji in the image is from my password manager, and is not there in reality)
Please list important …

SARAALERT-1099: Close Contacts Modal Updates

---

app/helpers/patient_query_helper.rb
app/javascript/components/layout/CustomTable.js
app/javascript/components/public_health/PatientsTable.js
app/javascript/components/public_health/query/AdvancedFilter.js
app/javascript/components/public_health/query/AssignedUserFilter.js
app/javascript/tests/public_health/Export.test.js
app/javascript/tests/public_health/PatientsTable.test.js
test/system/roles/public_health/patient_page/patient_page_verifier.rb

Jira Ticket: [SARAALERT-1085](https://tracker.codev.mitre.org/browse/SARAALERT-1085) & [SARAALERT-1272](https://tracker.codev.mitre.org/browse/SARAALERT-1272)
Other Jira tickets that are no longer relevant due to this PR: [SARAALERT-1043](https://tracker.codev.mitre.org/browse/SARAALERT-1043) & [SARAALERT-914](https://tracker.codev.mitre.org/browse/SARAALERT-914)
Resolves several issues identified with sticky filters on the `PatientsTable`. Also includes these bug fixes:
- Bulk Actions drop down is now hidden when on the Transferred Out line list
- Sorted results based on a column sort for the patient table will have the same precise order each time a sort is done
- If a sticky filter value for Assigned User exists, the filter input box will be properly populated now
1. Go to the Non …

SARAALERT-1085: Ensure Dashboard sticky filters are set properly

---

app/javascript/components/public_health/query/AdvancedFilter.js
app/javascript/tests/mocks/mockFilters.js

1. Open "Network" tab under Chrome dev tools
2. Open the advanced filter modal and create a new filter with any relative date (ex: "Latest Report (Relative Date)")
3. Select today, tomorrow, or, yesterday and click "Apply"
4. Notice that a 400 error is returned with the message: `"param is missing or the value is empty: value"`
The error is being thrown because `filter.require(:value)` is called when `filter[:value]` is not defined for these cases
`app/controllers/user_filters_controller.rb`, `app/helpers/patient_query_helper.rb`
- Remove `filter.require(:value)` since it's already covered by `filter.require(:value)`
Please describe the tests needed to verify your changes. Provide instructions for …

BUGFIX: Fix advanced filter relative date bug

---

app/controllers/close_contacts_controller.rb
app/controllers/laboratories_controller.rb
app/controllers/users/registrations_controller.rb

Fix areas where redirect_to was being called without parenthesis and combined with '&& return'
Jira Ticket: SARAALERT-1321
Uses the correct operator order of precedence when using the common idiot `redirect_to(url) && return` to avoid double render errors.
Additional information:
https://guides.rubyonrails.org/layouts_and_rendering.html#avoiding-double-render-errors'
https://stackoverflow.com/a/37211667
In all files changed I added parenthesis to fix the potential issue.

SARAALERT-1321 redirect_to && return

---

app/javascript/components/close_contact/CloseContact.js
app/javascript/tests/close_contact/CloseContact.test.js

This PR is a followup to the 1099 PR that was recently merged. There was feedback from User Training that suggested that the system should require `Name (First or Last) AND Reporting Method (Email or Phone)` as opposed to what we had before which was `First OR Last OR Email OR Phone`.
This PR updates that logic, and updates the front-end tests to support that new logic.

SARAALERT-1099: CloseContacts Required Fields Updates

---

app/helpers/patient_helper.rb
lib/assets/states_with_time_zone_data.yml
test/helpers/patient_helper_test.rb

Jira Ticket: SARAALERT-987
Previous functionality returned Patient time zone offsets based on if Eastern time swapped over to daylight savings time. This change sets offsets based on the address state time zone.
`patient_helper.rb` - main changes
`patient_helper_test.rb` - added tests that ensure returned values are formatted the same as previous behavior

SARAALERT-987: Set time zone offset correctly during DST

---

app/helpers/fhir_helper.rb
app/helpers/validation_helper.rb
app/models/patient.rb
test/controllers/fhir/r4/api_controller_test.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-1276](https://tracker.codev.mitre.org/browse/SARAALERT-1276)
This PR implements support for reading/writing continuous exposure via the API. Additionally, it adds validation so that `continuous_exposure` and `last_date_of_exposure` cannot both be set. 
`fhir_helper.rb`
- Add support for `continuous_exposure` in the `patient_from_fhir` and `patient_to_fhir` methods.
`patient.rb`
- Add validation on the Patient model (API context only) so that `continuous_exposure` and `last_date_of_exposure` are mutually exclusive.
To test this, you can make API requests and verify:
- Reading and writing of `continuous_exposure` via the API
- An error is returned if both `continuous_exposure` and `last_date_of_exposure` are set
- `continuous_exposure` or `last_date_of_exposure` must …

SARAALERT-1276: Support Continuous Exposure in the API

---

app/controllers/patients_controller.rb

Jira Ticket: SARAALERT-1106
This Pull Request addresses an issue where changes to a Monitoree's Jurisdiction would appear twice in the History list. This is due to the fact that we maintain items for Jurisdiction Changes, and a detailed list of all changes. When only the Jurisdiction was changed, there would be two entries (see image).
The fix for this is to filter out `jurisdiction_id` changes from the Detailed List. This prevents the duplication of data.
This solution has been approved by the PO and Development teams.
- In `master` change a monitoree's jurisdiction. Then go view the History. You will see the two entries (like the above image).
- Now, in this branch, do the same. You will notice that any `jurisidiction_id` changes are omitted from the Detailed_History History item. …

SARAALERT-1106: Removes Duplicate Jurisdiction Change in History

---

app/controllers/fhir/r4/api_controller.rb
app/helpers/patient_helper.rb
test/controllers/fhir/r4/api_controller_test.rb

Jira Ticket: [SARAALERT-1291](https://tracker.codev.mitre.org/browse/SARAALERT-1291)
History items were not being created for several fields (`travel_related_notes` for example) when those fields were updated via the API. We were only updating fields in an `info_fields` array, which did not contain all possible fields. This PR refactors our approach, so that all current fields will have History items created.
On the `1.24.0` branch, do a `PUT` or `PATCH` update on a Patient, and change the Patient's `email` and `travel_related_notes`. A history item will be created detailing the change in `email`, but the item will not include the change in `travel_related_notes`. On this branch, if you do the same update, you should see a history item that lists both changes.
The issue was that the …

SARAALERT-1291: History items not created for certain fields in API

---

.gitignore
.gitlab-ci.yml
Gemfile
Gemfile.lock
script/assert_jmeter_results.rb
script/benchmark.rb
script/benchmarks/close_patients_job_benchmark.rb
script/benchmarks/output/.gitignore
script/benchmarks/send_assessments_job_benchmark.rb
script/jmeter/01_public_health_dashboard_jmx_test.rb
script/run_jmeter_tests.sh

Jira Ticket: SARAALERT-1192
This PR shows an example JMeter test automated in CI, as well as a standalone example benchmark script for the send assessments job.
Rails 6.1 has this [benchmark generator built-in](https://github.com/rails/rails/tree/master/railties/lib/rails/generators/rails/benchmark) that uses the [benchmark-ips](https://github.com/evanphx/benchmark-ips) gem. We are also free to modify the file to use the vanilla benchmark library (https://ruby-doc.org/stdlib-2.5.0/libdoc/benchmark/rdoc/Benchmark.html)
IMO JMeter is a better solution for load and stress testing, while the rails benchmarking example does well for understanding performance of highly targeted slices of the code with detailed CPU & RAM logging with stackprof and memory_profiler. We would likely benefit by …

SARAALERT-1192: Performance testing

---

app/javascript/components/assessment/steps/SymptomsAssessment.js

Jira Ticket: SARAALERT-916
This PR fixes an issue with Google Translate causing a bug on the Assessment page (when users submitted their daily assessment). If the user was using Google Translate to translate their page, React would get confused when they attempted to submit it. Because Google Translate changes parts of the DOM, React was unable to locate things it was looking for in its node-tree. This PR wraps the necessary text in a `<span>`. This works to solve the problem as those text nodes with `<span>` can still be referenced by React, as they will stay in the DOM tree even though their contents are replaced with `<font>` tags (from Google Translate).
I will note that, despite the bug not rendering the correct "You submitted your assessment correctly!" page, the assessments *were* …

SARAALERT-916: Google Translate Bug Fix

---

app/views/patients/_patients.html.erb

Jira Ticket: SARAALERT-1212
Before, we had a bug where, whenever the jurisdiction was changed in the patient index interface, the scope would be changed to "all" even if it had been "exact match" beforehand. This updates the javascript to change the scope to its set value whenever the page is updated, and modifies the demo.rake to cover the test case that produced the error so we catch these in the future. 
Bug report here: 
https://teams.microsoft.com/l/file/F25865B2-C3D6-40CF-AF62-FD8FEB1033C5?tenantId=c620dc48-1d50-4952-8b39-df4d54d74d82&fileType=pptx&objectUrl=https%3A%2F%2Fmitre.sharepoint.com%2Fsites%2FCoVDT%2FShared%20Documents%2FGeneral%2FProduct%20Owner%20Materials%2FTesting%2FBug%20Reports%2FEnroller%20Scope%20bug.pptx&baseUrl=https%3A%2F%2Fmitre.sharepoint.com%2Fsites%2FCoVDT&se …

SARAALERT-1212: Dashboard Jurisdiction "Scope" Bugfix

---

app/controllers/assessments_controller.rb
app/helpers/assessment_query_helper.rb

No JIRA ticket associated
Change AssessmentsQueryHelper#format to #format_for_frontend so as not to conflict with Kernel#format when including AssessmentsQueryHelper from the console.
drop into `rails c`
```
include AssessmentsQueryHelper
app/helpers/assessment_query_helper.rb:71:in `format': wrong number of arguments (given 2, expected 1) (ArgumentError)
```
Change the method name

Error when including AssessmentsQueryHelper from the console

---

app/helpers/patient_query_helper.rb
app/javascript/components/public_health/query/AdvancedFilter.js
app/javascript/packs/stylesheets/advanced_filter.scss
app/javascript/tests/mocks/mockFilters.js
app/javascript/tests/public_health/query/AdvancedFilter.test.js

Jira Ticket: [SARAALERT-1023](https://tracker.codev.mitre.org/browse/SARAALERT-1023)
Added support for more than x unit in the future/past for all relative date filter options.
- Added operator dropdown as the fourth option for custom relative date filters
- Additional logic needed for adding more than option to the advanced filter
`advanced_filter.scss`
- Updated styling in order for all the dropdowns to fit on the same line
`AdvancedFilter.test.js`
- Updated/fixed broken tests
`mockFilters.js`
- Updated mocks to incorporate new operator value option …

SARAALERT-1023: Advanced Filter Relative Date Improvements

---

lib/assets/counties.yml

Jira Ticket: SARAALERT-1359
The state of Rhode Island had been left out of Counties.yml. This is a tiny change, but they should be added for consistency's sake. This only impacts `demo.rake`

SARAALERT-1359: Adds Counties to Counties.yml

---

app/javascript/components/assessment/steps/SymptomsAssessment.js
app/javascript/tests/assessment/steps/SymptomsAssessment.test.js
app/javascript/tests/mocks/mockAssessments.js
app/javascript/tests/mocks/mockSymptoms.js
app/javascript/tests/mocks/mockTranslations.js

Jira Ticket: [SARAALERT-1145](https://tracker.codev.mitre.org/browse/SARAALERT-1145)
Certain browsers allowed users to input non-numerical values into `FloatSymptom` input fields which caused errors at times. This PR addresses that issue as well as two other issues that were identified while testing the original reported bug: 
- `IntegerSymptom`s did not render in the `SymptomsAssessment` component when present
- Inputs over a certain value would cause errors.
`IntegerSymptom`s now display properly in the `SymptomsAssessment` component:
**Bug 1**: `FloatSymptom` inputs accepted non-numerical inputs (all browsers except Chrome) and at times caused errors (specifically for Internet Explorer).
1. While in Internet Explorer, navigate to a monitoree's profile that has a `SymptomAssessment` …

SARAALERT-1145: SymptomsAssessment input validation & IntegerSymptom support

---

app/models/patient.rb
test/db/database_test.rb
test/models/patient_notification_eligibility_test.rb
test/models/patient_test.rb

Jira Ticket: SARAALERT-1250, 770
DEPENDS ON: https://github.com/SaraAlert/SaraAlert/pull/634
This pull request introduces:
- comprehensive reminder eligibility tests for patients (These will fail until we complete the `reminder_eligible` scope).
- additional patient scopes that can be added to `reminder_eligible` and allow logic to be removed from `send_assessment`.
- creates a `better_reminder_eligible` scope that can pass the reminder eligibility tests.
I realize that changing the `reminder_eligible` scope all at once is a big leap, so I'd like to get these merged in and then add to the scope incrementally.
`patient.rb`
- New …

SARAALERT-1250, 770: Patient eligibility tests & supporting scopes

---

app/javascript/components/laboratory/Laboratory.js

Fixed copy paste error where the `Add New Lab Result` button actually says `Add New Close Contact`

Revert lab results button text

---

app/javascript/components/admin/AdminTable.js

Fixes a bug only in 1.25.0 introduced when a CSS class that was previously only applied to the Reports table, was changed to apply generally to the CustomTable (since other implementations such as the VaccinesTable needed it). See descriptions below for how to replicate and a description of the solution.
1. Run `1.25.0` locally and open in Safari.
2. Navigate to the Admin Panel and try to click any of the three buttons above the table - notice they are unclickable.
- There was previously an issue where tables that had buttons that spawned dropdowns (such as the `ReportsTable`) would have those dropdowns cut-off by the `CustomTable` because overflow-y was not specified. Turns out, in the css spec when you have overflow-x on an element set to auto/scroll, then overflow-y gets also …

(Bugfix) Buttons above Admin Table Unclickable in Safari

---

docs/api/api-coming-soon.md
docs/api/api-release-notes.md

This updates the API documentation to be accurate with respect to 1.24.0.
`docs/api-coming-soon.md`
* Update to indicate things coming in 1.25.0
`docs/api-release-notes.md`
* Update to indicate what was released in 1.24.0
I think it makes sense for us to start doing these updates the second the candidate branch gets merged, for some reason in my head I had been thinking we had to wait until the version was actually released, but that isn't right, we just have to wait on the release before we actually push to `gh-pages`.

API Documentation Updates for 1.24.0

---

Gemfile
Gemfile.lock
app/controllers/export_controller.rb
app/controllers/jurisdictions_controller.rb
app/helpers/patient_details_helper.rb
app/helpers/patient_query_helper.rb
app/jobs/export_job.rb
app/lib/import_export.rb
app/lib/import_export_constants.rb
app/lib/utils.rb
app/models/assessment.rb
app/models/close_contact.rb
app/models/history.rb
app/models/laboratory.rb
app/models/transfer.rb
app/models/user.rb
app/views/patients/edit.html.erb
app/views/patients/new.html.erb
app/views/patients/new_group_member.html.erb
lib/tasks/demo.rake
test/fixtures/patients.yml
test/system/roles/public_health/dashboard/dashboard_verifier.rb
test/system/roles/public_health/dashboard/export_verifier.rb

Jira Ticket: [SARAALERT-1287](https://tracker.codev.mitre.org/browse/SARAALERT-1287)
- Profile export performance (both memory and speed) and main problematic areas
- Implement changes to improve performance and profiled changes
Speed and memory for 36k monitorees:
Changes before (top) and after (bottom)
From left to right: csv linelist exposure, sara alert format exposure, excel export for all monitorees, custom export for all monitorees with everything checked off
As show in the graphs above, there is significant performance improvements in terms of speed and memory. The upward spikes in memory (more obvious in the "all" and "custom" exports) are caused by `workbook.read_string` which loads an entire excel file's worth of data from a file on disk to memory to be written to the database. …

SARAALERT-1287: Optimize Export Performance

---

app/javascript/packs/stylesheets/bootstrap.scss

Jira Ticket: SARAALERT-1383
There is a new issue on Chromium based browsers where the Form-Control elements we use behave in a laggy manner. They are slow and very unresponsive. The exact cause of this is not entirely understood. However, I have figured out a fix. Removing the bootstrap `.form-control` `transition` styling prevents the issue from appearing.
This fix was tested on the following browsers:

SARAALERT-1383: Form Control Lag Fix

---

app/helpers/validation_helper.rb
app/javascript/components/enrollment/steps/Identification.js
app/javascript/components/public_health/query/AdvancedFilter.js
app/javascript/components/util/DateInput.js

Jira Ticket: [SARAALERT-1337](https://tracker.codev.mitre.org/browse/SARAALERT-1337)
The issue stems from the fact that you can apply a filter with the date field empty.  For “before” or “after,” that value would be null because it’s only one field so when you apply the filter it fails as a bad request (which is the intended behavior).  With “within,” there are “start” and “end” fields in the value so it gets past the check if the value is empty, causing that error to in the sentry error in the JIRA.
1. Open the advanced filter modal and select a date field
2. Clear the date input and hit apply (notice there is an error)
3. Repeat step 1 but select "before" or "after" instead of "within"
4. Observe similar behavior
Prevent the user from submitting an empty date by reverting the date to …

SARAALERT-1337: Prevent advanced filter from submitting empty date inputs

---

app/controllers/patients_controller.rb

With the apply to household refactor, household dependents can now see the apply to household radio buttons.  With this, if a dependent is in the isolation workflow, they can now update the LDE if there are any other household members (including the HoH) that are CE in the exposure workflow.  This fixes a bug where if you select to update the LDE, the HoH was not being updated with the new LDE and turning off CE.
Fix: https://user-images.githubusercontent.com/35042815/111374689-c6d2d900-8673-11eb-8a06-f1d50da3d7cd.mov

Monitoring status LDE household update bug

---

app/helpers/patient_query_helper.rb
app/javascript/components/public_health/PatientsTable.js
app/javascript/packs/stylesheets/application.scss
app/javascript/packs/stylesheets/bootstrap.scss
app/javascript/packs/stylesheets/patient.scss
app/javascript/tests/mocks/mockPatients.js
app/models/assessment.rb
app/models/patient.rb
config/initializers/filter_parameter_logging.rb
db/migrate/20210315134120_add_latest_assessment_symptomatic_to_patients.rb
db/schema.rb
lib/tasks/demo.rake
test/jobs/purge_job_test.rb
test/models/assessment_test.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-711](https://tracker.codev.mitre.org/browse/SARAALERT-711)
Display if a monitoree's latest report was symptomatic through an icon on the Patients dashboard.
`app/helpers/patient_query_helper.rb`
- Include symptomatic flag as a part of the Latest Report data element
`app/javascript/components/public_health/PatientsTable.js`
- New format method for the Latest Report column to handle displaying the symptomatic icon
`app/javascript/packs/stylesheets/bootstrap.scss`
- New style class for symptomatic icon
- Method to determine if a monitoree's latest assessment was symptomatic & not reviewed

SARAALERT-711: Symptomatic Dashboard Icon

---

app/helpers/patient_query_helper.rb
app/javascript/components/public_health/query/AdvancedFilter.js
app/javascript/components/util/InfoTooltip.js
test/helpers/patient_query_helper_test.rb

Jira Ticket: [SARAALERT-975](https://tracker.codev.mitre.org/browse/SARAALERT-975)
This Pull Request adds the ability to filter by Blocked Numbers in the Advanced Filter. Jurisdictions wanted this ability, as it lets them know who they need to follow up, through other means.
`app/helpers/patient_query_helper.rb`
- Adds the back-end logic for including Blocked Numbers in the Advanced Filter
`app/javascript/components/public_health/query/AdvancedFilter.js`
- Adds the front-end logic for including Blocked Numbers in the Advanced Filter
- Updates some terminology (per Product Owner Team …

SARAALERT-975: Blocked Number Advanced Filter

---

app/javascript/components/public_health/query/AdvancedFilter.js

Ensure the advanced filter modal is fully reset reset after deleting a saved filter.
To recreate:
1. Delete any saved advanced filter
2. Click the "Advanced Filter" button to re-open the modal
3. Click the plus sign and an error fires blanking out the page

Advanced filter delete saved filter bugfix

---

app/controllers/admin_controller.rb
app/javascript/components/admin/AdminTable.js
app/javascript/components/layout/CustomTable.js
test/system/roles/admin/dashboard/dashboard_verifier.rb

Jira Ticket: [SARAALERT-475](https://tracker.codev.mitre.org/browse/SARAALERT-475)
Add switch/toggle above admin table to hide/show locked users. Default to only showing unlocked.
https://user-images.githubusercontent.com/35042815/111217843-63ca3f00-85ac-11eb-8812-1810a0228055.mov
`admin_controller.rb`
- Added support to filter users by all/unlocked/locked
`AdminTable.js`
- Added all/unlocked/locked toggle buttons at the top of admin table for filtering
`CustomTable.js`
- Fixed bug where "No data to display" column wouldn't span the whole admin table
This fix was tested on the following browsers (submitter must check all those that …

SARAALERT-475: Ability to hide locked users

---

app/helpers/patient_details_helper.rb
app/helpers/patient_query_helper.rb
app/javascript/tests/mocks/mockPatients.js
app/models/laboratory.rb
app/models/patient.rb
config/initializers/filter_parameter_logging.rb
db/migrate/20210317233414_replace_latest_positive_lab_with_first_positive_lab_on_patients.rb
db/schema.rb
lib/tasks/demo.rake
test/fixtures/patients.yml
test/jobs/purge_job_test.rb
test/models/laboratory_test.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-1381](https://tracker.codev.mitre.org/browse/SARAALERT-1381)
For our “isolation asymptomatic non test based” recovery definition (code here), we’re currently using “latest positive lab” instead of “first positive lab”, which seems to be incorrect based on the [cdc guidelines](https://www.cdc.gov/coronavirus/2019-ncov/hcp/disposition-in-home-patients.html).
- Update recovery definition logic
`db/migrate/20210310170556_replace_latest_positive_lab_with_first_positive_lab_on_patients.rb`
- Migration to replace and populate field
`db/migrate`
- Replace `latest_positive_lab_at` with …

SARAALERT-1381: Update "isolation asymptomatic non test based” recovery definition

---

app/controllers/fhir/r4/api_controller.rb
app/helpers/fhir_helper.rb
app/helpers/validation_helper.rb
app/models/close_contact.rb
app/models/concerns/complete_close_contact_validator.rb
config/initializers/doorkeeper.rb
docs/api/api-specification.md
docs/api/index.md
test/controllers/fhir/r4/api_controller_test.rb
test/controllers/fhir/r4/observation_test.rb
test/controllers/fhir/r4/patient_test.rb
test/controllers/fhir/r4/questionnaire_response.rb
test/controllers/fhir/r4/related_person_test.rb
test/fixtures/close_contacts.yml
test/models/close_contact_test.rb

Jira Ticket: [SARAALERT-1255](https://tracker.codev.mitre.org/browse/SARAALERT-1255)
This PR adds support for Close Contacts in the API. The Close Contacts are represented using a FHIR [RelatedPerson](https://www.hl7.org/fhir/relatedperson.html) resource. The API can be used to write and to read close contacts.
- Support a GET endpoint for RelatedPerson in the `show` method
- Support a PUT endpoint for RelatedPerson in the `update` method
- Support a POST endpoint for RelatedPerson in the `create` method
- Support searching of RelatedPersons in the `search` method
- Modify the `all` method so that it includes RelatedPersons
`fhir_helper.rb`
- Add a `close_contact_as_fhir` function for going from a ruby `CloseContact` to a FHIR RelatedPerson
- Add a …

SARAALERT-1255: Support Close Contacts in the API

---

test/test_helper.rb

Removes deprecation warning when running tests:
```
Mocha deprecation warning at /Users/kfagan/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': Test::Unit must be loaded *before* `require 'mocha/test_unit'`.
```
We are not using test unit. We are using minitest. https://guides.rubyonrails.org/testing.html#available-assertions

Remove require for mocha/Test::Unit since we are not using Test::Unit

---

app/javascript/components/admin/AdminTable.js
app/javascript/components/layout/CustomTable.js
app/javascript/components/public_health/PatientsTable.js
app/javascript/components/subject/household_actions/ApplyToHousehold.js
app/views/admin/index.html.erb

Jira Ticket: [SARAALERT-1307](https://tracker.codev.mitre.org/browse/SARAALERT-1307)
```
All aria labels for "Actions" checkboxes on the dashboard now begin with "select all", and then provide monitoree's name. However, only the very first top checkbox actually allows the user to "select all". Remove the "Select all" language from all action checkboxes but the first top one.
```
This ended up not being an issue with the individual row aria labels being in correct, however it is some how an issue with JAWS which reads the header checkbox aria label as well as the one from the row the user is on.  For now, updated the text in both the select all checkbox and the one in each row to make it easier for them to be read out loud.  Also refactored the individual row aria-label text to be passed …

SARAALERT-1307: Table row checkbox aria label updates

---

config/environments/test.rb
test/db/database_test.rb
test/models/patient_test.rb

Jira Ticket: SARAALERT-1398
Our GitHub actions runners are running in UTC. We have run into a few scenarios where tests will pass in a developer's local timezone, but then fail on the runner. This ticket is for changing the `config/environments/test.rb` file to force use of the 'UTC' time zone when running tests.
This PR also incorporates some `Timecop.return` calls that should have been written previously.
`config/environments/test.rb`
- Force use of 'UTC' timezone
`database_test.rb`, `patient_notification_eligibility_test.rb`, `patient_test.rb`
- added missing `Timecop.return` statements
**Submitter:**
@Bialogs  :
@holmesie  : …

SARAALERT-1398: Force tests to run in UTC

---

app/javascript/components/util/InfoTooltip.js

Removes the italics on the SMS Blocked tooltip per user feedback.

un-italicized blocked-sms tooltip terminology

---

app/lib/import_export.rb
test/system/roles/public_health/dashboard/dashboard.rb
test/system/roles/public_health/public_health_custom_export_test.rb
test/system_test_case.rb

These changes address a bug that is caused by ActiveRecord `pluck` returning inconsistent array dimensions if only 1 field is plucked (1D array) vs when multiple fields are plucked (2D array)
Perform a custom export where only `updated_at` is the only selected field from `assessments` for export
Convert plucked records from 1D array to 2D array if only one field is plucked
`import_export.js`
- Fix extract data methods
**Submitter:**
@holmesie  :
@ngfreiter  :
@Bialogs  :

FIX: Export bug when only one field is selected

---

app/controllers/import_controller.rb
app/controllers/patients_controller.rb
app/models/patient.rb
test/models/patient_duplicate_detection_test.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-727](https://tracker.codev.mitre.org/browse/SARAALERT-727)
This ticket addresses the duplicate detection logic when importing patients. Originally First Name, Last Name, Date of Birth, and Sex or State/Local ID had to match. Now First Name and Last Name or State/Local ID have to match. DoB and Sex will be checked for additional logging information but are now optional.
In the image below we use as much information as we can while displaying the duplicate messages but all of them are considered duplicates
First import all of the patients here 
[import_cain.xlsx](https://github.com/SaraAlert/SaraAlert/files/6172601/import_cain.xlsx)
Then import these to test for the detections …

SARAALERT-727: Refine Duplicate Detection

---

.github/workflows/performance.yml

I've noticed some performance testing jobs that seem to just hang indefinitely for no apparent reason - I'm wondering if this is just an artifact of using shared GitHub resources. The default timeout from GitHub is 360 minutes, which is much longer that what we should tolerate. This PR reduces the timeout for performance testing jobs to 30 minutes.
Here is an example of one of the 6 hour timeouts: https://github.com/SaraAlert/SaraAlert/runs/2169433913?check_suite_focus=true

Enforce GH Actions performance testing 30m timeout

---

performance/benchmark.rb

This PR changes the thresholds in GitHub Actions performance testing from using real time to now use total time (user + system). This is expected to give us more consistent results - especially on the GitHub shared resources.

Use total time in performance testing instead of real time

---

app/javascript/components/util/DateInput.js

Jira Ticket: [SARAALERT-1337](https://tracker.codev.mitre.org/browse/SARAALERT-1337)
Bug the PO team found when testing the above ticket, see steps to recreate below.
1. Select a monitoree and click edit on the Identification Section
2. Confirm DoB is set to a valid non-blank date
3. Highlight the valid date (DO NOT PRESS DELETE) and type in an invalid date (e.g. 14-14-1414)
4. Hit the Enter key (don't click outside the field)
5. Notice DOB is reverted to the prior valid date
Added the onBlur functionality to a keydown function for the enter key.  That way if an invalid date is typed and the user clicks the enter key, the DOB will revert to being blank, as it would if the user had just clicked outside the field.
**Submitter:**
@ : @timwongj 
@ : @holmesie

SARAALERT-1337 (continued): Bug when user presses enter and date is invalid

---

app/jobs/send_assessments_job.rb
app/views/user_mailer/assessment_job_email.html.erb
test/jobs/send_assessments_job_test.rb

No need to review this - PR into another one of my PRs for assessing performance impact before I make a change.
https://github.com/SaraAlert/SaraAlert/pull/726

revert job back to printing out all sent IDs

---

app/models/float_symptom.rb
app/models/integer_symptom.rb
app/models/symptom.rb
app/models/threshold_condition.rb
test/jobs/consume_assessments_job_test.rb
test/models/threshold_condition_test.rb

When assigning a reviewer, tag their GitHub username in the reviewer checklist section below.
Jira Ticket: SARAALERT-1300
When a non-symptomatic SMS/Voice report comes through, the int/float symptoms are set to 0 instead of nil. This PR makes sure that int/float symptoms values are set to nil for non-symptomatic SMS/Voice assessments.
In report mode, submit a non-symptomatic assessment for a patient in a jurisdiction that has an int/float symptom eg: any of the State1 jurisdictions in the sample jurisdictions.yml included in the repo.
`{"response_status": "success_sms","experiencing_symptoms":"No","patient_submission_token": "TYptUSsGmj","threshold_hash":"854613cf6657d5ebfef5babcc3eb0f1a465ac723859d4df0d1cdcd5ff321d165 …

SARAALERT-1300 negated non-bool symptom value

---

app/javascript/components/admin/AdminTable.js
app/javascript/components/admin/AuditModal.js
app/javascript/components/analytics/widgets/GeographicSummary.js
app/javascript/components/assessment/AssessmentTable.js
app/javascript/components/enrollment/steps/Contact.js
app/javascript/components/enrollment/steps/Exposure.js
app/javascript/components/layout/Breadcrumb.js
app/javascript/components/layout/Header.js
app/javascript/components/patient/Patient.js
app/javascript/components/patient/PatientPage.js
app/javascript/components/patient/vaccines/VaccineTable.js
app/javascript/components/public_health/Import.js
app/javascript/components/public_health/PatientsTable.js
app/javascript/components/public_health/PublicHealthHeader.js
app/javascript/components/public_health/Workflow.js
app/javascript/components/public_health/actions/UpdateCaseStatus.js
app/javascript/components/public_health/custom_export/PatientsFilters.js
app/javascript/components/subject/household_actions/ApplyToHousehold.js
app/javascript/components/subject/household_actions/EnrollHouseholdMember.js
app/javascript/components/subject/household_actions/MoveToHousehold.js
app/javascript/components/subject/monitoring_actions/Jurisdiction.js
app/javascript/tests/patient/Patient.test.js
app/javascript/tests/subject/household_actions/ApplyToHousehold.test.js

Currently, Sara Alert has the ability to be hosted at a subpath. For example, it can be hosted at `www.xyz.com/subpath/saraalert/`. This is done by allowing the setting of a `BASE_PATH` on the backend. For normal operation, this will be the empty string `""`. 
The front-end should structure all queries (axios, href...etc) to include this `BASE_PATH`. However, in certain files, this was forgotten.
This pull request adds back `window.BASE_PATH` into all the places were it was missing. It also corrects some front-end tests to account for this.
**Submitter:**
@ : @hackrm 
@ : @sgober 
@ : @holmesie

Window.BASE_PATH fixes

---

app/jobs/send_assessments_job.rb
app/models/patient.rb
app/views/user_mailer/assessment_job_email.html.erb
performance/benchmarks/send_assessments_job_benchmark.rb
test/jobs/send_assessments_job_test.rb

Jira Ticket: SARAALERT-1281
1) Improve the performance of the `send_assessments_job`
2) Write a test file for the `send_assessments_job`
I ran 5 jobs in GitHub Actions for this PR to compare with the results from the `send_assessments_job_benchmark` in the 1.27.0 branch.
`send_assessments_job.rb`
- Made performance improvements to job (threading, find_in_batches, select specific fields)
- Now collects summary data for sent items, but still keeps all data for exceptions
`assessment_job_email.html.erb`
- Now expects summary data for the sent area
`send_assessments_job_test.rb`
- New test file for job
**Submitter:**
@Bialogs  :
@holmesie …

SARAALERT-1281 Assessments Job Performance

---

app/javascript/components/enrollment/steps/Address.js
app/javascript/components/enrollment/steps/Identification.js

This fixes the long existing bug of how sometimes the DOB does not save.  See below for detailed steps on how to recreate this bug.
1. Open up any monitoree
2. Click the edit link for the identification section
3. Edit the DOB and click next
4. DO NOT CLICK FINISH
5. Notice that the DOB is updated to what you changed it to on the review page
6. From the review page, click the edit address link
7. Update the home address (one field is fine)
8. Click the "Copy from Home Address" button
9. Click Next
10. Notice that the DOB has reverted to the original DOB, not the one you changed it to
There were two piece to this fix, one in the Identification part of the carousel and one in the Address part
1. `Identification.js` was not calling `props.setEnrollmentState` when the DOB was updated, thus …

DOB does not save bugfix

---

app/javascript/components/admin/AdminTable.js

Add a user on the admin panel then click the export all users button (without refreshing the page).  The exported csv does not include the user you just added
Update the allUsersCount stored when a user is added

update allUsersCount when a user is added

---

app/models/patient.rb

Before we were running `preferred_contact_method&.downcase` on every `if` statement in `Patient#send_assessment`. We really only need to be running this operation once and evidently it gives us a small performance improvement when running the `SendAssessmentsJob`.
`patient.rb`
- In `Patient#send_assessment` set `preferred_contact_method&.downcase` to a local variable and use that variable in each `if` statment.
**Submitter:**
@ :
@ :
@ :

SA-NONE: Send assessment downcase

---

test/system/roles/enroller/enrollment/form.rb
test/system/roles/enroller/enrollment/form_validator.rb

Jira Ticket: [SARAALERT-562](https://github.com/SaraAlert/SaraAlert/pull/747)
This intermittent test failure was introduced in [SARAALERT-562](https://github.com/SaraAlert/SaraAlert/pull/747)
**Submitter:**
@holmesie  :
@ :
@ :

Fix intermittent enroller system test failure caused by enrollment page transition delay

---

app/javascript/components/enrollment/steps/Exposure.js
app/javascript/components/patient/Patient.js
app/javascript/components/public_health/PatientsTable.js
app/lib/import_export_constants.rb
test/system/roles/enroller/enroller_enrollment_test.rb
test/system/roles/enroller/enrollment/form_validator.rb

Jira Ticket: SARAALERT-562
This PR temporarily reverts the changes introduced in 562 for adding first positive lab to enrollment
**Submitter:**
@tstrass :
@holmesie :
@ :

Temporarily revert first positive lab changes

---

app/javascript/components/public_health/query/AdvancedFilter.js
app/javascript/tests/public_health/query/AdvancedFilter.test.js

Jira Ticket: [SARAALERT-1338](https://tracker.codev.mitre.org/browse/SARAALERT-1338)
When you want to create multiple filters and save them, the name you used to save the previous filter seems to be automatically populated when you try to save the next one. 
1. Create and save an advanced filter with a name
2. Click the "Apply" button
3. In the dropdown, click the new filter button
4. Click the "Save" button
5. Notice the name modal is pre-filled with the name of the last advanced filter
When the new filter button is clicked, insure filterName is cleared
- When the new filter button is clicked, clear filterName
- …

SARAALERT-1338: Filter name modal clearing bug

---

Gemfile
Gemfile.lock
app/controllers/assessments_controller.rb
app/jobs/consume_assessments_job.rb
app/jobs/produce_assessment_job.rb
app/mailers/patient_mailer.rb
app/mailers/twilio_sender.rb
app/models/history.rb
app/models/patient.rb
config/twilio/assessment_studio_flow.json
test/jobs/consume_assessments_job_test.rb
test/mailers/patient_mailer_test.rb
test/mailers/twilio_sender_test.rb
test/test_helpers/consume_assessments_job_test_helper.rb
test/vcr_cassettes/get_number_from_sms_assessment_execution.yml
test/vcr_cassettes/get_numbers_from_inbound_sms_trigger_execution.yml
test/vcr_cassettes/get_numbers_from_inbound_voice_trigger_execution.yml
test/vcr_cassettes/get_numbers_from_single_message_execution.yml
test/vcr_cassettes/get_numbers_from_voice_assessment_execution.yml
test/vcr_setup.rb

Jira Ticket: [SARAALERT-1121 ](https://tracker.codev.mitre.org/browse/SARAALERT-1121)[SARAALERT-1156](https://tracker.codev.mitre.org/browse/SARAALERT-1156)
This PR enables detailed history items in the event of errored communications through Twilio.
1. All SMS messages will now be dispatched through the Studio Flow.
2. When any SMS (or call) fails to send in the studio flow we will post back to our report endpoint with an included `error_code` parameter.
3. When the consume assessments job sees that an error coded was included, history items will be added to the appropriate monitorees indicating how/why the communication failed.
4. As part of this PR SARAALERT-1121 is addressed which ensures that both the HoH and monitoree get error/success history item messages regardless of if the HoH …

SARAALERT-1121, SARAALERT-1156: Twilio Error Handling

---

app/javascript/components/public_health/PublicHealthHeader.js

Jira Ticket: [SARAALERT-1294](https://tracker.codev.mitre.org/browse/SARAALERT-1294)
Update the icon for isolation. 
**Submitter:**
@sgober  :
@DPC15038  :
@holmesie   :

SARAALERT-1294: new isolation icon

---

lib/tasks/demo.rake

Jira Ticket: [SARAALERT-1354](https://tracker.codev.mitre.org/browse/SARAALERT-1354)
Some monitorees in the demo data generated through the `populate` script were being erroneously marked as HOHs. This PR fixes the issue in the demo script (root cause was a timezone issue) to ensure generated monitorees won't get into this state when generated. 
While on the `v1.28.0` branch, complete the following:
1. If you haven't run the populate script to poplate your local database, do so: `bundle exec rake demo:populate`
2. In MySQL Workbench or through the rails console, query for the moniotrees who are in the erroneous HOH state:
If using MySQL Workbench:
```
SELECT id, first_name, last_name
FROM disease_trakker_development.patients
WHERE responder_id = id AND head_of_household = 1 AND id in …
```

SARAALERT-1354: Resolve HOH issue when populating demo data

---

app/controllers/assessments_controller.rb
app/controllers/patients_controller.rb
app/helpers/assessment_query_helper.rb
app/javascript/components/admin/AdminTable.js
app/javascript/components/admin/AuditModal.js
app/javascript/components/layout/CustomTable.js
app/javascript/components/patient/assessment/AssessmentTable.js
app/javascript/components/patient/household/actions/ApplyToHousehold.js
app/javascript/components/patient/household/actions/MoveToHousehold.js
app/javascript/components/patient/vaccines/VaccineTable.js
app/javascript/components/public_health/PatientsTable.js
app/models/assessment.rb
performance/benchmarks/micro_benchmarks.rb
test/fixtures/conditions.yml
test/fixtures/patients.yml
test/fixtures/users.yml
test/models/assessment_test.rb
test/system/lib/system_test_utils.rb
test/system/roles/public_health/dashboard/dashboard.rb
test/system/roles/public_health/patient_page/patient_page.rb
test/system/roles/public_health/patient_page/patient_page_verifier.rb
test/system/roles/public_health/patient_page/reports.rb
test/system/roles/public_health/patient_page/reports_verifier.rb
test/system/roles/public_health/public_health_patient_page_test.rb
test/system/roles/public_health/public_health_test_helper.rb
test/system/workflow/workflow_test.rb

Jira Ticket: [SARAALERT-1421](https://tracker.codev.mitre.org/browse/SARAALERT-1421)
Currently, hundreds of queries (although cached, still slower) are being executed to load the assessments table, which is responsible for a noticeable amount of the loading time of the patient page. This is due to the fact that each symptom of each assessment is being queried separately.
The changes in this PR aim to improve the performance of this by querying these assessments and symptoms in bulk rather than individually
**Submitter:**
@jkufro  :
@mayerm94  :
@holmesie  :

SARAALERT-1421: Improve loading of assessments table on patient page

---

app/controllers/analytics_controller.rb
app/javascript/components/analytics/widgets/GeographicSummary.js
app/jobs/cache_analytics_job.rb
app/views/analytics/index.html.erb
config/routes.rb
lib/tasks/demo.rake

Jira Ticket: [SARAALERT-1440](https://tracker.codev.mitre.org/browse/SARAALERT-1440)
Currently the analytics page takes a while to complete its initial page load because it takes a while to query and load all the `monitoree_maps` data, which prevents anything on the page from loading until it's completed. This PR includes changes to dynamically load `monitoree_maps` data once the analytics component is mounted that way the initial load time is way faster as well as slight improvements to query `monitoree_maps` more efficiently.
NOTE: This PR is currently targeted towards the `demo_script_households` branch because it includes those changes to `demo.rake`, once that PR is merged, this branch will be targeted to `1.28.0`
Please list important files (meaning substantial or integral to the …

SARAALERT-1440: Improve analytics page initial loading time

---

app/controllers/user_filters_controller.rb
app/helpers/patient_query_helper.rb
app/javascript/components/public_health/query/AdvancedFilter.js
app/javascript/data/advancedFilterOptions.js
app/javascript/packs/stylesheets/advanced_filter.scss
app/javascript/packs/stylesheets/bootstrap.scss
app/javascript/tests/mocks/mockFilters.js
app/javascript/tests/public_health/query/AdvancedFilter.test.js
test/helpers/patient_query_helper_test.rb

Jira Ticket: [SARAALERT-1055](https://tracker.codev.mitre.org/browse/SARAALERT-1055)
Adds support for filtering monitorees by different lab result fields (result, test type, collection date and report date).  This included adding support for a new advanced filter type, "multi-select".  See the JIRA ticket for mockups for the type.  The multi type is intended to support multiple fields using an "and".  It does not allow for the same field to be selected twice within the multi filter.
When testing, here is something to note.  When combining filters within one multi lab statement, a monitoree will be returned IF they have one lab that meets all of the fields.  For example...
This will return monitorees that have at least one positive PCR test
While this will return monitorees that have at …

SARAALERT-1055: Advanced Filter Lab Results

---

app/controllers/assessments_controller.rb
app/lib/import_export.rb
test/controllers/assessments_controller_test.rb
test/fixtures/conditions.yml
test/fixtures/symptoms.yml
test/system/roles/public_health/patient_page/reports_verifier.rb

This bug was initially discovered as an export bug caused by some symptoms having `nil` labels, which was a result of some recent assessment changes
Before checking out this branch:
1) edit any assessment
2) query the assessments' symptoms and notice that the labels are missing
The [assessment performance PR](https://github.com/SaraAlert/SaraAlert/pull/806) changed what was being passed back to the controller upon assessment update (no longer includes the label) which was being relied on. This PR changes the way assessments are updated so that the symptom label/type for the update come from the original assessment and symptom from the threshold condition.
Also added `nil` checks to the symptom query for exports
**Submitter:**
@tstrass :
@holmesie :
@mayerm94 :

BUGFIX: Export and assessments symptom label bug

---

app/javascript/components/patient/Patient.js
app/lib/import_export.rb
app/lib/import_export_constants.rb
app/lib/languages.rb
test/lib/languages_test.rb
test/system/roles/public_health/dashboard/export_verifier.rb

This PR translates the three-letter language codes on the Patient into Display names for Export.

SARAALERT-1344: Converts language back to display code for export

---

lib/tasks/demo.rake

This is just a small PR that adds a rake task (for development env) to clear out sidekiq queues

SARAALERT-None: Add QoL rake task to clear sidekiq in development

---

app/controllers/application_api_controller.rb
app/controllers/fhir/r4/api_controller.rb

Jira Ticket: [SARAALERT-1432](https://tracker.codev.mitre.org/browse/SARAALERT-1432)
This PR refactors how we handle checking scopes in the API so that we don't explicitly list out all the scopes every single time we authorize. Since certain scopes are always grouped together (for example, we don't have any cases where it would make sense for someone to be allowed only the `system/Patient.read` scope but not the `system/Patient.*` scope), this PR groups those scopes together and uses those groupings when authorizing. This came out of this [comment](https://github.com/SaraAlert/SaraAlert/pull/797#discussion_r609973264) by @dubem7.  
- Refactor listing of scopes in `doorkeeper_authorize!` calls.
**Submitter:**
@dubem7 
@ashankland 
@tstrass

SARAALERT-1432: Refactor API Scopes

---

app/controllers/patients_controller.rb
app/javascript/components/enrollment/Enrollment.js
app/javascript/components/enrollment/steps/Review.js

Jira Ticket: [SARAALERT-1357](https://tracker.codev.mitre.org/browse/SARAALERT-1357)
If two users are editing a record at once, and one of them opens the model to add a dependent to the record, and another one adds that record as a dependent, then the first user may be able to enroll a dependent on a dependent record. In addition, this fixes a bug where the "Finish and Add a Household Member" button is displayed for a dependent when it should not be.
There are two ways to replicate this bug, one for a HoH and one for an individual
HoH:
1. Open up two tabs of Sara Alert with the same HoH details displayed in each
2. In one tab, open up the Change HoH modal.  Select a dependent but **DO NOT SUBMIT**
3. In the other tab, click the "Enroll Household Member" button
4. Step through the …

SARAALERT-1357: Prevent users from adding dependents to a dependent record

---

app/jobs/export_job.rb
app/lib/import_export.rb
app/views/user_mailer/download_email.html.erb
test/mailers/user_mailer_test.rb

Jira Ticket: SARAALERT-1186
If there are no valid patients for an export (such as with purge eligible), the user will be confused because the export starts and finishes successfully but no email is sent letting the user know that nothing was actually available to export.
If there are valid patients for an export, but all selected patients do not have any data (such as a group of patients that all do not have lab results) and the user requests that only lab results be exported, they will get an email notifying them that nothing was available to export.
This PR will send an email notifying users that the export did not have any patients available.
Please list important files (meaning substantial or integral to the PR) along with a list of the general changes that should be highlighted for …

SARAALERT-1186: Notify a user of an export that had no patients matching export criteria

---

app/models/patient.rb
test/models/patient_test.rb

Jira Ticket: SARAALERT-1250
This is the second PR in a series of PRs that seeks to bring the `better_reminder_eligible` scope checks into `reminder-eligible` one step at a time. This PR incorporates the `reminder_not_sent_recently` scope into the `reminder_eligble` scope.
Note that there is a slight functionality change between `reminder_not_sent_recently` and the previous check that just assumed that a reminder sent < 12 hours ago is too recent. The `reminder_not_sent_recently` scope uses the patient's local time and `reporting_period_minutes` to determine if a reminder is too recent. For example, if the `reporting_period_minutes` is 1 day, then the scope will check that the patient has not received a reminder today in their local time.
This is not expected to have a significant …

SARAALERT-1250: Reminder eligible incorporation pt.2

---

app/jobs/cache_analytics_job.rb

Jira Ticket: SARAALERT-1448
This ticket filters out any values in the Analytics where `potential_exposure_country` is `''`. Previously, only `nil` values were filtered out.

1448-filters out the empty string from the country of exposure analytis

---

app/javascript/components/admin/AdminTable.js
app/javascript/components/admin/AuditModal.js
app/javascript/components/admin/UserModal.js
app/javascript/components/analytics/widgets/Demographics.js
app/javascript/components/patient/close_contact/CloseContact.js
app/javascript/components/patient/vaccines/VaccineModal.js
app/javascript/packs/stylesheets/bootstrap.scss
app/javascript/packs/stylesheets/layout.scss
app/models/user.rb
app/views/patients/show.html.erb

Jira Ticket: SARAALERT-1438
This Pull Request does 4 main things:
1. Tracks any changes to the Notes field in the Admin Page and displays them in the Audit Modal
2. Combines some `word-wrap` CSS that had been duplicated.
3. Fixes an issue with too many `<tbody>`s in the Analytics
4. Makes the length and syntax of notes constant (the VaccineModal was doing it slightly different)
Number 1 is the only big thing. Fixes 2 through 4 are just small tweaks.
`app/javascript/components/admin/AdminTable.js`
- Adds the back-end for the Notes Auditing
`app/javascript/components/admin/AuditModal.js`
- Adds front-end formatting for the Notes Auditing
`app/javascript/components/admin/UserModal.js` and `app/javascript/components/patient/close_contact/CloseContact.js`
- Formats Max Notes Length in similar …

SARAALERT-1438: Adds 'Notes' to the Admin Panel Audit Modal

---

app/javascript/components/analytics/widgets/MonitoreeFlow.js
app/javascript/tests/analytics/widgets/MonitoreeFlow.test.js
app/jobs/cache_analytics_job.rb

It was realized this didn't make sense in the table since the data
pertains to active monitorees only and not purged ones, while the
rest of the data in that table includes purged.
This is a temporary measure, and the workflow move data will be
included in the future elsewhere on the analytics page. For this
reason, the migration was left in.
Here is a [full (reverse) diff](https://github.com/SaraAlert/SaraAlert/compare/revert-374) of the changes of the changes that went in as a part of 374, for which the changes in this PR are a subset.

Remove workflow change data from monitoree flow table in analytics

---

config/environments/development.rb
config/environments/production.rb
config/environments/test.rb

set activestorage route prefix to /files  to avoid routing to the assessment container

set activestorage route prefix to /files 

---

config/locales/spa-pr.yml
config/locales/spa.yml

There was a typo in the translations. An extra quote had been added to the thank you messages for the Spanish translations. 
This PR ONLY fixes the translations themselves. A test-linting PR will go up later today that addresses the incorrect quotes in the test files.

Hotfix: fixed typo in translations

---

db/migrate/20210414203512_convert_primary_language_to_iso_code.rb

This PR fixes an incorrect translation from `eng/spa` to `eng/por`.

changed translation from spanish to portuguese

---

performance/benchmark.rb
performance/benchmarks/micro_benchmarks.rb

Description
These changes allow benchmarks to specify the mode of measurement (total, user, system, real). The default is still total, but with benchmarks that are heavily or completely measuring SQL queries it is more useful to measure real time since the time spent waiting for queries is not included in total time.
**Submitter:**
@Bialogs  :
@holmesie  :
@tstrass  :

Benchmark modes

---

app/javascript/components/enrollment/steps/Address.js
app/models/patient.rb
app/models/required_address_validator.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-1386](https://tracker.codev.mitre.org/browse/SARAALERT-1386)
This PR tweaks the address validation in the UI so that as long as one tab (USA or foreign) is valid, the user may proceed (even if it isn't the tab currently being viewed). Then the PR also updates the address validation in the API so that it matches this behavior.
I don't think the way it worked before was so much a bug, but here is how you could replicate it on 1.30.0:
1. Entry in an address with all required fields in the "Home Address Within USA" tab, then switch to the "Home Address Outside USA (Foreign)" tab.
2. Click "Next", and you will see errors about required elements on the "Home Address Outside USA (Foreign)" tab. Reversing the order of the tabs, this works the same way.
On this branch, …

SARAALERT-1386: Fix address validation

---

performance/benchmarks/send_assessments_job_benchmark.rb

The only threshold that needed to be changed was the send assessments job benchmark.
`performance/benchmarks/send_assessments_job_benchmark.rb`
- The Timecop time should have been set to 1800 UTC like the scope's micro benchmark (I thought I changed this previously but it must have gotten lost somwhere)
- The failure threshold is now set to 310 seconds to accommodate the new (somewhat larger) performance DB
**Submitter:**
@holmesie  :
@tstrass  :
@Bialogs :

Updated benchmarking thresholds

---

app/javascript/components/layout/CustomTable.js
app/javascript/components/patient/assessment/actions/ExtendedIsolation.js
app/javascript/components/patient/assessment/actions/LastDateExposure.js
app/javascript/components/patient/assessment/actions/SymptomOnset.js
app/javascript/packs/stylesheets/bootstrap.scss
app/javascript/packs/stylesheets/custom_table.scss

Jira Ticket: SARAALERT-[1053](https://tracker.codev.mitre.org/browse/SARAALERT-1053)
Remove last date of exposure and continuous exposure from a monitoree's profile while in the isolation workflow.
Exposure
Isolation
Look at a monitoree in both the isolation and exposure workflow. On 1.30 they both have last date of exposure and continuous exposure.
Look at a monitoree in both the isolation and exposure workflow. On this branch they have last date of exposure and continuous exposure in the exposure workflow and neither in the isolation workflow.
Added a check if the patient was in isolation before displaying those fields.
**Submitter:**
@tstrass :
@sgober  :
@DPC15038  :

SARAALERT-1053: Hide fields in isolation

---

app/helpers/patient_query_helper.rb
app/javascript/components/public_health/query/AdvancedFilter.js
app/javascript/data/advancedFilterOptions.js
test/helpers/patient_query_helper_test.rb

Jira Ticket: [SARAALERT-1229](https://tracker.codev.mitre.org/browse/SARAALERT-1229)
Allow users to filter records by vaccine history using the following fields: Administration Date, Dose Number, Product Name, and Vaccine Group
- Added support for filtering by multiple vaccine fields to the backend (these are very similar to the ones for the lab multi advanced filter)
`patient_query_helper_test.rb`
- Added backend query tests for the multi vaccine advanced filter (again, very similar to how the lab multi advanced filter is done)
`advancedFilterOptions.js`
- Added vaccine filter option to list of advanced …

SARAALERT-1229: Vaccine Advanced Filter

---

app/javascript/components/patient/assessment/Assessment.js
app/javascript/components/patient/assessment/actions/AddAssessmentNote.js
app/javascript/components/patient/assessment/actions/ClearAssessments.js
app/javascript/components/patient/assessment/actions/ClearSingleAssessment.js
app/javascript/components/patient/assessment/actions/ContactAttempt.js
app/javascript/components/patient/assessment/actions/ExtendedIsolation.js
app/javascript/components/patient/assessment/actions/LastDateExposure.js
app/javascript/components/patient/assessment/actions/PauseNotifications.js
app/javascript/components/patient/assessment/actions/SymptomOnset.js
app/javascript/components/patient/close_contact/CloseContact.js
app/javascript/components/patient/history/History.js
app/javascript/components/patient/history/HistoryList.js
app/javascript/components/patient/laboratory/Laboratory.js
app/javascript/components/patient/monitoring_actions/AssignedUser.js
app/javascript/components/patient/monitoring_actions/CaseStatus.js
app/javascript/components/patient/monitoring_actions/ExposureRiskAssessment.js
app/javascript/components/patient/monitoring_actions/Jurisdiction.js
app/javascript/components/patient/monitoring_actions/MonitoringPlan.js
app/javascript/components/patient/monitoring_actions/MonitoringStatus.js
app/javascript/components/patient/monitoring_actions/PublicHealthAction.js

`location.reload(true)` is deprecated because the `forceGet` flag is no longer supported.  I replaced all instances of it in the app with `location.reload()`.  See this thread for more info: https://github.com/Microsoft/TypeScript/issues/28898
**Submitter:**
@holmesie :
@DPC15038 :

Removed deprecated flag in location.reload

---

app/javascript/components/enrollment/Enrollment.js

Jira Ticket: SARAALERT-1451
This PR scrolls to the top of the page in Enrollment when clicking `next()` or `previous()`
This isnt a bug, but if you scroll to the bottom of the window during enrollment and click next, the next card will render at the bottom. This is a feature of the browser itself. This PR has the browser scroll back to the top when clicking next.
`app/javascript/components/enrollment/Enrollment.js`
- Scrolls to the top when changing cards in the carousel
**Submitter:**
@sgober :
@timwongj :
@holmesie   :

SARAALERT-1451: Scroll to Top of Enrollment

---

app/javascript/packs/stylesheets/layout.scss

Jira Ticket: SARAALERT-1427
There is a bug in Safari, where it will render the width of certain dropdowns in the Enrollment at an incorrect width. It looks like the tooltip div is defaulting to the content width during initial rendering, which causes these dropdowns to be wider than the content of the selects. DOM repaint forced by the menu div shown when you open the Workflow dropdown causes it to recompute the width of the tooltip divs.
The Old, Incorrect, Behavior:
The New, Correct Behavior:
`/stylesheets/layout.scss`
- Fixes safari-tooltip width issue
**Submitter:**
@timwongj  :
@sgober   :
@jkufro  :

SARAALERT-1427: Fixes tooltip width bug in safari

---

app/controllers/close_contacts_controller.rb
app/javascript/components/patient/close_contact/CloseContact.js
app/javascript/components/util/DeleteDialog.js
app/javascript/packs/stylesheets/layout.scss
app/javascript/tests/patient/close_contact/CloseContact.test.js
config/routes.rb
test/controllers/close_contacts_controller_test.rb

Jira Ticket: [SARAALERT-767](https://tracker.codev.mitre.org/browse/SARAALERT-767)
Adds the ability for users to delete close contact records from patients. 
app/controllers/close_contacts_controller.rb
- adds the delete method, with some very basic authentication. 
app/javascript/components/patient/close_contact/CloseContact.js
- adds front-end functionality to delete close contacts from the patient view, with a warning prompt. 
app/config/routes.rb
- adds a route for the delete method in the controller so the front-end can interact with the db. 
**Submitter:**
@sgober :
@timwongj :
@tstrass  :

SARAALERT-767: Ability to delete/retire close contacts from the list

---

app/controllers/api/api_export_controller.rb
app/controllers/application_api_controller.rb

Jira Ticket: [SARAALERT-1471](https://tracker.codev.mitre.org/browse/SARAALERT-1471)
When an unauthorized application made a request to the `nbs/patient` endpoint, we were incorrectly responding with a 500 error, since we were double `respond_to`ing. One `respond_to` came from `doorkeeper_authorize!`, and then we would also run `status_unauthorized`, causing a server error. This PR fixes that bug.
Make a request to `nbs/patients` without any authorization token. You should get a 500 response, instead of the expected 401.
To fix this, we now raise a `ClientError` whenever there is some sort of error status that is using `respond_to`, this halts execution, and the error is rescued (but nothing is done with it, since the status is already set).
Please list important files (meaning …

SARAALERT-1471: Fix bug with unauthorized request to PHDC export endpoint

---

app/controllers/histories_controller.rb

Jira Ticket: [SARAALERT-832](https://tracker.codev.mitre.org/browse/SARAALERT-832)
Ensure history delete modifies the updated_at time (update_all does not do this on it's own)

History Delete update_at bugfix

---

docs/api/api-coming-soon.md

Updates the docs for 1.30.0. Since the two major features that could have went to 1.30.0 are pushed to 1.31.0, this only required updating the "Coming Soon".
- Changed to 1.31.0
N/A

SARAALERT-NONE: 1.30.0 API Documentation Updates

---

test/system/roles/enroller/enrollment/form.rb

On `master`, there is a system test failing in the workflow tests. See [here](https://github.com/SaraAlert/SaraAlert/runs/2666779009) for a log of the error. This PR should fix that error.
I'm unable to replicate the bug locally, and the failure is intermittent on GitHub actions, but happens often enough to be an issue. It seems to be that the test fails when this [line](https://github.com/SaraAlert/SaraAlert/blob/e348b8f2d893774781803d79c0d9f78edf5ad8ed/test/system/roles/enroller/enrollment/form.rb#L23) fails to find the relevant section to expand. This seems to happen because the line above clicks the `details-expander-link` button, but in this case that section is already expanded. So the section is actually collapsed, and the section we want to edit cannot be found. …

SARAALERT-NONE: Fix failing workflow system test

---

app/javascript/components/patient/close_contact/CloseContact.js

Renames an incorrect method to prevent the Close Contact Modal from error-ing out.

fixes cc contact_attempt method

---

app/helpers/validation_helper.rb
app/jobs/close_patients_job.rb
app/models/patient.rb
performance/benchmarks/close_patients_job_benchmark.rb
performance/benchmarks/micro_benchmarks.rb
test/jobs/close_patients_job_test.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-1385](https://tracker.codev.mitre.org/browse/SARAALERT-1385)
Patient records in the non-reporting line list in the exposure workflow that have not been updated for 30+ days can now be automatically closed by the close_patients_job.
Added helper scope for :no_recent_activity
Added helper scope as or clause in close_eligible
Added new valid system-set monitoring reason 'No record activity for 30 days (system)'
Added logic for new monitoring reason in close_patients_job
Added relevant tests for new functionality
`app/helpers/validation_helper.rb`
- Added new valid option `No record activity for 30 days (system)`
- …

SARAALERT-1385 Close inactive patient records automatically

---

app/lib/import_export.rb

Jira Ticket: [SARAALERT-###](https://tracker.codev.mitre.org/browse/SARAALERT-###)
The goal of this PR is to address the failures due to "MySQL server has gone away" errors on L165 of import_export.
L165 of import export was causing failures due to "MySQL server has gone away" errors. This can be replicated by attempting to export a large number of patients at once (I'm testing with the 500k database).
I tested this solution on the 500k database and the change appears to be functionally the same as what we had before but does not encounter the MySQL server has gone away error.
I was able to successfully export all 500k patients from the 500k performance datbase (took about 2300 seconds / 40 minutes). The excel file is 500MB and takes a few minutes to actually open (I'm not sure of the …

Alter symptom_names_and_labels queries to avoid MySQL has gone away errors

---

app/jobs/purge_job.rb
app/mailers/user_mailer.rb
app/views/user_mailer/_purge_job_email_failure.html.erb
app/views/user_mailer/_purge_job_email_success.html.erb
app/views/user_mailer/purge_job_email.html.erb
config/sara/sara.yml
test/jobs/purge_job_test.rb
test/mailers/user_mailer_test.rb

Jira Ticket: SARAALERT-1449
Updates the PurgeJob to send emails in batches.
Includes additional diagnostic info.
Nothing purged / no errors
With data
Send an email to our email server in excess of 170k lines and receive an STMPError.
Send multiple emails so we do not hit this upper limit.
`purge_job.rb`
- Batching logic
`purge_job_test.rb`
- Tests for batching
`sara.yml`
- Add batch size config 
`purge_job_email.html.erb`
- Logic updates
- Break out into partial for purged/not_purged
- Include new job information
- Formatting improvements
`user_mailer_test.rb`
- Updated tests for different cases
**Submitter:**
@tstrass  :
@timwongj: …

SARAALERT-1449: Purge job diagnostic email

---

app/jobs/close_patients_job.rb
app/models/patient.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-1504](https://tracker.codev.mitre.org/browse/SARAALERT-1504)
This refactors the close patients job so that there isn't any additional logic added to setting monitoring reasons besides the scopes. This will help ensure that the logic in the job does not fall out of line with the logic in the scopes.
```ruby
patient = create(:patient,
last_date_of_exposure: 200.days.ago,
created_at: 150.days.ago)
patient.update(updated_at: 135.days.ago)
Patient.where(id: patient.id).exposure_asymptomatic.submitted_assessment_today.end_of_monitoring_period
Patient.where(id: patient.id).where(isolation: false).non_reporting.no_recent_activity
```
The solution is to remove all monitoring reason logic in the close job so that there is no chance it can fall out of line with the logic in …

Close job refactor

---

app/javascript/components/patient/monitoring_actions/CaseStatus.js
app/javascript/components/public_health/actions/UpdateCaseStatus.js
app/javascript/tests/patient/monitoring_actions/CaseStatus.test.js
app/javascript/tests/public_health/actions/UpdateCaseStatus.test.js

Jira Ticket: [SARAALERT-1407] Part 3
This PR removes the ability to update Reason for Closure for Monitorees in the Isolation Workflow via the Case Status Modal. Per User Feedback, it doesnt make sense to update the RoC via that modal in the Isolation workflow.
`app/javascript/components/public_health/actions/UpdateCaseStatus.js`
- Removes the ability to update RoC via the Case Status Modal for Isolation Monitorees.
**Submitter:**
@tstrass 
@hackrm 
@jkufro

Hotfix-SA-1407 Disabled Reasons in Isolation Workflow

---

app/controllers/public_health_controller.rb
app/helpers/patient_query_helper.rb
app/javascript/components/public_health/custom_export/PatientsFilters.js
app/javascript/tests/mocks/mockTabs.js
test/controllers/jurisdictions_controller_test.rb
test/controllers/public_health_controller_test.rb

Jira Ticket: [SARAALERT-448](https://tracker.codev.mitre.org/browse/SARAALERT-448)
[Slack context](https://mitrecorp.slack.com/archives/C01A6P94R9B/p1623953377090400?thread_ts=1623772268.020300&cid=C01A6P94R9B)
This is a follow on to #937. It was requested that the Transferred In and Transferred Out line lists should be removed from global custom export, since they are not included as tabs in the dashboard.
**Submitter:**
@holmesie:
@sgober:
@timwongj:

Remove transferred in/out from global export

---

app/javascript/components/patient/follow_up_flag/FollowUpFlag.js

Jira Ticket: [SARAALERT-928](https://tracker.codev.mitre.org/browse/SARAALERT-928)
The tooltip that is suppose to appear when a user hovers their mouse over the disabled "Clear Follow-up Flag" button was not working across all broswers. This PR addresses this issue so this tooltip now appears across all browsers.
1. While in Chrome or Safari ...
2. In the Dashboard view, select a monitoree who is not flagged for a bulk action.
3. In the Bulk Actions drop down select "Flag for Follow-up"
4. In the modal, notice that the "Clear Follow-up Flag" radio button is disabled. Hover your mouse over it and notice there is no tooltip that appears.
Wrapping the radio button in a `<span>` and associating the tooltip with the `<span>` instead of the `<Form.Check>` addressed the issue. …

Bug fix for SARAALERT-928: Clear Flag radio button tooltip

---

app/javascript/components/public_health/actions/UpdateCaseStatus.js

Jira Ticket: SARAALERT-1407 
For Monitorees in the Closed Line List, through the Bulk Action Case Status Modal, it is possible to update their `Reason for Closure` without also updating their Case Status. This is the only situation where it is possible to update `RoC` without also updating `Case Status`. When a monitoree is closed a History Item is created. It is in the format:
`User updated Monitoring Status from X to Y. Reason: REASON_FOR_CLOSURE, FREE_TEXT_NOTES_HERE.`
and no history item for Reason for Closure is created.
However, when updating Monitorees from the Closed Line list, if you only updated the Reason for Closure, you would get a history item that looks like:
`User changed Reason for Closure from "Meets criteria to shorten quarantine" to "Does not meet criteria for …

SARAALERT-1407: Update History Logic

---

.github/workflows/performance.yml
.gitignore
Gemfile
Gemfile.lock
performance/aggregate_benchmark_results.rb
performance/benchmark.rb
performance/benchmarks/output/.gitignore
performance/collect_benchmark_results.rb

Jira Ticket: [SARAALERT-###](https://tracker.codev.mitre.org/browse/SARAALERT-###)
**Something strange seems to have happened where this [original PR was merged](https://github.com/SaraAlert/SaraAlert/pull/889), but none of the changes actually are present in 1.32.0. I have just rebased the branch against the latest 1.32.0 and made this PR.**
For performance benchmarks this PR will make it so that we now generate JSON describing test results and save them to artifacts. This PR also includes two scripts: one that pulls down and unpacks all relevant artifacts, and another that aggregates all of the data into an excel workbook.
To test the scripts, you will need to create a GitHub access token that has "workflow" permissions and set `export PERSONAL_TOKEN='<token value>'`.
Please list …

SARAALERT-NONE Benchmark artifacts (REDO)

---

app/javascript/data/advancedFilterOptions.js

Jira Ticket: [SARAALERT-928](https://tracker.codev.mitre.org/browse/SARAALERT-928)
The "Refused Active Monitoring" flag reason was not included in the Advanced Filter options by mistake. This PR adds it to the list of filter options.
`app/javascript/data/advancedFilterOptions.js`
- Added "Refused Active Monitoring" to the flag filter options
**Submitter:**
@ :
@ :
@ :

Update to SARAALERT-928: Adding flag reason to filter that was missed

---

app/javascript/components/enrollment/steps/Contact.js
app/javascript/components/enrollment/steps/Identification.js
app/javascript/components/patient/Patient.js
app/javascript/packs/stylesheets/layout.scss
app/javascript/tests/patient/Patient.test.js

JIRA: [SARAALERT-1517](https://tracker.codev.mitre.org/browse/SARAALERT-1517)
Noticed a while back that the blocked sms tag made the enrollment contact window pretty screwy.  This just fixes the styling related to the blocked SMS badge.
Be sure to test with and without a blocked number in the enrollment window, and use all different screen sizes.
To block a number, run `BlockedNumber.create(phone_number: '+15555550153')` in the rails console with the relevant number
**Enrollment with no blocked number:**
Before:
After:
**Enrollment with blocked number:**
Before:
After:
**Monitoree details contact info (not much different):**
Before:
After:
Please list important files (meaning substantial or integral to the PR) along with a list of the general changes that should be highlighted for …

SARAALERT-1517: Cleaned up UI for blocked sms

---

config/newrelic.yml

Increases the remembered/visible backtraces by NewRelic from 50 to 125
https://docs.newrelic.com/docs/agents/ruby-agent/configuration/ruby-agent-configuration/#error_collector-max_backtrace_frames

Increase the amount of backtraces remembered by NewRelic

---

app/jobs/cache_analytics_job.rb
app/models/patient.rb
test/controllers/public_health_controller_test.rb

This PR was created as a follow up on this thread: https://github.com/SaraAlert/SaraAlert/pull/937#discussion_r653070079
The `monitoring_active` scope was created for analytics a long time ago but I just noticed that it doesn't include the `where(purged: false)` condition. Although `patients` should never be in a state where monitoring is `true` and purged is `true`, it's better to include in the queries anyways. Adding that condition to the scope would make it the same as the `monitoring_open` scope so I just replaced the `monitoring_active` scope with the `monitoring_open` scope.
`app/jobs/cache_analytics_job.rb`
- …

Replace monitoring active scope with monitoring open scope

---

app/helpers/patient_details_helper.rb
app/lib/import_export_constants.rb

Jira Ticket: [SARAALERT-448](https://tracker.codev.mitre.org/browse/SARAALERT-448)
[Slack context](https://mitrecorp.slack.com/archives/C01A6P94R9B/p1624474474040600)
This is another follow-on to #937, #945, #960.
This just changes the order of the columns in the line list CSV export. I inserted the new columns, Reporter ID and Workflow, into the order of columns to mimic the order they exist in the dashboard. It was requested that they instead are tacked onto the end (columns V and W).
`import_export_constants.rb`
- Changed the column order
**Submitter:**
- [] If UI changes have been made, Chrome Dev Tools Lighthouse accessibility test has been executed to ensure no 508 issues were introduced.
@holmesie:

SARAALERT-448: Change order of new columns in line list CSV export

---

app/javascript/components/patient/laboratory/LaboratoryModal.js
app/models/concerns/laboratory_date_validator.rb
app/models/laboratory.rb
test/models/laboratory_test.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-1355](https://tracker.codev.mitre.org/browse/SARAALERT-1355)
This PR adds validation for lab results to the frontend making it so that a user cannot create a lab result if it does not have at least a specimen_date or report date AND a result. This also expands upon some of the existing backend validations.
Add lab results with no fields populated.
Try to add lab results without the required fields, see that creation is blocked.
**Submitter:**
@Bialogs  :
@tstrass:
@ :

SARAALERT-1355 lab validation

---

app/javascript/data/advancedFilterOptions.js

This PR modifies some text for the ineligible-for-recovery tool-tip text in the advanced filter.

Hotfix:  Corrects the text for the ineligible-recovery advanced filter tooltip

---

app/javascript/components/public_health/actions/UpdateAssignedUser.js

Jira Ticket: [SARAALERT-1519](https://tracker.codev.mitre.org/browse/SARAALERT-1519)
This PR adds the ability to to clear out the assigned user via the assigned user bulk action simply by making the field empty and submitting.
The reason this was not working before was that `assigned_user` was not making it into the `diff_state`, so the field would not be updated for the selected patients.
The fix is simply to also include `assigned_user` in the `diff_state` if the `assigned_user` field is blank in the bulk action form. I tested submitting blank assigned users multiple times for patients and the changed history item only appears once. …

SARAALERT-1519 Bulk clear assigned user

---

app/javascript/components/patient/assessment/actions/MonitoringPeriod.js
app/javascript/tests/patient/assessment/actions/MonitoringPeriod.test.js
public/Sara Alert Import Format.xlsx

Jira Ticket: Follow-up on [SARAALERT-1436](https://tracker.codev.mitre.org/browse/SARAALERT-1436)
- display LDE in isolation
- set default cell of import guidance to A1 and default sheet to 1st sheet
**Submitter:**
@tstrass :
@holmesie :
@sgober :

FIX: display LDE in isolation and set default cell of import guidance to A1

---

app/javascript/components/layout/CustomTable.js
app/javascript/components/public_health/PatientsTable.js
app/javascript/packs/stylesheets/custom_table.scss

Jira Ticket: [SARAALERT-1006](https://tracker.codev.mitre.org/browse/SARAALERT-1006)
This Pull Request updates the styling for the Patients Table. It adds a better (and more obvious) hover color to the table. It also adds a custom class for selected rows, and a hover color for those rows that have been selected.
This PR also removes an incorret `id`s off each of the cells within each row of the Patients Table. The `id` on each row remains.
https://user-images.githubusercontent.com/17532163/122814770-a6ce3980-d2a2-11eb-8191-3cab8d9312f0.mov
`app/javascript/components/layout/CustomTable.js`
- Removes `id` from each cell in the Patients …

SARAALERT-1006: Patients Table Styling Update

---

app/controllers/fhir/r4/api_controller.rb
test/controllers/fhir/r4/immunization_test.rb
test/controllers/fhir/r4/observation_test.rb

Jira Ticket: [SARAALERT-1464](https://tracker.codev.mitre.org/browse/SARAALERT-1464)
This refactors the API controller to be a little neater and use a little less code. As it stands, this PR only removes about 40 lines of code, but I think it makes the `update` and `create` methods much more readable. Additionally, once #870 and #872 are accounted for in this PR, the difference in code will be more significant.
- Refactor the `apply_patch` method to also handle error throwing
- Add an `update_model_from_fhir` method which can be used for any non-Patient model to update it, given the original model, the contents of the update (as FHIR), and a method for converting from FHIR
- Add an `update_record` method which wraps the code for updating and saving a model, and …

SARAALERT-1464: Refactor API Controller

---

app/controllers/patients_controller.rb
app/controllers/public_health_controller.rb
app/helpers/patient_query_helper.rb
app/javascript/components/patient/household/actions/MoveToHousehold.js
test/controllers/patients_controller_test.rb
test/helpers/patient_query_helper_test.rb

Jira Ticket: [SARAALERT-1445](https://tracker.codev.mitre.org/browse/SARAALERT-1445)
If a monitoree is not part of a household, they can be enrolled in one by using the Move-To-Household modal. You are currently able to select the current Monitoree to be their own HoH.
For example, if you're on Monitoree Bob Smith, you can find Bob Smith in the list of Monitorees to assign as Bob Smith's HoH.
If you select Bob Smith to be his own HoH, the page refreshes and nothing changes, so there is no error in functionality, but the current monitoree should probably be filtered from the list.
`MoveToHousehold.js`
- Add `exclude_patient_id` to query …

SARAALERT-1445: Remove Current Monitoree from Move-To-Household Modal

---

app/controllers/patients_controller.rb

Jira Ticket: [SARAALERT-1541](https://tracker.codev.mitre.org/browse/SARAALERT-1541)
There was a bug where we were returning a 401 from the
patients/bulk_edit endpoint in the event that you bulk update a
household that has a purged member. The actual back end bulk update
wasn't broken, but the user got an erroneous and confusing error message
in the front end.
See [Slack context](https://mitrecorp.slack.com/archives/C01A6P94R9B/p1624979151021000) for more information and screenshots.
Find or manually create a scenario where an HoH has a household member that has been purged. Perform a bulk edit on that monitoree, with the apply to household toggle on.
Add a condition to ignore purged household members.
`patients_controller.rb`
- In `bulk_update` there's a check for households to identify …

SARAALERT-1541: Ignore purged in household bulk update

---

app/mailers/patient_mailer.rb
app/models/history.rb
app/models/patient.rb
test/mailers/patient_mailer_test.rb
test/models/history_test.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-1520](https://tracker.codev.mitre.org/browse/SARAALERT-1520)
Implement auto-close logic on Non-reporting line list in the Isolation workflow. Auto-close if it's been at least 30 days since last record update**. The reason for record closure should be: "No record activity for 30 days (system)".
**This does not include an update made to a record as a result of the system sending the monitoree a symptom report notification.
`patient_mailer.rb`
- Do not touch patient `updated_at` when sending daily report reminders
`history.rb`
- Do not touch patient `updated_at` when sending daily report reminders
`patient.rb`
- Do …

SARAALERT-1520: Isolation auto close

---

app/models/patient.rb

Clear up error noise in the `send_assessments_job` diagnostic emails.

Remove send_now from Patient#send_assessment

---

app/javascript/components/public_health/PublicHealthHeader.js

Jira Ticket: [SARAALERT-1420](https://tracker.codev.mitre.org/browse/SARAALERT-1420)
Ensure the "Upload" button is disabled in this situation so the user can't erroneously import a previously selected import file. Also verify if this behavior is an issue for the Epi-X import and resolve that if needed.
1. Select the Sara Alert import option
2. In the import modal, select the file to import
3. Close the modal
4. Select the Sara Alert import option again
5. Observe that while no file is attached, the "Upload" button is enabled, and if you attempt to click the "Upload" button, the previously attached file is imported.
Reset the state of the file selected for import when the modal is closed
Please list important files (meaning substantial or integral to the PR) along with a list of the …

SARAALERT-1420: Previously selected import file bugfix

---

app/controllers/patients_controller.rb

Jira Ticket: [SARAALERT-1554](https://tracker.codev.mitre.org/browse/SARAALERT-1554)
[Slack thread](https://mitrecorp.slack.com/archives/C01A6P94R9B/p1625848057089900) for context.
If you attempt to change an HoH in a household with purged monitoree(s), it would fail since the check for whether all the household members are viewable by the current user did not properly consider that monitorees could be purged.
This bug and fix are essentially the same as #973, just in a different place
Find or manually create a household with at least one purged household member. Attempt to change the head of household.
Add a filter on unpurged monitorees when checking if the household members are viewable.
Confirm you can replicate on master, and then confirm you cannot replicate on this branch. …

SARAALERT-1554: Fix bug with changing HoH

---

app/javascript/components/patient/Patient.js
app/javascript/tests/patient/Patient.test.js

Jira Ticket: [SARAALERT-1551](https://tracker.codev.mitre.org/browse/SARAALERT-1551)
"Head of Household" is capitalized elsewhere in the patient view but not in the notification that a patient is a minor. This capitalizes the phrase in the notification to ensure it remains consistent. 
Navigate to a patient record where the patient is a minor on another branch. The text should not capitalize "head of household" in the notification under the Contact Info Session.
Changes the text in patient.js to capitalize "Head of Household"
`app/javascript/components/patient/Patient.js`
**Submitter:**
@sgober  :
@tstrass:
@ :

SARAALERT-1551: capitalizes "Head of Household" in patient minor notification. 

---

app/controllers/patients_controller.rb
test/system/roles/public_health/dashboard/import_verifier.rb

Jira Ticket: [SARAALERT-1524](https://tracker.codev.mitre.org/browse/SARAALERT-1524)
Removes code within `patients_controller.rb` that will automatically set the monitored address to the provided home address upon enrollment.
* Before this patch is applied (such as on the `master` branch), create a monitoree with a home address and no monitored address. Observe how the home address is automatically copied into the monitored address _after_ enrollment is complete. 
Removes code within `patients_controller.rb` that will automatically set the monitored address to the provided home address upon enrollment.
`patients_controller.rb`
- Remove logic that checks if monitored address is blank and sets it based on home address
`import_verifier.rb`
- Remove logic that checks if monitored address is …

SARAALERT-1524: Remove Monitored Address Autofill on Enrollment

---

.dockerignore
config/sara/README.md
config/sara/performance_jurisdictions.yml
lib/tasks/admin.rake
lib/tasks/demo.rake
lib/tasks/performance.rake
performance/docker/build-push-1m-database-image.sh

Jira Ticket: SARAALERT-1351
Updates `admin.rake` and creates `performance.rake` with some features that bring the data more in-line with what production looks like in terms of amount and variety for performance testing.
`performance_jurisdictions.yml`
- Create a larger jurisdiction config. (7 jurisdictions -> 3852 jurisdictions) by including every county, three cities for each state and children for each city.
`admin.rake`
- Add toggle via PERFORMANCE environment variable to load `performance_jurisdictions.yml`
- Suppresses stdout when populating in CI to improve performance
`performance.rake`
- Add task that creates many more users (`:setup_performance_test_users`) based on the number of jurisdictions.
- - Add task that orchestrates creating of a 500k patient database with performance …

SARAALERT-1351: Demo rake updates

---

nginx.conf

Jira Ticket:  N/A
We have an `api/nbs/patient` endpoint that client applications can use to get data in the PHDC format. I noticed recently that the requests to this endpoint actually go to the enrollment container, since only requests that start with `/fhir` or `/oauth` go to the api container. This fixes that by now sending requests that start with `api/` to the api container.
**NOTE:** This is an area I'm not super familiar with, it seemed to me from following the previous examples that what I am doing should work, but I don't totally know how to locally test it. So if one of the reviewers does have things set up to easily test this, I would appreciate it, or since you reviewers know more about this than me, if one of you could point me in the right direction for how I should test …

SARAALERT-NONE: Fix nginx.conf for requests to /api

---

app/jobs/close_patients_job.rb
app/models/history.rb

Jira Ticket: [SARAALERT-1423](https://tracker.codev.mitre.org/browse/SARAALERT-1423)
Improves performance of close_patients_job by using batching and bulk import of histories.
This is a newer version of [this PR](https://github.com/SaraAlert/SaraAlert/pull/810) but does not bypass validations on patient records
[GitHub_Actions_Performance_Data_1626196344.xlsx](https://github.com/SaraAlert/SaraAlert/files/6810841/GitHub_Actions_Performance_Data_1626196344.xlsx)
`close_patients_job.rb`
- find patients in batches similar to send assessments job
- build all histories and import all at once for each batch
`history.rb`
- allow passing …

close_patients_job: batch groups and bulk import histories

---

app/javascript/components/public_health/PatientsTable.js
app/javascript/packs/stylesheets/dashboard.scss
app/javascript/tests/mocks/mockTabs.js
app/javascript/tests/public_health/PatientsTable.test.js
app/views/public_health/isolation.html.erb
test/system/roles/public_health/dashboard/dashboard_verifier.rb

Jira Ticket: [SARAALERT-1543](https://tracker.codev.mitre.org/browse/SARAALERT-1543)
The "Records Requiring Review" line list tab label in the Isolation workflow is fairly large and makes the line list tabs larger in width than they need to be. The tab name for this line list should be shortened when the tabs get into their 'responsive' state.
Before:
After:
`PatientsTable.js`
- Added support for an abbreviated tab name and the necessary classes to show/hide appropriately
`dashboard.scss`
- Added styling that dynamically hides/shows the normal label or the abbreviated label.  This is only added for the isolation dashboard right now.  If …

SARAALERT-1543: Abbreviated RRR (Records Requiring Review) tab on small screens

---

app/mailers/patient_mailer.rb
app/models/history.rb
test/mailers/patient_mailer_test.rb
test/models/history_test.rb

Jira Ticket: [SARAALERT-1188](https://tracker.codev.mitre.org/browse/SARAALERT-1188)
* Adds a history item if any error is raised during the execution of `PatientMailer#assessment_email`. 
* Logs the error to Sentry (Raven).
New History Item in Action:
`patient_mailer.rb`
- Do not bubble error up to diagnostic email.
- Comment logic
- Create History and log to Sentry
`history.rb`
- Create new `:assessment_email_error` History item
- Prevent `:assessment_email_error` from changing an associated model's `updated_at` attr
`patient_mailer_test.rb`
- Test to ensure error is passed to sentry gem
- Test to ensure history item is created …

SARAALERT-1188: Add history item when PatientMailer#assessment_email errors

---

app/models/patient.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-1561](https://tracker.codev.mitre.org/browse/SARAALERT-1561)
An edge case for the Exposure Non-Reporting line list auto-closure logic was identified now that auto-symptom assessment notifications will no longer count as a 'touch' on a monitoree. Monitorees who meet at least one of the following 2 conditions should not be eligible for auto-closure in the Non-Reporting Exposure line list:
-   CE is true
-   End of Monitoring date has not elapsed yet
Before this change the previously mentioned edge case would allow continuous exposure patients to be closed earlier than they should. This can be replicated by creating a patient similar to this (in tests) and seeing that they are eligible for closure
```ruby
patient.update(monitoring: true, isolation: false, …
```

SARAALERT-1561 - Additional non-reporting auto closure case

---

app/jobs/close_patients_job.rb
app/models/history.rb
test/jobs/close_patients_job_test.rb

Jira Ticket: [SARAALERT-1494](https://tracker.codev.mitre.org/browse/SARAALERT-1494)
History items for manual and automatic closures don't currently include the text of the reason for closure. This PR adds that to the `record_automatically_closed` history item as an optional parameter. The close patients job now passes the `montioring_reason` to this optional argument.
`history.rb`
- add optional reason argument to the `record_automatically_closed` History helper method.
`close_patients_job.rb`
- pass `monitoring_reason` to the new optional argument
`close_patients_job_test.rb`
- add tests to verify that the history change has the …

SARAALERT-1494 - Include reason for closure in the record_automatically_closed history item

---

docs/api/api-coming-soon.md

Update API docs for 1.34.0.
- Few things to note, changed the coming soon to 1.34.0, and did not list the new fields as coming soon, since by my guess those will not make 1.35.0. Also although some new fields were supported in 1.34.0, I would prefer to leave that undocumented in the release notes for now, and just document all the fields together once additional new fields are added.

SARAALERT-NONE: 1.34.0 API Documentation Updates

---

app/models/history.rb
test/jobs/close_patients_job_test.rb

Jira Ticket: [SARAALERT-1494](https://tracker.codev.mitre.org/browse/SARAALERT-1494)
This is related to https://github.com/SaraAlert/SaraAlert/pull/1014 and brings in a language change that was requested in addition to the changes made in that PR. The request is: `Change the first sentence of the History message for system-closed records (“Monitoree has completed monitoring”) to “Monitoree closed by the system.”`
`history.rb`
- Changed the default comment for the `record_automatically_closed` history item to use the newly requested language.
`close_patients_job_test.rb`
- Changed the test cases that involve this auto-close language to account of the new history comment change.
`bundle exec rails test test/jobs/close_patients_job_test.rb` and/or run the close patients job in you local …

SARAALERT-1494: Auto close history language change

---

app/controllers/fhir/r4/api_controller.rb
app/controllers/patients_controller.rb
app/models/history.rb
test/controllers/patients_controller_test.rb

Jira Ticket: [SARAALERT-890](https://tracker.codev.mitre.org/browse/SARAALERT-890)
Modifies Monitoring_Change histories to indicate what patient record the change originated from when the change was made to an entire household or a subset of the household. 
app/models/history.rb: modifies the comment-generating code for Monitoring_Change histories to clearly and concisely describe not only what the change was, but where the change was made from and to whom in the household. To support this, also changes the contract of the function to take in the ID of the record where the change originated as a parameter. …

SARAALERT-890: For changes to household, note where change originated in history. 

---

app/javascript/components/enrollment/steps/Exposure.js
app/javascript/components/patient/assessment/actions/ClearAssessments.js
app/javascript/components/patient/assessment/actions/SymptomOnset.js
app/javascript/components/patient/laboratory/LaboratoryModal.js
app/javascript/components/util/DeleteDialog.js
app/models/concerns/patient_date_validator.rb
app/models/patient.rb
test/models/patient_test.rb
test/system/roles/enroller/enrollment/form_validator.rb

Jira Ticket: [SARAALERT-1559](https://tracker.codev.mitre.org/browse/SARAALERT-1559)
Currently, users are allowed to future-date a monitoree's Symptom Onset Date by up to 30 days. When the Extend Isolation To date was implemented, this addressed the primary use case that was reference for the future-dating of Symptom Onset Date. So at this point, the system should no longer allow the user to future-date the Symptom Onset Date
Definition of Done:
- Prevent the user from being able to future-date a monitoree's Symptom Onset Date
- Prevent the user from importing a moniotree with a future-dated Symptom Onset Date.
- …

SARAALERT-1559: Do not allow the future-dating of Symptom Onset Date

---

app/helpers/fhir_helper.rb

When I added support for `public_health_action` via the API, I didn't account for the default value of `None` that should be used. So via the API, if no `public-health-action` extension is specified, a `public_health_action` is added to the db with the value `nil`. However, in other spots of the app, we assume that `public_health_action` will have a value of `None` by default, see [here](https://github.com/SaraAlert/SaraAlert/blob/f0898dea30e33ef1d0fa7f0e61b7d784ceed6c76/app/helpers/patient_details_helper.rb#L22) for an example.
This result in us assuming that a `public_health_action` has been set, because the value is not `None`, so the patient goes on the PUI line list, but in fact the value is just `nil`, so the patient should not be on the PUI line list.
On …

SARAALERT-NONE: Add a default value for public_health_action in the API

---

app/controllers/fhir/r4/api_controller.rb
app/helpers/fhir_helper.rb
app/helpers/patient_details_helper.rb
app/lib/import_export.rb
app/models/assessment.rb
docs/api/fhir-api-specification.md
docs/api/index.md
test/controllers/fhir/r4/immunization_test.rb
test/controllers/fhir/r4/observation_test.rb
test/controllers/fhir/r4/patient_test.rb
test/controllers/fhir/r4/related_person_test.rb
test/controllers/fhir/r4/transaction_test.rb

Jira Ticket: [SARAALERT-1548](https://tracker.codev.mitre.org/browse/SARAALERT-1548)
There are several fields which were available via manual Excel exports, which were not supported as readable via the API. This PR is meant to fill that gap and ensure that all fields which can be read via manual exports can be read via the API. This meant adding support for reading the following fields via the API:
**Patient**
* Monitored address fields  - `Patient.address`
* Foreign monitored address fields - `Patient.address`
* Transfers - complex extension in `Patient.extension`
* Created date
* Updated date
* ID
* To jurisdiction
* From jurisdiction
* Who initiated transfer
* Report source and report source specify - complex extension in `Patient.extension`
* Additional planned travel fields - simple …

SARAALERT-1548: Add read support for all exportable fields in API

---

app/controllers/public_health_controller.rb
app/controllers/user_filters_controller.rb
app/helpers/patient_query_helper.rb
app/javascript/components/public_health/CustomExport.js
app/javascript/components/public_health/Export.js
app/javascript/components/public_health/PatientsTable.js
app/javascript/components/public_health/PublicHealthHeader.js
app/javascript/components/public_health/Workflow.js
app/javascript/components/public_health/custom_export/PatientsFilters.js
app/javascript/components/public_health/query/AdvancedFilter.js
app/javascript/data/advancedFilterOptions.js
app/javascript/tests/mocks/mockFilters.js
app/javascript/tests/public_health/query/AdvancedFilter.test.js
app/views/public_health/exposure.html.erb
app/views/public_health/global.html.erb
app/views/public_health/isolation.html.erb
test/controllers/user_filters_controller_test.rb
test/factories/user_filter.rb
test/helpers/patient_query_helper_test.rb
test/test_helpers/user_filters_test_helper.rb

Jira Ticket: [SARAALERT-1020](https://tracker.codev.mitre.org/browse/SARAALERT-1020)
Currently, Sara Alert users are able to filter the dashboard view based on Assigned User & Jurisdiction through the standard dashboard filters. This ticket entails adding the ability to search by multiple users/jurisdictions, or addition of the "OR" operator to support ability to filter by multiple users/jurisdictions. This will require implementing a new "type" of multi-select advanced filter.
- Implement new "Multi-select" advanced filter type
- Add jurisdiction paths and assigned users to propTypes and get those options
- Add …

SARAALERT-1020: Add Assigned User and Jurisdiction to advanced filter

---

app/javascript/components/patient/assessment/actions/MonitoringPeriod.js
app/javascript/tests/patient/assessment/actions/MonitoringPeriod.test.js

Jira Ticket: [SARAALERT-1053](https://tracker.codev.mitre.org/browse/SARAALERT-1053)
Since the LDE and Continuous Exposure fields have not real relevance for the Isolation workflow, they should be hidden in the moniotree's main profile view as shown below, but they should still be available in the monitoree's Exposure Information Details.
Test resizing the screen for monitorees in both workflows, both should be dynamic
**Submitter:**
@tstrass  :
@timwongj :
@annmarieb1 :

SARAALERT-1053: Hide "Last Date of Exposure" and "Continous Exposure" in monitoree's profile when in Isolation Workflow

---

app/models/api_download.rb
app/models/oauth_application.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into OauthApplication model.
Related #1028
`OauthApplication.rb`
- Add `inverse_of` letting Rails know about the relationship between JWT and OauthApplication
`ApiDownload.rb`
Since this was now updated with the changes from 1.36 I've added some changes to related to ApiDownload.
Added the same dependent and inverse_of as JwtIdentifier
Added a missing belongs_to relationship with OauthApplication
Use the following [rubocop.txt](https://github.com/SaraAlert/SaraAlert/files/6956507/rubocop.txt) to …

SARAALERT-1470: OauthApplication & ApiDownload Model Changes

---

app/controllers/contact_attempts_controller.rb
app/javascript/components/patient/history/HistoryList.js
app/javascript/tests/patient/history/HistoryList.test.js
app/models/history.rb
db/migrate/20210811133939_add_manual_contact_attempt_history_type.rb
db/schema.rb
lib/tasks/demo.rake

Jira Ticket: [SARAALERT-1039](https://tracker.codev.mitre.org/browse/SARAALERT-1039)
Currently: Right now, the "Contact Attempt" history tag includes both manual contact attempts and for when the system sent a notification to a monitoree but did not receive a response. Maine is using the "manual contact attempt" button to track monitorees lost to follow up. 
This PR creates an additional history type "Manual Contact Attempt" rather than "Contact Attempt" so we can filter them appropriately in History. It also alphabetically sorts the creator and type history filter options.
`history.rb`
- Create 'Manual Contact Attempt' History type
` ccontact_attempts_controller.rb`
- Change contact attempts controller so that it creates a 'Manual Contact Attempt' history item when a user logs a manual …

SARAALERT-1039: Update History Filters to include "Manual Contact Attempt"

---

yarn.lock

Upgraded `url-parse`.  `glob-parent` vulnerabilities still need to be addressed but that will involve upgrading `webpacker-dev-server` to v4

Yarn Lock Updates

---

app/jobs/consume_assessments_job.rb
test/jobs/consume_assessments_job_test.rb

Jira Ticket: [SARAALERT-1596](https://tracker.codev.mitre.org/browse/SARAALERT-1596)
Disable retry of failed SMS. Most likely, if SMS messages fail, they are not going to succeed when retried an hour later, so this provided marginal benefit, and results in substantial cost when high numbers of messages fail (e.g. in the case of a carrier filtering all our messages).
`consume_assessments_job.rb`
- Removed the line that results in retries.

SARAALERT-1596: Disable retry of failed SMS

---

app/javascript/components/patient/assessment/AssessmentTable.js
app/javascript/components/patient/assessment/actions/CurrentStatus.js
app/javascript/components/patient/assessment/actions/MonitoringPeriod.js
app/javascript/components/patient/close_contacts/CloseContactModal.js
app/javascript/components/patient/close_contacts/CloseContactTable.js

Jira Ticket: [SARAALERT-1439](https://tracker.codev.mitre.org/browse/SARAALERT-1439)
The language that appears in a blank notes field in the Close Contacts modal says "enter additional information about case" if the monitoree is in isolation, and "enter additional information about monitoree's potential exposure" if monitoree is in exposure. Should say "enter additional information about contact"–regardless of the workflow the monitoree is in.
Also updated this spacing issue where not all the tables had the same spacing in monitoree details: 
**Submitter:**
@timwongj :
@hackrm :
@ngfreiter :

SARAALERT-1439: Update Placeholder text in Close Contact Notes field

---

app/helpers/patient_query_helper.rb
app/javascript/data/advancedFilterOptions.js
test/helpers/patient_query_helper_test.rb

Jira Ticket: [SARAALERT-1018](https://tracker.codev.mitre.org/browse/SARAALERT-1018)
Create a Boolean advanced filter for Monitorees who have at least one Close Contact that has not been enrolled yet.
`advancedFilterOptions.js`
- Added boolean unenrolled close contact option to advanced filter list
- Added support for the unenrolled close contact filter.  True returns monitorees with one or more unenrolled close contact, while false returns monitorees with only enrolled close contacts or no close contacts
`patient_query_helper_test.rb`
- Added test for new advanced filter query
Please list any recommendations …

SARAALERT-1018: Ability to search for monitorees with an unenrolled close contact in advanced search

---

config/locales/fra.yml
config/locales/spa-pr.yml
config/locales/spa.yml

Remove special characters from Spanish, Puerto Rican Spanish, and French locales.
They were previously removed here: https://github.com/SaraAlert/SaraAlert/pull/1042
And mistakenly reintroduced here: https://github.com/SaraAlert/SaraAlert/pull/1041
It's crucial that we remove them in order to get a more efficient encoding for SMS messaging.
I am aware that some of the affected parts of the locale file are shared by voice and web mediums. It's not ideal, but that is how it must be for now. Note that the initial removal of the characters was deployed in 1.35.2 and has been live in prod for a couple weeks now without issue.

Re-remove special chars from spa, pr-spa, fra locales

---

app/javascript/components/patient/monitoring_actions/AssignedUser.js
app/javascript/components/patient/monitoring_actions/ExposureRiskAssessment.js
app/javascript/components/patient/monitoring_actions/Jurisdiction.js
app/javascript/components/patient/monitoring_actions/MonitoringPlan.js
app/javascript/components/patient/monitoring_actions/MonitoringStatus.js
app/javascript/components/patient/monitoring_actions/PublicHealthAction.js

This PR comes after user feedback saying that the Dropdowns within the Monitoring Actions section of the Patient Detail Page are very "noisy" when using a screen reader. Currently, a screen reader will read the label and the tooltip associated with it for each dropdown.
This PR overrides the `aria-label` for each dropdown in the Monitoring Actions area so that the tooltip is not also read by the screen-readers.
> Open up VoiceOver and attempt to change the dropdown of the Monitoring Actions.
> Notice that screen reader reads a LOT of information for each change.
> Try the same behavior on this branch and notice that it only reads the header.
`app/javascript/components/patient/monitoring_actions/AssignedUser.js`
`app/javascript/components/patient/monitoring_actions/ExposureRiskAssessment.js …

BUGFIX: Monitoring Actions Aria-Labels Fix

---

app/lib/phdc/serializer.rb

Jira Ticket: [SARAALERT-1591](https://tracker.codev.mitre.org/browse/SARAALERT-1591)
This PR makes some minor updates to the PHDC serialization after some feedback we got back from folks with NBS. The updates are:
* Remove the repetitive `Investigation Local ID` element. This element contains the same info as the `Investigation State Local ID` element, so no need to have both.
* Add an entry to the "Clinical Information" section of the PHDC for the condition, in this case COVID-19. 
* Change `assignedPerson` to the more accurate `assignedAuthoringDevice`, since the Sara Alert jurisdiction which authored is not a specific person.
`serializer.rb`
- Made the changes described above.
* Test that the PHDC is serialized without error
* If you want, you can test that the resulting XML is valid …

SARAALERT-1591: Update PHDC Serialization

---

app/controllers/active_storage/blobs/proxy_controller.rb
app/jobs/destroy_downloads_job.rb
test/jobs/destroy_downloads_job_test.rb

Jira Ticket: [SARAALERT-1480](https://tracker.codev.mitre.org/browse/SARAALERT-1480)
This error appears when the Export Retry time is set lower than the Download Destroy Wait time. This configuration allows a User to perform another export before the DownloadsDestroyJob is run, causing the DeserializationError. When the User performs another export, the previous exports of the same type are destroyed. This causes the DeserializationError at most 45 minutes later.
As before, even if the Download is not found for a different reason, it will be destroyed by the PurgeJob and not lingering in object storage.
1. Set the admin setting for exports lower than the download destroy wait time
2. Perform an export and download the results 
3. Perform another export of the same type once the export …

SARAALERT-1480: Resolve ActiveJob::DeserializationError Download not found error

---

app/controllers/contact_attempts_controller.rb
app/javascript/components/patient/assessment/actions/ContactAttempt.js
app/javascript/components/patient/assessment/actions/LastDateExposure.js
app/javascript/components/patient/follow_up_flag/FollowUpFlag.js
app/javascript/components/patient/household/HouseholdMemberTable.js
app/javascript/components/patient/household/actions/ApplyToHousehold.js
app/javascript/components/patient/monitoring_actions/AssignedUser.js
app/javascript/components/patient/monitoring_actions/CaseStatus.js
app/javascript/components/patient/monitoring_actions/ExposureRiskAssessment.js
app/javascript/components/patient/monitoring_actions/Jurisdiction.js
app/javascript/components/patient/monitoring_actions/MonitoringPlan.js
app/javascript/components/patient/monitoring_actions/MonitoringStatus.js
app/javascript/components/patient/monitoring_actions/PublicHealthAction.js

Jira Ticket: [SARAALERT-1601](https://tracker.codev.mitre.org/browse/SARAALERT-1601)
Household members don't clear when toggling in Contact Attempt modal, see How to Replicate section for recreation steps.
1. Go to the details page for a monitoree with household members
2. Click the Log Manual Contact Attempt button
3. Select radio button for "This monitoree and selected household members"
4. Select checkboxes for one or more household members
5. Select radio button for "This monitoree only"
6. Click submit
The implementations for the `ApplyToHousehold` component are the same across the board, however, this bug only occurred for contact attempts.  In all cases, the ids were NOT cleared on when toggling the radio buttons.  For consistencies sake, I made this change to every instance of the …

SARAALERT-1601: Apply Contact Attempt to Household Bug

---

app/javascript/components/patient/laboratory/LaboratoryModal.js
app/models/laboratory.rb
app/models/non_empty_laboratory_validator.rb
test/models/laboratory_test.rb

Jira Ticket: [SARAALERT-1556](https://tracker.codev.mitre.org/browse/SARAALERT-1556)
This PR updates the lab validation logic to only require that at least one field is non-empty. The requirement that at least one date field and a result are specified is removed. This requirement is also now enforced in the API. On import, this shouldn't be a problem, since a lab is only created on import when one field is non-empty. This does not affect the validation logic for making a lab when enrolling a monitoree, because in that case we still should require a specimen collection and a positive result.
`LaboratoryModal.js`
- Update the validation to only require at least one field
`laboratory.rb`
- Add a validator on the model to enforce that at least one field is present …

SARAALERT-1556: Update lab creation/editing logic

---

app/javascript/components/patient/close_contacts/CloseContactTable.js
app/javascript/packs/stylesheets/custom_table.scss

Jira Ticket: [SARAALERT-###](https://tracker.codev.mitre.org/browse/SARAALERT-###)
Status tooltips are not displaying at certain screen sizes).  I also fixed a bug where the horizontal scrollbar for tables would be detached from the table.
Status tooltips (workflow linelist and notification eligibility) above the reports table are not showing up when the screen size is at a certain width.  This occurs when the screen size is small enough for the reports table to be scrollable, but large enough that the buttons above the table don't wrap.
In `custom_table.scss`, we handle the overflow on the tables that have dropdowns by setting the padding and offsetting the margin.  When the close contacts table was converted to a react component (has a larger dropdown from the others), this value was …

BUGFIX: Status tooltips are not showing up

---

app/javascript/components/patient/laboratory/LaboratoryModal.js

Jira Ticket: [SARAALERT-1556](https://tracker.codev.mitre.org/browse/SARAALERT-1556)
This is a fix on top of https://github.com/SaraAlert/SaraAlert/pull/1086. In #1086, I updated the lab validation logic on enrollment so that only one field was required by the modal, but once you clicked the "Next" button you would still get an error if you did not include specimen collection date. We'd rather have that validation in the modal itself, so now the modal requires that you enter a specimen collection date. 
Enroll a patient into isolation, and enter a lab result with no dates on it, and no symptom onset. You will get an error when you click "Next". On this branch however, you should not be allowed to save the lab at all unless you enter specimen collection.
Require specimen collection to be …

SARAALERT-1556: Clarify enrollment lab result validation

---

app/javascript/components/enrollment/steps/Contact.js

Jira Ticket: [SARAALERT-1382](https://tracker.codev.mitre.org/browse/SARAALERT-1382)
Fix contact time warning message appearing when undefined
Enroll new monitoree and notice warning message appearing by default
Do not display warning message when contact time is undefined
**Submitter:**
@tstrass :
@ngfreiter :
@sgober :

SARAALERT-1382: Fix contact time warning message appearing when undefined

---

app/javascript/components/enrollment/steps/Contact.js

Alternate implementation to #1123 
Accomplish this by allowing email and confirm email fields to be undefined. Initialize the confirm field if the email field is modified so that the confirm email validation is still run.
This makes things a little cleaner as now we won't POST or PATCH an empty email string if the value is not set, which brings email in line with the behavior of the other contact fields.

Fix bug where blank alt contact email logged in history

---

app/javascript/components/util/EligibilityTooltip.js

This fixes a bug which would cause the incorrect notification status to display for patients in the patients table following some sort of filtering that does not refresh the full page, such as applying an advanced filter.
1. Navigate to the patients table with no filters applied.
2. Apply the "Household Member" filter as `true`.
3. Note that the notification status column does not update, we would expect that all patients would have the household icon, but the icons remain the same as before the advanced filter was applied.
Add a hook to update the state on the `EligibilityTooltip` component when the props update. This ensures that the state of this component is accurate.
Please list important files (meaning substantial or integral to the PR) along with a list of the …

SARAALERT-NONE: Fix bug with reporting eligibility icon in patient table

---

package.json
yarn.lock

This rolls eslint back to version 6.8.0, to remove the dependency on a version of `node` that is causing issues when we try to deploy.

Roll back eslint

---

Nginx.Dockerfile
README.md
app/jobs/consume_assessments_job.rb
app/jobs/produce_assessment_job.rb
docker-compose.prod.yml
docker-compose.yml
lib/reports_helper.rb
lib/tasks/reports.rake
test/jobs/consume_assessments_job_test.rb
test/rake/reports_helper_test.rb
test/sidekiq/sidekiq_test.rb
test/test_case.rb
test/test_helpers/consume_assessments_job_test_helper.rb

Jira Ticket: [SARAALERT-1175](https://tracker.codev.mitre.org/browse/SARAALERT-1175)
Maybe also [SARAALERT-1377](https://tracker.codev.mitre.org/browse/SARAALERT-1377)
Currently ConsumeAssessmentsJob launches into an infinite loop. This means we cannot see any timings/performance on any of the methods inside this loop - we will only get notified of a final exception because at that point the thread will actually exit.
The main benefit of this reorganization is visibility into the log
and 'errors' during a ConsumeAssessmentJob. Secondary benefit is a
scaling architecture which is homogeneous with the rest of of
background jobs.
`reports.rake`
* Refactor reports.rake to launch a queue only job ("queue job").
- Improve error handling within queue job to include publish backoff
- Improved …

SARAALERT-1175: Refactor ConsumeAssessmentsJob to be performed by Sidekiq Async

---

app/javascript/components/util/DateInput.js

Jira Ticket: [SARAALERT-400](https://tracker.codev.mitre.org/browse/SARAALERT-400)
Bug introduced in #1154 
The date input was not formatting the date correctly for the component's `onChange` callback when there `showTime` is false. The timestamp it was using was including the time. This theoretically shouldn't be an issue, because the date is still present in the timestamp, but it causes an issue with vaccinations, because the `Vaccine` model has a validation that rejects the full timestamp.
- Try to create a vaccine with an administration date
Format the timestamp differently based on whether the DateInput is showing time or not.
- Test creating vaccines with administration date
- Test all other components with DateInputs to ensure they are working still.

Bugfix: Fix issue with date input callback function

---

app/mailers/patient_mailer.rb
app/models/jurisdiction.rb
app/views/patient_mailer/enrollment_email.html.erb
config/sara/jurisdiction_messages.yml
db/migrate/20211110160736_add_custom_messages_to_jurisdictions.rb
db/schema.rb
lib/tasks/admin.rake
lib/tasks/mailers.rake
test/fixtures/jurisdictions.yml
test/mailers/patient_mailer_test.rb

Jira Ticket: [SARAALERT-902](https://tracker.codev.mitre.org/browse/SARAALERT-902)
This adds the ability for jurisdictions to specify a custom welcome messages (and their translations) for SMS and email.
`20211110160736_add_custom_messages_to_jurisdictions.rb`
- Add a column in Jurisdiction table to hold the custom messages
`admin.rake `
- Add a task to read in and save the custom messages
- See `jurisdiction_messages.yml` for a sample to the expected structure of this file
- Structure was designed to mimic both the jurisdictions.yml file and the translations files that hold the default messages
- Ideally the translations would be registered with Rails in the same way the translations of the default messages are, but like the actual jurisdiction hierarchy, the jurisdictions' custom …

SARAALERT-902 custom welcome message

---

app/helpers/patient_query_helper.rb
app/javascript/components/public_health/query/AdvancedFilter.js
app/javascript/data/advancedFilterOptions.js
test/helpers/patient_query_helper_test.rb

Jira Ticket: [SARAALERT-1635](https://tracker.codev.mitre.org/browse/SARAALERT-1635)
This ticket makes the behavior of the Telephone Number (Contains) advanced filter match the behavior of the Telephone Number (Exact Match) advanced filter. Specifically, the Telephone Number (Contains) filter did not previously strip out special characters, while the Telephone Number (Exact Match) filter uses the Phonelib gem to parse the number and remove special characters before querying the database. 
This ticket also makes a tiny change to the logic in  renderSearchStatement as discussed in Slack [here](https://mitrecorp.slack.com/archives/C029CLK0X2P/p1637171821013600?thread_ts=1637170608.013100&cid=C029CLK0X2P) (Note: This logic was initially introduced because a tooltip was to be added for the …

SARAALERT-1635 : Change "Telephone Number (Contains)" Filter to ignore special characters

---

app/helpers/patient_query_helper.rb

From Alex: Right now it looks like if you set a Common Exposure Cohort advanced filter and leave the field blank, it'll filter out all monitorees. I think the way we were thinking it would work is that it will filter out no monitorees (that's what the tooltip currently says)
https://mitrecorp.slack.com/archives/C029JM3PFC4/p1637699389134800 …

fix cohorts adv filter

---

app/lib/phdc/serializer.rb

Jira Ticket: [SARAALERT-1625](https://tracker.codev.mitre.org/browse/SARAALERT-1625)
This updates the PHDC export to remove the signs and symptoms section, and instead represent this data in an HTML table. See the example linked in the ticket for how this is supposed to look. I made a few style changes, but when exporting the PHDC for a patient with symptomatic reports, the PHDC should contain an HTML table similar to that in the linked example.
`serializer.rb`
- Update the PHDC export to remove the Signs and Symptoms section and replace it with "Active Problems" HTML table
- NBS export a Patient with no reports
- NBS export a Patient with reports, but none that are symptomatic
- NBS export a Patient with symptomatic reports
**Submitter:**
@tstrass 
@sgober 
@timwongj

SARAALERT-1625: Remove Signs and Symptoms section from PHDC

---

app/javascript/components/enrollment/steps/ExposureInformation.js

Bugfix to prevent overwriting the Contact Relationship when adding a Common Exposure Cohort
1. Enroll a new monitoree in exposure filling out only the required fields
2. When on the contact step, be sure to swap the primary contact relationship and add a contact name
3. For the Exposure Information (last) step, add a common exposure cohort
4. Click next and the contact type has been reset to self
When updating the `enrollmentState` in the `ExposureInformation` component, `modified` was being updated with the values in `current`, instead of using `modified`.  This then is what is used to set the state in the `Enrollment` component, which is why the value is overwritten
**Submitter:**
@tstrass :
@timwongj :
@deastman :

SARAALERT-NONE: Contact Type Reset Bugfix

---

app/helpers/close_contact_query_helper.rb
app/helpers/patient_details_helper.rb
app/helpers/patient_query_helper.rb
app/javascript/components/patient/household/actions/MoveToHousehold.js
app/javascript/components/public_health/PatientsTable.js
app/javascript/components/public_health/custom_export/PatientsFilters.js
app/javascript/utils/PatientFormatters.js
app/lib/import_export_constants.rb
test/controllers/public_health_controller_test.rb
test/fixtures/patients.yml
test/system/roles/public_health/dashboard/dashboard_verifier.rb
test/system/roles/public_health/dashboard/export_verifier.rb

Jira Ticket: [SARAALERT-1631](https://tracker.codev.mitre.org/browse/SARAALERT-1631)
Add Ability to Search by Phone Number and Email to all patient searches (Patients Table, Move to Household modal, export search).  Also add a phone number column to the patients and move to household tables (this column is not sortable)
- Add support for searching by email and phone number to the `filter_by_text` method
`MoveToHousehold.js`, `PatientsTable.js`, `PatientsFilters.js`
- Added column for phone number to the table (n/a for `PatientsFilters.js`)
- Updated search tooltip to include phone number and email …

SARAALERT-1631: Add Ability to Search by Phone Number and Email

---

lib/tasks/stats.rake

These mistakes have been there since the queries were initially written in Jan 2021.
Please do visual review and run the stats rake task and export to ensure no issues.
Example:
```
rake stats:eval_queries ids=1,2,5,3,4,6,7 start=2021-12-10 tag=foo
```
```
rake stats:eval_queries_export ids=1,2,5,3,4,6,7 tag=foo
```

Fix mistakes in age demographics stats queries

---

app/helpers/assessment_query_helper.rb
app/helpers/close_contact_query_helper.rb
app/helpers/patient_query_helper.rb
app/helpers/vaccine_query_helper.rb
app/models/patient.rb
lib/tasks/demo.rake

Jira Ticket: [SARAALERT-###](https://tracker.codev.mitre.org/browse/SARAALERT-###)
For column sorts within Sara Alert, Null values are always sorted to be at the bottom of the list regardless of sort direction. But for blank values (values that held a value at one point that were then cleared out by the monitoree) currently are not sorted the same way. Revise the column sorting logic for all applicable columns to ensure that blank values are sorted to the end of the list regardless of sort direction where Null values are also sorted.
- Example …

SARAALERT-1649: Column Sort should result in all null and blank values appearing at the bottom

---

app/helpers/patient_details_helper.rb
app/javascript/components/patient/assessment/AssessmentTable.js
app/javascript/components/patient/assessment/actions/CurrentStatus.js
app/javascript/tests/patient/assessment/actions/CurrentStatus.test.js
app/models/patient.rb
app/views/patients/show.html.erb
config/sara/sara.yml
lib/tasks/demo.rake
test/jobs/close_patients_job_test.rb
test/jobs/send_assessments_job_test.rb
test/models/patient_notification_eligibility_test.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-1662](https://tracker.codev.mitre.org/browse/SARAALERT-1662)
- Shorten the period for when a case is eligible for the Records Requiring Review line list to: at least 5 days (down from 10 days) from Symptom Onset/First Positive Lab AND at least 1 day without a fever/use of a fever reducer.
- Change the default monitoring period from 14 days to 10 days (from Last Date of Exposure).
`app/helpers/patient_details_helper.rb`, `app/models/patient.rb`
- replace hard-coded 10 day recovery definition period with admin options variable
`config/sara/sara.yml`
- update `monitoring_period_days` from `14` to `10`
- create new …

SARAALERT-1662: Update monitoring and recovery definition periods

---

app/jobs/consume_assessments_job.rb

Sentry was getting flooded with errors for ordinary cases in the consume assessments job that don't merit actual concern

Remove excessing Sentry logging statements

---

app/javascript/components/enrollment/steps/Arrival.js
app/models/concerns/patient_date_validator.rb

Jira Ticket: [SARAALERT-1297](https://tracker.codev.mitre.org/browse/SARAALERT-1297)
The "Date of Departure" field and calendar modal allows the user to select a date 30 days in the future. However, a future date is not valid and on the next page red validation language appears saying the future dating is not allowed. This PR updates the calendar modal to set the maxDate to today. 
Dates beyond the current date are not selectable in the "Date of Departure" calendar modal. 
`app/javascript/components/enrollment/steps/Arrival.js`
- Change maxDate to today
Ensure that dates beyond the current date are not selectable in the "Date of …

SARAALERT-1297: Make selectable dates for Arrival Information consistent with system validation

---

app/javascript/components/util/DateInput.js
package.json
yarn.lock

Jira Ticket: [SARAALERT-1415](https://tracker.codev.mitre.org/browse/SARAALERT-1415)
In shorter screens, the symptom onset date picker cuts off about halfway. Ideally, would like the full calendar to show, or just have the calendar open below the field rather than above it.
Make your chrome screen short in height (so that there is more room above the symptom onset datepicker than below it), then open the datepicker.  The result is the datepicker popping up and getting cutoff (because there is not room above) rather than popping down and forcing the user to scroll.
Used `popperModifiers` prop to force the placement even if the datepicker deems there's not enough space.  Also upgraded `react-datepicker` to the latest
Please list any recommendations regarding what reviewers should test and …

SARAALERT-1415: Fix date picker popup being cutoff on small screens

---

app/javascript/components/public_health/PatientsTable.js
app/models/patient.rb

Jira Ticket: [SARAALERT-1574](https://tracker.codev.mitre.org/browse/SARAALERT-1574)
Since End of Monitoring date is only relevant for monitorees in the Exposure workflow, show End of Monitoring as blank for monitorees in the Isolation workflow within the Global Dashboard and the CSV Line List export.  
**Note**: This PR does not remove the End of Monitoring date column from the CSV Line List export in the Isolation dashboard (with this PR, all values in the column are blank). Per @hackrm there is a [ticket in the backlog](https://tracker.codev.mitre.org/browse/SARAALERT-1108) to completely deactivate CE for the Isolation workflow in the future since CE has no impact on the Isolation workflow.
End of Monitoring is blank for monitorees in the Isolation Workflow within the Global Dashboard. …

SARAALERT-1574: For cases in the Global Dashboard, display <blank> for End of Monitoring value

---

app/javascript/components/enrollment/steps/CaseInformation.js
app/javascript/components/patient/laboratory/FirstPositiveLaboratory.js
app/javascript/tests/patient/laboratory/FirstPositiveLaboratory.test.js

Jira Ticket: [SARAALERT-1660](https://tracker.codev.mitre.org/browse/SARAALERT-1660)
Currently, if a user tries to delete a lab result that already exists via the Edit Case Status page, the lab result will not be deleted. To address this situation, this PR prevents the user from being able to delete an already existing lab result via the Edit Case Status page and directs them to delete it from the Lab Results Table.
While on the `1.42.0` branch ...
- Find a existing monitoree in the Isolation workflow that has at least one positive lab result and go to their Edit Case Status page
- Remember the details of the Lab Result currently displayed.
- Delete the lab result, go to the review screen and save the monitoree
- Go to the Lab Results table and see that the lab result you attempted to …

1660: Remove ability to delete an already existing positive lab result in the Edit Case Status page

---

app/javascript/components/public_health/custom_export/PatientsFilters.js
app/javascript/components/public_health/query/AdvancedFilter.js

Jira Ticket: [SARAALERT-1665](https://tracker.codev.mitre.org/browse/SARAALERT-1665)
After saving an export preset with an advanced filter and opening it up again, the advanced filter is applied to the query but not displayed in the modal.
1. Create and save a user export preset with a saved advanced filter
2. Refresh and reload the saved user export preset and notice that the advanced filter is not displayed, but is applied (based on the number of patients filtered)
Please list any …

SARAALERT-1665: Saved export preset advanced filter is not displayed

---

app/controllers/admin_controller.rb
app/controllers/application_controller.rb
app/javascript/components/admin/UserModal.js
app/models/user.rb
db/migrate/20220126135321_add_last_activity_at_to_user.rb
db/schema.rb
test/fixtures/users.yml
test/models/user_test.rb

Jira Ticket: [SARAALERT-1666](https://tracker.codev.mitre.org/browse/SARAALERT-1666)
Currently, if a user is unlocked, the system sets that user's status to inactive/active based on whether it's been 30 days since `current_user_sign_in_at`.  (Note: the 30-day value is configurable, which was added in SARAALERT-1375 and is `<%= ENV['INACTIVE_USER_THRESHOLD'] || 30 %>`)
This pull request adds a new timestamp column to the Users table, `last_activity_at`. Specifically, `last_activity_at` is updated at 15 minute intervals, i.e., the `last_activity_at` timestamp is updated on the current_user's request if the `last_activity_at` timestamp is more 15 minutes in the past. (This was discussed with @tstrass in lieu of updating the timestamp on every request and incurring the I/O cost of doing so.) …

SARAALERT-1666: Admin Panel - Have active/inactive statuses dependent on most recent activity instead of login

---

app/controllers/export_controller.rb

Jira Ticket: [SARAALERT-1682](https://tracker.codev.mitre.org/browse/SARAALERT-1682)
The `exported_recently?` method in the export_controller returns a 401 unauthorized status code if a user attempts to create the same type of report within 15 minutes.
The unauthorized status code erroneously causes a toast to appear with the text, 'Your session expired. Please sign in again to continue.' This is because the unauthorized status code is used to timeout the user's session [here](https://github.com/SaraAlert/SaraAlert/blob/master/app/javascript/components/layout/Header.js#L23) 
- Create a Custom Format Export
- Immediately try to create another Custom Format Export
- Confirm toast appears with text: 'Your session expired. Please sign in again to continue.' 
This PR updates the …

SARAALERT-1682: Change status code in export_controller when same export type created less than 15 minutes ago

---

app/helpers/patient_query_helper.rb
app/javascript/data/advancedFilterOptions.js
app/javascript/tests/mocks/mockFilters.js
app/javascript/tests/public_health/query/AdvancedFilter.test.js
db/migrate/20220203164307_remove_shortened_quarantine_filters.rb
db/schema.rb
test/controllers/public_health_controller_test.rb

Jira Ticket: [SARAALERT-1679](https://tracker.codev.mitre.org/browse/SARAALERT-1679)
As a result of [SARAALERT-1662](https://tracker.codev.mitre.org/browse/SARAALERT-1662), the 2 candidate for shortened quarantine filters are no longer relevant and need to be removed. 
Do not remove the scopes used for these filters in the patient model. But remove usage of these scopes and remove the 2 candidate for shortened quarantine filters from the Advanced Filter drop down
Create a migration that removes both of these filter options from any saved Advanced Filters that contain them.
Note: User export preset advanced filters are now shown properly until https://github.com/SaraAlert/SaraAlert/pull/1196 is merged
Please list important files (meaning substantial or integral to the PR) along with a list …

SARAALERT-1679: Remove shortened quarantine filters

---

app/helpers/patient_details_helper.rb
app/models/patient.rb
config/sara/sara.yml
test/models/patient_notification_eligibility_test.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-1627](https://tracker.codev.mitre.org/browse/SARAALERT-1627)
Adds a config value to sara.yml to make the non-reporting interval configurable independent of the reporting interval.
N/A
- Updates scopes in `patient.rb` to use `non_reporting_period_minutes` instead of `reporting_period_minutes`
`app/helpers/patient_details_helper.rb`
- Updates status to use `non_reporting_period_minutes` instead of `reporting_period_minutes`
`config/sara/sara.yml`
- Adds `non_reporting_period_minutes` as config to to make the non-reporting interval configurable independent of the reporting interval (defaults to 1440 minutes or 1 day) 
One possible testing avenue is to `rails c `, change `ADMIN_OPTIONS['non_reporting_period_minutes']` and confirm that the …

SARAALERT-1627: make non reporting period configurable

---

app/javascript/components/enrollment/steps/PublicHealthManagement.js
app/javascript/tests/enrollment/steps/PublicHealthManagement.test.js

Jira Ticket: [SARAALERT-946](https://tracker.codev.mitre.org/browse/SARAALERT-946)
Adds tooltips to Risk Assessment and Monitoring Plan fields within the Enrollment wizard to align with the monitoree's profile view. 
`app/javascript/components/enrollment/steps/PublicHealthManagement.js`
- Adds appropriate InfoTooltip to MONITORING PLAN and RISK ASSESSMENT fields. 
- Confirm that tooltips are present in the Enrollment wizard within the PUBLIC HEALTH RISK ASSESSMENT AND MANAGEMENT SECTION. 
**Submitter:**
@sgober  :
@timwongj  :
@hackrm  :

SARAALERT-946: Add Risk Assessment and Monitoring Plan tooltips to last Enrollment wizard screen

---

app/javascript/components/public_health/query/AdvancedFilter.js

Fix issue where the advanced filter dropdown does not auto scroll to the current selected option
Select an option in the advanced filter dropdown that is further down in the scrollable view.  Close the dropdown and reopen it, the selected option will not be in the current view (but still is selected).
Used the options array to get the value object of the selected value.
Do the steps in the "How to Replicate" section
**Submitter:**
@timwongj :
@hackrm :
@deastman :

SARAALERT-NONE: Fix Advanced Filter Selected Option Scroll

---

app/javascript/components/public_health/query/AdvancedFilter.js
app/javascript/tests/public_health/query/AdvancedFilter.test.js

Jira Ticket: [SARAALERT-1232](https://tracker.codev.mitre.org/browse/SARAALERT-1232)
Given the existing erroneous behavior of the Reset button (detailed in the Jira ticket) and that this feature is likely not commonly used if used at all, it is being removed from the Filter modal. Additionally, the descriptive line at the bottom of the Filter modal has been revised to reflect the current state of how sticky the filters are. 
`app/javascript/components/public_health/query/AdvancedFilter.js`
- Removed the Rest button and reset function
- Revised the descriptive line displayed at the bottom of the modal
`app/javascript/tests/public_health/query/AdvancedFilter.test.js`
- Revised Filter tests appropriately
Open the Advanced Filter modal and observe that once a filter has been applied, there is …

SARAALERT-1232: Remove Reset button from Advanced Filter Modal

---

app/javascript/components/admin/AuditModal.js
app/javascript/components/util/InfoTooltip.js
app/models/user.rb

Jira Ticket: [SARAALERT-1678](https://tracker.codev.mitre.org/browse/SARAALERT-1678)
All manually set Status changes in the Admin view for a given user will be logged in that user's Audit log. This does not include Statuses set by the system such as "Inactive," "Active," and the auto-lock reason. 
`app/javascript/components/admin/AuditModal.js`
- Displays new audits for `manual_lock_reason` data element
- New Info tooltip for Manually set Status audits (to clarify that system-set Statuses are not audited)
`app/models/user.rb`
- Included `manual_lock_reason` as an auditable data element
As an Admin user, attempt to change the Status of a user and validate the Audit log displayes the changes properly. Only manually set Statuses will be …

SARAALERT-1678: Including manual Status changes in Audit log

---

app/javascript/components/public_health/PatientsTable.js
app/javascript/components/public_health/query/JurisdictionFilter.js

Jira Ticket: [SARAALERT-1685](https://tracker.codev.mitre.org/browse/SARAALERT-1685)
When the Dashboard page is refreshed or when the user switches between workflows, the Jurisdiction Filter remains sticky in terms of filtering the displayed monitorees, but the sticky value doesn't appear in the UI for the Filter. This pull request ensures that the Jurisdiction value that is being used to filter the Dashboard monitorees is shown in the user interface within the Jurisdiction filter input control.
1. Filter the Patient Dashboard by a specific jurisdiction (E.g., USA, State 1, County 2)
2. Click on a different Workflow (E.g., if you were initially in the Exposure Monitoring Workflow, choose the Isolation Workflow) or refresh the page
3. Confirm that the monitorees in the table are still …

SARAALERT-1685: Display sticky value for the Dashboard Jurisdiction Filter

---

app/helpers/enroller_query_helper.rb

Inroduced in #1211 
Same-named methods were defined in the `PatientQueryHelper` and the `EnrollerQueryHelper`. When both modules were included in the `PatientsController`, bugs ensued because the unintended overload of the methods were being called.
- Try to remove a monitoree from a household (results in 500 error)
- Try to move a monitoree to a household (results in only the patients the current user has enrolled)
- Change the names of the ambiguous methods in the `EnrollerQueryHelper` to be unique.
- Confirm you can reproduce the bugs in master
- Confirm you cannot reproduce the bugs in this branch

Fix critical enroller helper bug

---

app/helpers/patient_query_helper.rb
app/javascript/components/public_health/query/AdvancedFilter.js
app/javascript/tests/mocks/mockFilters.js
app/javascript/tests/public_health/query/AdvancedFilter.test.js
app/lib/advanced_filter_options.rb
test/helpers/patient_query_helper_test.rb

Jira Ticket: [SARAALERT-1699](https://tracker.codev.mitre.org/browse/SARAALERT-1699)
- Address (blank)
- Age 
- Add a blank option to the drop down list
- When a non-blank drop down option is selected and the numerical input ( s) are left blank , the filter option should not filter out _any_ monitorees. 
- When a non-blank drop down option is selected, display the following tooltip
- "Leaving number field(s ) blank will not filter out any monitorees" 
- Manual Contact Attempts 
- *Do not* add a blank option to the drop down list 
- If the numerical input ( s) are left blank , the filter option should not filter out _any_ monitorees. 
- Display the following tooltip
- "Leaving number field(s ) blank will not filter out any monitorees"
Please list important files (meaning substantial or …

SARAALERT-1699: Adv filter should display patients with unpopulated value when blank

---

app/javascript/components/enrollment/steps/ExposureInformation.js
app/javascript/components/util/InfoTooltip.js
app/javascript/tests/enrollment/steps/ExposureInformation.test.js
app/models/patient.rb
test/api_controller_test_case.rb
test/controllers/fhir/r4/patient_test.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-1108](https://tracker.codev.mitre.org/browse/SARAALERT-1108)
Since this toggle has no impact of the monitoree's behavior in the isolation workflow, it would be best to have this toggle inactive.
Script to be executed along with these changes:
```
ActiveRecord::Base.connection.execute(Arel.sql("UPDATE patients SET continuous_exposure = false WHERE purged = false AND monitoring = true AND isolation = true AND continuous_exposure = true"))
```
- Ensure CE is disabled and proper tooltip message is displayed for isolation cases
- Ensure CE is still …

SARAALERT-1108: Deactivate the "Continuous Exposure" Toggle for cases in the Isolation Workflow

---

app/javascript/components/patient/assessment/steps/SymptomsAssessment.js
app/javascript/tests/patient/assessment/steps/SymptomsAssessment.test.js

Jira Ticket: [SARAALERT-1222](https://tracker.codev.mitre.org/browse/SARAALERT-1222)
Introduced in #1248 
Fixes weird floating tooltip when submit button is disabled, as well as not accurately detecting changes for int/float symptoms (empty or otherwise).  This is due to all inputs being cast to a string in the on change, so added a line to prevent that from happening.
**Submitter:**
@tstrass :
@deastman :
@hackrm :

SARAALERT-1222: Disable Submit Assessment Button Bugfixes
