.gitlab-ci.yml

**Submitter:**
**Reviewer:**
Name:

Fix typo in .gitlab-ci.yml when pushing docker image

---

.rubocop.yml
app/controllers/public_health_controller.rb
app/models/patient.rb

- Refactored public_health_controller to reduce duplicate code
- Added sorting of columns (works for multiple too)
- Made risk sorting specific rather than alphabetical
---
**Submitter:**
**Reviewer:**
Name:

Added column sorting on backend; Fixed risk sorting

---

app/controllers/patients_controller.rb
app/jobs/close_subjects_job.rb
app/mailers/patient_mailer.rb
app/views/patient_mailer/closed_email.html.erb

Send closed email when monitoring complete
---
**Submitter:**
**Reviewer:**
Name:

Send closed email when monitoring complete

---

app/controllers/export_controller.rb
app/controllers/patients_controller.rb
app/controllers/public_health_controller.rb
app/models/jurisdiction.rb
app/models/patient.rb
app/models/transfer.rb
app/views/public_health/_patients.html.erb
app/views/public_health/index.html.erb
config/routes.rb
db/migrate/20200218015650_create_transfers.rb
db/schema.rb

Added transfer tracking
---
**Submitter:**
**Reviewer:**
Name:

Added transfer tracking

---

app/controllers/patients_controller.rb
app/javascript/components/Patient.js
app/javascript/components/PatientPage.js
app/javascript/components/enrollment/Enrollment.js
app/javascript/components/enrollment/steps/Review.js
app/views/patients/edit.html.erb
app/views/patients/new.html.erb
app/views/patients/new_group_member.html.erb
app/views/patients/show.html.erb

Added group dependents list to monitoree view
---
**Submitter:**
**Reviewer:**
Name:

Added group dependents list to monitoree view

---

test/fixtures/symptoms.yml
test/mobile_application_system_test_case.rb
test/rake/admin_task_test.rb
test/system/components/assessment/form.rb
test/system/components/public_health_monitoring/dashboard.rb
test/system/components/public_health_monitoring/history.rb
test/system/components/public_health_monitoring/reports.rb
test/system/form_data/assessments.yml
test/system/monitoree_test_mobile.rb
test/system/public_health_test.rb

Fixed the system tests that were breaking, refactored symptoms and updated fixtures (temperature -> fever)
**Submitter:** Tim Wong
**Reviewer:**
Name:

fix system tests

---

app/controllers/assessments_controller.rb
app/controllers/histories_controller.rb
app/javascript/components/PatientPage.js
app/javascript/components/subject/AddReportNote.js
app/javascript/components/subject/ClearReports.js
app/views/patients/index.html.erb
app/views/patients/show.html.erb
app/views/public_health/index.html.erb

Added ability to add notes to reports
---
**Submitter:**
**Reviewer:**
Name:

Added ability to add notes to reports

---

app/controllers/analytics_controller.rb

**Submitter:**
**Reviewer:**
Name:

Replace nil with unknown when patients do not have a state

---

app/javascript/components/enrollment/Enrollment.js
app/javascript/components/enrollment/steps/Review.js
test/system/components/monitoree_enrollment/form.rb

Added modal describing group add behavior

Added modal describing group add behavior

---

Gemfile
Gemfile.lock
app/jobs/consume_assessments_job.rb

Includes our SaraSchema gem and adds a validation method to the assessment consumer.

Schema validator

---

lib/tasks/demo.rake

Add env SKIP to skip all but final analytics cache

---

app/javascript/components/dashboard/widgets/RiskFactors.js
lib/tasks/demo.rake

Fixes an issue that was on production, where country data was `null` and `countryData.toString` was being called for a React Key, causing an error. This wraps the entire table in a conditional

Fixes no Country data Available Bug

---

.github/workflows/test.yml
.rubocop.yml
Gemfile
Gemfile.lock
test/application_system_test_case.rb
test/factories/history.rb
test/factories/jurisdiction.rb
test/factories/patient.rb
test/factories/role.rb
test/factories/user.rb
test/helpers/patient_helper_test.rb
test/models/history_test.rb
test/models/jurisdiction_test.rb
test/models/patient_test.rb
test/models/symptom_test.rb
test/models/user_test.rb
test/rake/analytics_task_test.rb
test/test_helper.rb

This pull request establishes Unit test framework with Factory Bot and Faker into the application by:
* Including Factory Bot as  a development/test dependency 
* Moving fixture loading to the system tests and the rake task tests
* creates blank factory files for many models
* working factory files for patient, user, jurisdiction, history for testing the user model.
This pull request also publishes our test coverage online as part of the GH actions workflow and includes the simplecov-lcov plugin gem which provides a 1-file format for upload to coveralls.
I've also tweaked the rubocop configuration to enable some new cops that are not yet default (thus removing warnings) and included the test directory except system tests and the existing rake tests to be examined by rubocop. 
Finally it …

Unit test setup/User and History model

---

app/models/patient.rb
app/models/transfer.rb

See conversation : https://github.com/SaraAlert/SaraAlert/pull/76/files/41d6ee55404c1422347eca742309ccbac2fa4428#r413876999

Update time_frame scopes to include Total and default case

---

.env-prod-enrollment-example

Small update to have consistency between README and examples.

Update env-prod-enrollment-example with twillio variables

---

app/models/history.rb
app/models/integer_symptom.rb
app/models/symptom.rb
test/factories/bool_symptom.rb
test/factories/integer_symptom.rb
test/factories/symptom.rb
test/models/history_test.rb
test/models/integer_symptom_test.rb
test/models/symptom_test.rb

Something to note here is the `:text` attribute is not tested because we don't have a `:text` column on this model.

Symptom unit tests

---

.github/workflows/test.yml
bin/rails
lib/simplecov_saraalert.rb
lib/tasks/coverage_report.rake
test/application_system_test_case.rb
test/helpers/patient_helper_test.rb
test/mobile_application_system_test_case.rb
test/models/history_test.rb
test/models/integer_symptom_test.rb
test/models/jurisdiction_test.rb
test/models/laboratory_test.rb
test/models/patient_test.rb
test/models/subject_test.rb
test/models/symptom_test.rb
test/models/user_test.rb
test/system_test_case.rb
test/test_case.rb
test/test_helper.rb

Move formatting logic into  custom SimpleCov profile for the application with rake task to merge coverages and report in lcov format for use in CI

Merge Test Coverage between System test and unit/integration

---

.env-prod-enrollment-example
README.md
app/controllers/assessments_controller.rb
app/jobs/consume_assessments_job.rb
app/jobs/produce_assessment_job.rb
app/mailers/patient_mailer.rb
app/models/patient.rb
app/views/patient_mailer/assessment_email.html.erb
app/views/patient_mailer/enrollment_email.html.erb
config/twilio/assessment_studio_flow.json
lib/tasks/mailers.rake
yarn.lock

History items will be entered for a monitoree when they do not respond via SMS and Voice or if there is an error sending them their messages, likely due to a bad phone number or attempting to SMS a landline. In the cases of errored send or no answer via voice, last_assessment_reminder_sent will be set to nil so that that the system will attempt to reach out again an hour later when the send assessments job is run.

Twilio improvements

---

app/controllers/export_controller.rb
app/javascript/components/monitor/DownloadExcelAllMonitorees.js
app/javascript/components/monitor/DownloadExcelPurgeableMonitorees.js
app/javascript/components/subject/DownloadMonitoreeExcel.js
app/models/history.rb
app/models/laboratory.rb
app/views/public_health/exposure.html.erb
app/views/public_health/isolation.html.erb
config/routes.rb
test/application_system_test_case.rb
test/fixtures/laboratories.yml
test/mobile_application_system_test_case.rb
test/models/patient_test.rb
test/system/lib/public_health_monitoring/dashboard.rb
test/system/lib/public_health_monitoring/downloads_verifier.rb
test/system/lib/public_health_monitoring/helper.rb
test/system/lib/system_test_utils.rb
test/system/public_health_test.rb
test/system/workflow_test.rb

JIRA: [https://jira.mitre.org/browse/SARAALERT-331](https://jira.mitre.org/browse/SARAALERT-331)
Bug fixes:
Improvements:
Testing:

SARAALERT-331: System tests for exports

---

app/javascript/components/admin/ReleaseUpdate.js
app/javascript/components/assessment/Assessment.js
app/javascript/components/enrollment/Enrollment.js
app/javascript/components/import/Import.js
app/javascript/components/laboratory/Laboratory.js
app/javascript/components/monitor/DownloadExcelAllMonitorees.js
app/javascript/components/subject/AddReportNote.js
app/javascript/components/subject/CaseStatus.js
app/javascript/components/subject/ClearReports.js
app/javascript/components/subject/ClearSingleReport.js
app/javascript/components/subject/ContactAttempt.js
app/javascript/components/subject/DownloadMonitoreeExcel.js
app/javascript/components/subject/MonitoringStatus.js
app/javascript/components/subject/PauseNotifications.js
app/javascript/components/subject/SendReminder.js
app/javascript/components/subject/SymptomOnset.js
app/javascript/components/util/ReportError.js
app/javascript/packs/stylesheets/toastify.scss
app/views/layouts/application.html.erb
app/views/user_mailer/admin_message_email.html.erb

changed all axios Catch blocks to use reportError
fixed report error modal

Move Error Reporting to New Component

---

app/views/public_health/exposure.html.erb
app/views/public_health/isolation.html.erb

Update formatting guidance paths to be from github

---

app/models/assessment_receipt.rb
test/factories/assessment_receipt.rb
test/models/assessment_receipt_test.rb
test/models/laboratory_test.rb

Also fixes a bug in the `Laboratory` test.

Assessment receipt tests

---

README.md

Adds development database creation and information about demo username/password credentials to the README.

README updates for development database creation and demo credentials.

---

app/javascript/components/import/Import.js
app/javascript/components/util/ConfirmDialog.js

https://jira.mitre.org/browse/SARAALERT-274

Add checkbox for import to allow for the ignoring of duplicate records

---

app/javascript/components/subject/AddReportNote.js
app/javascript/components/subject/CaseStatus.js
app/javascript/components/subject/ChangeHOH.js
app/javascript/components/subject/ClearReports.js
app/javascript/components/subject/ClearSingleReport.js
app/javascript/components/subject/ContactAttempt.js
app/javascript/components/subject/DownloadMonitoreeExcel.js
app/javascript/components/subject/MonitoringStatus.js
app/javascript/components/subject/PauseNotifications.js
app/javascript/components/subject/SendReminder.js
app/javascript/components/subject/SymptomOnset.js
app/javascript/components/util/ConfirmDialog.js
app/javascript/packs/stylesheets/datatables.scss
app/views/layouts/_help.html.erb
app/views/patients/show.html.erb
test/system/lib/public_health_monitoring/reports.rb

Improved assessment table; Added loading animation to status changes

---

.gitlab-ci.yml
Nginx.Dockerfile
README.md
docker-compose.yml
nginx.conf

Please discuss with me before merging.

Static assets container

---

app/javascript/components/assessment/Assessment.js
app/javascript/components/laboratory/Laboratory.js
app/javascript/components/subject/AddReportNote.js
app/javascript/components/subject/CaseStatus.js
app/javascript/components/subject/ChangeHOH.js
app/javascript/components/subject/ClearReports.js
app/javascript/components/subject/ClearSingleReport.js
app/javascript/components/subject/ContactAttempt.js
app/javascript/components/subject/DownloadMonitoreeExcel.js
app/javascript/components/subject/MonitoringStatus.js
app/javascript/components/subject/PauseNotifications.js
app/javascript/components/subject/RemoveFromHousehold.js
app/javascript/components/subject/SendReminder.js
app/javascript/components/subject/SymptomOnset.js

This will still reload the page, but also set the scroll location to where the user was before.

Using reload for better user experience on monitoree page

---

app/javascript/components/enrollment/steps/Contact.js
app/javascript/components/history/HistoryComponent.js
app/javascript/components/subject/CurrentStatus.js
app/javascript/components/subject/MonitoringStatus.js
app/javascript/components/util/InfoTooltip.js
app/views/patients/show.html.erb
app/views/public_health/_exposure_tabs.html.erb
app/views/public_health/_isolation_tabs.html.erb

Added more information tooltip/buttons to the fields listed here: https://mitre.sharepoint.com/:w:/r/sites/CoVDT/_layouts/15/Doc.aspx?sourcedoc=%7B336D5C90-70FE-4318-8392-B8C5B140AAEC%7D&file=20200529%20Info%20button%20text.docx&action=default&mobileredirect=true&cid=a4f8f6a7-39d3-4352-9039-5410fc2a3065

More info btns

---

app/helpers/import_export_helper.rb
app/models/patient.rb

For ~15k monitorees in exposure, the download takes ~17 secs
For ~6k monitorees in exposure, the download takes ~12 secs (takes longer to check isolation statuses)
Not sure how long they would have taken before the change, but wouldn't be surprised if it took an hour

Linelist export via bulk queries

---

app/controllers/public_health_controller.rb
app/javascript/components/Patient.js
app/javascript/components/subject/MoveToHousehold.js
config/routes.rb

Monitorees can now be moved into a household if they are a self reporter. The monitorees available to be set as their new head of household are those who are themselves self reporters.

Movetohousehold

---

app/controllers/patients_controller.rb
app/controllers/public_health_controller.rb

Enrollers will now only be able to see monitorees that they enrolled int he move to household dropdown

Scope hoh patients enroller can see to their enrolled_patients

---

lib/tasks/admin.rake

Added nil check for unique identifier on jurisdiction import or update

---

app/javascript/components/subject/MonitoringStatus.js
app/models/patient.rb
lib/tasks/demo.rake

SARAALERT-440: Add duplicate as reason for closure

---

app/helpers/import_export_helper.rb
test/system/lib/public_health_monitoring/export_verifier.rb

SARAALERT-430: Add patient id to linelist export

---

app/models/assessment.rb
app/models/patient.rb
test/models/patient_test.rb

JIRA: https://jira.mitre.org/browse/SARAALERT-493

SARAALERT-493: Records with any symptom reports should not qualify for asymp logic

---

app/javascript/components/dashboard/widgets/GeographicSummary.js

Re-adds the ability to view map data as table

---

app/controllers/import_controller.rb

Disables location validation on import.
https://jira.mitre.org/browse/SARAALERT-512

Remove the address validation in the import controller

---

test/system/form_data/monitorees.yml
test/system/lib/system_test_utils.rb
test/system/workflow/workflow_test.rb

Fixes test failures introduced in: https://github.com/SaraAlert/SaraAlert/pull/277

WIP: Fix system tests

---

config/puma.rb

More PUMA threads+processes

---

lib/tasks/admin.rake

Jira Ticket: https://jira.mitre.org/browse/SARAALERT-585
You now have to explicitly enter 'y' before jurisdiction update changes will be written to the database. This allows changes to be rolled back if the final hashes printed out do not match between runs on the enrollment and assessment containers.
Please describe the tests needed to verify your changes. Provide instructions for reproducing these tests. List any relevant details for …

Make jurisdiction update transactional

---

app/models/patient.rb
test/system/roles/public_health/dashboard/export_verifier.rb

Fix end of monitoring date

---

config/locales/en.yml
config/locales/es-PR.yml
config/locales/es.yml
config/locales/fr.yml
config/locales/so.yml

Jira Ticket: SARAALERT-523/569
Add translation entries for words used in jurisidction update https://gitlab.mitre.org/2019-ncov/jurisdiction-resources/-/merge_requests/12
Please list important files (meaning substantial or integrel to the PR) along with a list of the general changes that should be highlighted for reviewers.
Changes are to the locale files, will need to work with translators to populate _acual_ translations, all are in English as place holders for now.
To test, use jurisdiction.yml in gitlab MR linked to above and open an assessment for a patient in "Tribe …

Update translations with new symptoms

---

Gemfile
Gemfile.lock
app/mailers/patient_mailer.rb
test/mailers/patient_mailer_test.rb
test/test_case.rb

Jira Ticket: SARAALERT-586
Adds tests for the Patient Mailer 
*checking content of mail, SMS, and voice messages being sent out. 
*checking that appropriate histories are set on success/error
*checking that reminder time is set
Included `rspec-mocks` gem to mock the Twilio objects such that we can make assertions/expectations surrounding the messages being sent out.
I added a couple rubocop disable line lengths to avoid having to match the body of the messages/voice while integrating newlines...
Not applicable (not a change that displays anything to the front end)
Please …

Patient mailer test

---

config/locales/en.yml
config/locales/fr.yml
config/locales/so.yml

Jira Ticket: [SARAALERT-530](https://tracker.codev.mitre.org/browse/SARAALERT-530)
Since a variety of contact information may be provided on this message now, update the following:
"if you have immediate concerns, please call your medical provider or local health department" to say
"if you have immediate concerns, please contact your medical provider or local health department"
changed instruction2 in the following yml files:
`en.yml`
`fr.yml`
`so.yml`
Reviewer: holmesie
Checklist:
Reviewer: kylietmo
Checklist:

Update monitoree web-link message to say "contact" instead of "call"

---

app/controllers/public_health_controller.rb
app/javascript/components/subject/MoveToHousehold.js

https://tracker.codev.mitre.org/browse/SARAALERT-661
Remove search feature in movetohoh dropdown, browsers have a hard time with it as number of monitorees increases.
Now, monitorees just appear in an alphabetized list that you have to scroll to
Almost all changes were made to the MoveToHousehold.js script.
This fix was tested on the following browsers (submitter must …

Reduce browser workload in movetohousehold dropdown

---

app/controllers/assessments_controller.rb
app/controllers/patients_controller.rb
app/controllers/public_health_controller.rb
app/helpers/patient_details_helper.rb
app/javascript/components/enrollment/steps/Identification.js
app/javascript/components/public_health/Import.js
app/javascript/components/public_health/PatientsTable.js
app/javascript/components/subject/CurrentStatus.js
app/javascript/components/subject/SymptomOnset.js
app/javascript/components/util/EligibilityTooltip.js
app/javascript/components/util/InfoTooltip.js
app/javascript/packs/datatables.js
app/javascript/packs/stylesheets/application.scss
app/javascript/packs/stylesheets/bootstrap.scss
app/jobs/purge_job.rb
app/models/history.rb
app/models/patient.rb
app/views/patients/_histories.html.erb
app/views/patients/show.html.erb
config/sara/sara.yml
db/migrate/20200801142657_add_index_to_assessment_receipts.rb
db/schema.rb
package.json
test/controllers/public_health_controller_test.rb
test/models/history_test.rb
test/models/patient_test.rb
test/system/roles/enroller/dashboard/dashboard_verifier.rb
test/system/roles/public_health/dashboard/dashboard_verifier.rb
yarn.lock

Alternative style:
Jira Tickets: SARAALERT-635, 620, 537, 610, 618
- Added info tooltips for sexual orientation, birth sex, and gender identity
- Show symptom onset date on line lists
- Show notification eligibility information on the line lists and in monitoree details
- Remove sex from line lists
- Send notifications to RR and PUI line lists
Reviewer: @timwongj 
Checklist:
Reviewer: @kylietmo 
Checklist:
Reviewer: @sgober 
Checklist:
Reviewer: @mayerm94 
Checklist:

1.10.0 Usability Improvements

---

app/javascript/components/enrollment/Enrollment.js

Jira Ticket: SARAALERT-664
When enrolling a monitoree, `<Enrollment/>` runs through a carousel of many components. `<Enrollment/>` maintains its own state, as do each of the components. They all report state changes up to `<Enrollment/>`. One function was updating `isolation` to be whatever the child passed up. But this raised the issue of, "What if a child isnt passing up isolation?" In that case, `!!isolation` would be `!!undefined` which is `false`. This lead to the user being directed to the `Exposure` Carousel pages, when they should have been seeing the `Isolation` pages.
Enroll a monitoree and change their workflow from the Monitoree Detail Page.
This PR will now take you to the correct final page (eg, adding the Symptom Onset Date for Isolation)
`Enrollment.js`
- …

Fixes Workflow Issues

---

app/controllers/patients_controller.rb
app/javascript/components/enrollment/Enrollment.js
app/javascript/components/enrollment/steps/Contact.js
app/javascript/components/patient/Patient.js
app/javascript/components/public_health/Import.js
app/javascript/components/subject/SymptomOnset.js
app/models/assessment.rb
app/models/patient.rb
app/views/patients/show.html.erb
db/migrate/20200709133910_add_linelist_fields_to_patients.rb
db/migrate/20200806201118_add_user_defined_symptom_onset.rb
db/schema.rb
lib/tasks/demo.rake
test/models/assessment_test.rb
test/models/patient_test.rb
test/system/roles/public_health/dashboard/export_verifier.rb

Jira Ticket: [SARAALERT-669](https://tracker.codev.mitre.org/browse/SARAALERT-669)
- Improve logic so that system does not overwrite dates set by a user
- Hide "Review" button from isolation workflow so that users do not accidentally clear out symptom onset date by marking all as reviewed
Please describe the tests needed to verify your changes. Provide instructions for reproducing these tests. List any relevant details for your test …

SARAALERT-669: Symptom Onset Date overwritten or reverts when new report added

---

db/migrate/20200810194643_add_additional_chain_index_to_conditions.rb
db/schema.rb

add additional chain index to conditions

---

app/javascript/components/admin/AdminTable.js
app/javascript/components/enrollment/steps/Identification.js

Jira Ticket: NONE
Age was not automatically calculating in enrollment after updating DOB. 
1. Go to enroll a new monitoree. 
2. Change DOB.
3. Notice age does not calculate even when there's a valid DOB.
The code to automatically update the age was in the` handleChange()` method and not the new `handleDateChange()` method. Just needed to move it over.
`app/javascript/components/enrollment/steps/Identification.js`
- Updated `handleDateChange()` to update age data upon valid date. Moved this logic from `handleChange()`
To test, please replicate the above steps to try and replicate the bug and confirm it no longer happens. 
Reviewer: @timwongj 
Checklist:
Reviewer: @holmesie 
Checklist:

BUGFIX: Age not calculating when updating DOB in Enrollment

---

.github/PULL_REQUEST_TEMPLATE.md

Updating PR template to remove some sections and fluff.

Updating PR Template

---

app/javascript/components/assessment/steps/AssessmentCompleted.js

Remove prepended slashes from href

---

.github/workflows/test.yml
app/jobs/cache_analytics_job.rb
app/jobs/close_subjects_job.rb
app/jobs/purge_job.rb
app/mailers/user_mailer.rb
app/views/user_mailer/assessment_job_email.html.erb
app/views/user_mailer/cache_analytics_job_email.html.erb
app/views/user_mailer/close_job_email.html.erb
app/views/user_mailer/purge_job_email.html.erb

Add more mailers to send job results
`modified:   app/jobs/cache_analytics_job.rb` added job results email deliver_now
`modified:   app/jobs/close_subjects_job.rb`added job results email deliver_now
`modified:   app/jobs/purge_job.rb` added job results email deliver_now
`modified:   app/mailers/user_mailer.rb` added mailers for each job
`modified:   app/views/user_mailer/assessment_job_email.html.erb` tweaked capitalization
`new file:   app/views/user_mailer/cache_analytics_job_email.html.erb` email template for analytics job
`new file:   app/views/user_mailer/close_job_email.html.erb` email template for close job
`new file: …

Add more mailers to send job results

---

README.md

Added brief subsection on the react component tests to the general Sara readme and hyperlinked the more detailed readme

Update readme to include react component tests

---

db/migrate/20200902213827_add_chain_index_to_patients_three.rb
db/schema.rb

SARAALERT-749: Improve performance of patient queries

---

app/models/patient.rb
config/sara/sara.yml

1.11.3. Bugfix

---

config/locales/en.yml
config/locales/es-PR.yml
config/locales/es.yml
config/locales/fr.yml
config/locales/so.yml

Simple updates to the locale translation files in accordance with the most recent symptom additions here: https://gitlab.mitre.org/2019-ncov/jurisdiction-resources/-/merge_requests/15

Add new symptoms to locales

---

app/javascript/components/subject/LastDateExposure.js

Jira Ticket: [SARAALERT-733](https://tracker.codev.mitre.org/browse/SARAALERT-733)
Update misleading text in Continuous Monitoring and LDE modals.
Updated to reflect these mockups: https://tracker.codev.mitre.org/secure/attachment/30708/HH_LDE_CM_modal.pptx
`LastDateExposure.js`: swapped from switch to radio buttons and updated language

Updates to continuous exposure/LDE modals

---

app/views/layouts/_help.html.erb

Jira Ticket: [SARAALERT-766](https://tracker.codev.mitre.org/browse/SARAALERT-766)
Add a user forum option to the help menu that will help connect users to user forum as an additional resource. 
`_help.html.erb`: added additional dropdown menu option

Added user forum option to the help menu

---

app/javascript/components/subject/CaseStatus.js

Jira Ticket: [SARAALERT-763](https://tracker.codev.mitre.org/browse/SARAALERT-763)
Updating "Case Status" is not working as expected in several ways
There are multiple bugs, see the JIRA ticket for descriptions and steps to recreate (with screenshots).
The biggest fix here was refactoring the `handleChange` method to make more sense logically.  In addition, there are multiple language changes.
`CaseStatus.js`
Please describe the tests needed to verify your changes. Provide instructions for reproducing these tests. List any relevant details for …

Case status modal updates

---

.rubocop.yml
app/controllers/assessments_controller.rb
app/controllers/import_controller.rb
app/controllers/patients_controller.rb
app/controllers/public_health_controller.rb
app/jobs/consume_assessments_job.rb
app/models/assessment.rb
app/models/patient.rb
app/models/symptom.rb
test/system/lib/system_test_utils.rb
test/system/roles/admin/admin_test_helper.rb
test/system/roles/admin/dashboard/dashboard.rb
test/system/roles/admin/dashboard/dashboard_verifier.rb
test/system/roles/enroller/dashboard/dashboard_verifier.rb
test/system/roles/enroller/enroller_dashboard_test.rb
test/system/roles/enroller/enroller_enrollment_test.rb
test/system/roles/enroller/enroller_test_helper.rb
test/system/roles/enroller/enrollment/form.rb
test/system/roles/enroller/enrollment/form_validator.rb
test/system/roles/enroller/patient_page/patient_page_verifier.rb
test/system/roles/public_health/dashboard/dashboard.rb
test/system/roles/public_health/dashboard/dashboard_verifier.rb
test/system/roles/public_health/patient_page/actions.rb
test/system/roles/public_health/patient_page/reports.rb
test/system/roles/public_health/public_health_bulk_edit_test.rb
test/system/roles/public_health/public_health_dashboard_test.rb
test/system/roles/public_health/public_health_import_export_test.rb
test/system/roles/public_health/public_health_patient_page_test.rb
test/system/roles/public_health/public_health_test_helper.rb
test/system/workflow/workflow_test.rb

Rc lc recovery

---

app/javascript/components/subject/CaseStatus.js

Jira Ticket: [SARAALERT-828](https://tracker.codev.mitre.org/browse/SARAALERT-828)
Update Case Status Modal with Radio Buttons for HH members
`CaseStatus.js`: swap to radio buttons and updated the onChange function

Case status modal radio buttons

---

config/locales/es-PR.yml
config/locales/es.yml

Jira Ticket: SARAALERT-824
Updated Spanish translations
`config/locales/es-PR.yml`
- Updated Spanish translations
`config/locales/es.yml`
- Updated Spanish translations
Enroll a new monitoree, and set primary language to Spanish. Open up an assessment weblink, and compare the translations.

SARAALERT-824: Updated Spanish translations

---

config/locales/fr.yml

Jira Ticket: SARAALERT-823
Updated French translations
`config/locales/fr.yml`
- Updated French translations
Enroll a new monitoree, and set primary language to French. Open up an assessment weblink, and compare the translations.

SARAALERT-823: Updated French translations

---

app/javascript/components/enrollment/steps/AdditionalPlannedTravel.js
app/javascript/components/enrollment/steps/Arrival.js
app/javascript/components/enrollment/steps/Contact.js
app/javascript/components/enrollment/steps/Exposure.js
app/javascript/components/enrollment/steps/Identification.js
app/javascript/components/laboratory/Laboratory.js
app/javascript/components/subject/LastDateExposure.js
app/javascript/components/subject/MonitoringStatus.js
app/javascript/components/subject/SymptomOnset.js
app/javascript/components/util/InfoTooltip.js
test/system/roles/enroller/enrollment/form_validator.rb

Jira Ticket: [SARAALERT-794](https://tracker.codev.mitre.org/browse/SARAALERT-794)
See JIRA ticket for list of minor issues to address
- validation
- info

Minor issues identified from 1.12 testing

---

.github/workflows/anchore-analysis.yml
.github/workflows/static.yml
.github/workflows/test.yml

We want to run the GitHub Actions on everything rather than just the `master` branch. See syntax [here](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#on). 
`.github/workflows/anchore-analysis.yml`
`.github/workflows/static.yml`
`.github/workflows/test.yml`
- Now running on every push and pull request.

Run GitHub Actions on every push and PR.

---

app/javascript/components/enrollment/steps/Exposure.js
app/views/user_mailer/welcome_email.html.erb

Jira Ticket: SARAALERT-405 & SARAALERT-878
Included more information helpful to users in welcome email & fixed a typo in the UI.
`app/views/user_mailer/welcome_email.html.erb`
- Included information in email about the temp password expiring after 72 hours & advice to manually type the password
`app/javascript/components/enrollment/steps/Exposure.js`
- Fixed typo: seperate --> separate

Updating welcome email & fixing a typo

---

app/javascript/components/util/InfoTooltip.js

Jira Ticket: SARAALERT-903
Very small pull request to reword the contents of the `Case Status` Info Tooltip.
- Rewords the Tooltip

rewords the case status tootip per JIRA Ticket#903

---

app/javascript/components/public_health/PatientsTable.js

Will be put back on the 1.15.0 candidate PR that will be opened up shortly.
- Removed import and kept if check to avoid unused import and unused parameter linting errors.

Removing HoH render from master. 

---

app/javascript/components/subject/CaseStatus.js
app/models/history.rb

update history message for dependents upon case status change of HoH

---

.github/workflows/static.yml
package.json
yarn.lock

- Adds `yarn audit` to static analysis workflow.
- Updates node modules
- Updates version pin on `@rails/webpacker` to `^5.2.0`

Yarn audit

---

app/controllers/public_health_controller.rb
app/controllers/user_filters_controller.rb
app/javascript/components/enrollment/steps/AdditionalPlannedTravel.js
app/javascript/components/enrollment/steps/Arrival.js
app/javascript/components/enrollment/steps/Exposure.js
app/javascript/components/enrollment/steps/Identification.js
app/javascript/components/laboratory/Laboratory.js
app/javascript/components/layout/CustomTable.js
app/javascript/components/public_health/AdvancedFilter.js
app/javascript/components/public_health/PatientsTable.js
app/javascript/components/subject/LastDateExposure.js
app/javascript/components/subject/SymptomOnset.js
app/javascript/components/util/DateInput.js
app/javascript/packs/stylesheets/bootstrap.scss
app/javascript/packs/stylesheets/datepicker.scss
app/models/user.rb
app/models/user_filter.rb
config/routes.rb
db/migrate/20200923172958_create_user_filters.rb
db/schema.rb

Jira Ticket: SARAALERT-509
Adds the ability to do advanced filtering of monitorees on all dashboard line lists.
Reset button on dashboard (added in addition to sticky settings)
`app/controllers/public_health_controller.rb`
- Added advanced filter to endpoint
`app/controllers/user_filters_controller.rb`
- New controller to handle CRUD for user filters
`app/javascript/components/public_health/AdvancedFilter.js `
- New advanced filter React component
`app/javascript/components/public_health/PatientsTable.js`
- Added advanced filter component to table
`app/javascript/components/util/DateInput.js `
- Expanded date input to allow custom css …

SARAALERT-509: Advanced search

---

README.md

Update Jobs description in README.

Update Jobs Description in README

---

app/javascript/components/subject/LastDateExposure.js

Jira Ticket: SARAALERT-835
Update LDE language to what Kelly wanted

SARAALERT-835: Fix lde language

---

app/controllers/public_health_controller.rb

Should not consider purged dependents when adding HoH badge.

Don't consider purged dependents when adding HoH badge.

---

app/models/user.rb

Filter out purged monitorees from enroller view

Filter out purged monitorees from enroller view

---

app/javascript/tests/subject/PauseNotifications.test.js

Frontend test failing due to tooltip change.

Fixing frontend component test

---

app/javascript/components/layout/Header.js
app/javascript/components/subject/MonitoringStatus.js
app/javascript/components/util/InfoTooltip.js
app/lib/roles.rb
app/views/layouts/application.html.erb
app/views/layouts/doorkeeper/admin.html.erb
app/views/layouts/doorkeeper/application.html.erb
app/views/patients/show.html.erb

This PR makes the following small updates:
1. Fixes issue where the active tab wouldn't be highlighted when in Isolation workflow.
2. Adds back demo warning bar underneath nav bar.
3. Updates new Nav bar tabs to be aligned with Sara Alert brand logo.
4. Updates the Assigned Jurisdiction tooltip underneath Monitoring Actions to have new text that is dynamic based on role.
`app/javascript/components/layout/Header.js`
- Changes to handle updates 1-3 listed above. The diff is really rough because I had to wrap everything in a `<React.Fragment>`.
`app/javascript/components/subject/MonitoringStatus.js`
`app/views/patients/show.html.erb`
- Changes for update 4.
This fix was tested on the following browsers (submitter must check all those that …

Small Fixes for 1.16.0

---

app/controllers/public_health_controller.rb

fixes linting issue

---

app/javascript/components/admin/AdminTable.js
test/system/roles/admin/dashboard/dashboard.rb
test/system/roles/admin/dashboard/dashboard_verifier.rb
test/system/roles/public_health/dashboard/export_verifier.rb

Jira Ticket: SARAALERT-889
Increase timeout on admin test dashboard validations

Fix Failing System Tests

---

README.md

update sql downgrading instructions

---

app/controllers/histories_controller.rb
app/controllers/public_health_controller.rb
app/javascript/components/public_health/AdvancedFilter.js
app/javascript/packs/stylesheets/bootstrap.scss
db/migrate/20201104192101_add_contact_attempts_to_patients.rb
db/schema.rb
lib/tasks/demo.rake

Jira Ticket: [SARAALERT-597](https://tracker.codev.mitre.org/browse/SARAALERT-957)
Advanced Filter has new selectable option for "Manual Contact Attempts" which can have a positive integer value (including 0) that finds all records with that number of manual contact attempts.
- Added a number type option for advanced filters that takes a non-negative integer (>0) and an operator (equal, greater than, less than, etc)
- Use this new number type to implement a manual contact attempts advanced filter
`public_health_controller.rb`
- Backend changes needed for manual contact attempts filter
`histories_controller.rb`
- When …

SARAALERT-957: Advanced filter manual contact attempts

---

app/models/patient.rb

Bugfix for issue that is causing edits of Monitoree details to not show up in History.

Fixing bug in detailed history edits.

---

app/controllers/fhir/r4/api_controller.rb

Updating param in API controller for history update.

---

app/models/patient.rb

We're seeing some latency issues on prod relating to household updates and have isolated some queries that can be improved.

Improving queries related to finding the HoH.

---

app/javascript/components/public_health/AdvancedFilter.js

Jira Ticket: [SARAALERT-957](https://tracker.codev.mitre.org/browse/SARAALERT-957)
Updated Operator filter to use language instead of symbols

SARAALERT-957: changed operator symbols to text

---

app/controllers/import_controller.rb
app/javascript/components/public_health/Import.js
app/models/laboratory.rb
app/models/patient.rb
test/models/laboratory_test.rb
test/models/patient_test.rb

- Commented out code we want to test more before patch.
- Removed dead/unused code from Import.js.
- Added back code that was removed to make new import validation work, just to be safe for emergency patch.

Hotfix: Commented out import validation and adding back code temporarily for patch.

---

app/javascript/components/public_health/PatientsTable.js
test/system/roles/public_health/dashboard/dashboard.rb
test/system/roles/public_health/dashboard/dashboard_verifier.rb

debounce patient table queries

---

app/helpers/patient_details_helper.rb
app/lib/import_export.rb

fix linelist export symptom onset

---

db/migrate/20201104192101_add_contact_attempts_to_patients.rb
lib/tasks/demo.rake

exclude system contact attempts from manual contact attempts

---

app/jobs/send_purge_warnings_job.rb
app/models/user.rb

Jira Ticket: [SARAALERT-1004](https://tracker.codev.mitre.org/browse/SARAALERT-1004)
Send the purge warning to SuperUsers as well as admins.

Saraalert-1004 Send Purge Warning to SuperUsers

---

app/views/patients/show.html.erb

1.18.0 fix

---

app/controllers/public_health_controller.rb

Fix advanced filter manual contact attempts operands

---

app/javascript/components/patient/Patient.js

add check if LDE is defined

---

app/controllers/public_health_controller.rb
app/controllers/user_filters_controller.rb
app/javascript/components/public_health/AdvancedFilter.js
app/javascript/components/public_health/PatientsTable.js
app/javascript/packs/stylesheets/bootstrap.scss
lib/tasks/demo.rake

Fixes both the regular date and relative date filters
1. user filters with relative dates not saving - [how to replicate](https://teams.microsoft.com/dl/launcher/launcher.html?url=%2F_%23%2Fl%2Ffile%2F331D80A5-E459-4D3B-B6FD-1E8FB46D43A0%3FtenantId%3Dc620dc48-1d50-4952-8b39-df4d54d74d82%26fileType%3Dpptx%26objectUrl%3Dhttps%253A%252F%252Fmitre.sharepoint.com%252Fsites%252FCoVDT%252FShared%2520Documents%252FGeneral%252FProduct%2520Owner%2520Materials%252FTesting%252FBug%2520Reports%252FAdvanced%2520Filter%2520Relative%2520Date%2520Filter%2520Bug.pptx%26baseUrl%3Dhttps%253A%252F%252Fmitre.sharepoint.com%252Fsites%252FCoVDT%26serviceName%3Dteams%26threadId%3D19%3A00d3d45c64ca457795d58c2764d517cd%40thread.skype%26groupId%3D7de0f318-3170-4f1c-82eb-95bfe132bfe9&type=fi …

Fix advanced filter date

---

app/javascript/components/patient/Patient.js
app/mailers/patient_mailer.rb

Contact method nil check

---

app/controllers/public_health_controller.rb

Fixes timezone issues when comparing dates from Advanced Search.

(FIX): Advanced Search Date Timezone Fixes

---

app/jobs/consume_assessments_job.rb
config/locales/en.yml
config/locales/es-PR.yml
config/locales/es.yml
config/locales/fr.yml
config/locales/so.yml

Update wording in max_retries_message and remove word 'daily' in the history item for max_retries voice

Message updates

---

app/javascript/components/public_health/CustomExport.js

fix custom export preset update

---

test/models/patient_test.rb

This was feedback on a recent PR that is now being handled separately. Just updating some new Patient tests to take advantage of their factories.

Updating patient tests to use factories.

---

public/Sara Alert Import Format.xlsx

Adjust font to be uniform
All tabs have A1 selected
All tabs open to A1
The blue columns in the header row have font size 11

Update Import Format

---

app/controllers/export_controller.rb
app/helpers/patient_details_helper.rb
app/javascript/components/public_health/ConfirmExport.js
app/javascript/components/public_health/CustomExport.js
app/javascript/components/public_health/Export.js
app/javascript/packs/stylesheets/bootstrap.scss
app/lib/import_export.rb
app/models/patient.rb
test/system/roles/public_health/dashboard/dashboard.rb
test/system/roles/public_health/dashboard/export_verifier.rb
test/system/roles/public_health/public_health_custom_export_test.rb
test/system/roles/public_health/public_health_test_helper.rb

- fix custom export csv format not exporting, include data type in filename for csv exports
- fix custom export load preset query
- update expected purge date logic in exports
- add custom export confirm modal
- basic system tests
Please describe the tests needed to verify …

Custom Export bug fixes, remaining items, and basic system tests

---

app/javascript/components/analytics/widgets/MonitoreesByEventDate.js

Quick fix to remove the analytics disclaimer in the ` Monitorees by Event Date` panel

removes disclaimer

---

config/initializers/filter_parameter_logging.rb

Filters History comments from the logs.

Filter history comments

---

app/models/assessment.rb

Updating method to fetch reports columns to use threshold conditions

---

app/views/user_mailer/download_email.html.erb

Jira Ticket: [SARAALERT-1031](https://tracker.codev.mitre.org/browse/SARAALERT-1031)
Update the language to match the functionality of the system. 
From the export menu select:
1. Excel Export for Purge-Eligble Monitorees
2. Excel Export for all Monitorees
Using Sidekiq verify that the new language is present in the generated email.

SARAALERT-1031: Update language on when exports are purged

---

config/twilio/assessment_studio_flow.json

This is just updating the copy of the studio flow json we keep into the repo to reflect the studio flow that will be used with 1.18 that includes max retries and opt out funcitonality.

Update studio flow json to version that has max retries and opt out

---

app/lib/import_export.rb

Fixes issue caused by loading all symptoms in custom export config
Remove query as it is unnecessary

Fix issue caused by loading all symptoms in custom export config

---

app/controllers/assessments_controller.rb
app/jobs/consume_assessments_job.rb
app/lib/import_export.rb

Additional safe navigation when plucking from conditions

---

app/javascript/components/layout/CustomTable.js

missing aria-label

---

config/initializers/filter_parameter_logging.rb

Filter value parameter from requests.

filter value parameter

---

app/javascript/components/analytics/PublicHealthAnalytics.js
app/javascript/components/analytics/widgets/MonitoreeFlow.js
app/javascript/tests/analytics/PublicHealthAnalytics.test.js
app/javascript/tests/analytics/widgets/MonitoreeFlow.test.js
app/javascript/tests/util.js

While updating other tests I noticed that the PublicHealthAnalytics and MonitoreeFlow components' test suites were not fully fleshed out like our other ones.  Added complete test suites for those two component
`PublicHealthAnalytics.test.js`
- fully fleshed test suite
`PublicHealthAnalyticst.js`
- added loading spinner to export button
- additional cleanup
`MonitoreeFlow.test.js`
- fully fleshed test suite
`MonitoreeFlow.js`
- small cleanup
`utils.js`
- additional date formatter util method
Please describe the tests needed to verify your changes. …

Updated test suites

---

app/javascript/tests/public_health/Export.test.js

Fixes broken Export component test on 1.21.

export component test fix

---

.github/PULL_REQUEST_TEMPLATE.md

No Jira ticket. I just added @holmesie 's guidance for titling PRs to the template.

Add PR title guidance to PR template

---

app/controllers/user_filters_controller.rb
app/helpers/patient_query_helper.rb
app/javascript/components/public_health/query/AdvancedFilter.js
app/javascript/packs/stylesheets/bootstrap.scss

Jira Ticket: [SARAALERT-1063](https://tracker.codev.mitre.org/browse/SARAALERT-1063)
Add age filter to advanced filter.
- Add Age filter to the advanced filter dropdown
- Add between option to number type advance filter that is included/excluded by a flag
- Overall refactor to account for styling
- Add age filter functionality by using age to filter on DOB
Please describe the tests needed to verify your changes. Provide instructions for reproducing these tests. List any relevant details for your test …

SARAALERT-1063: Add "Age" Advanced Filter

---

app/javascript/components/public_health/query/AdvancedFilter.js

Updated tooltip language for [SARAALERT-1063](https://tracker.codev.mitre.org/browse/SARAALERT-1063)

SARAALERT-1063 (Update): Advanced Filter Age Tooltip

---

app/controllers/import_controller.rb
app/helpers/patient_query_helper.rb
app/javascript/components/enrollment/steps/Exposure.js
app/javascript/components/public_health/PatientsTable.js
app/javascript/components/public_health/actions/UpdateAssignedUser.js
app/javascript/components/public_health/query/AssignedUserFilter.js
app/javascript/components/subject/monitoring_actions/AssignedUser.js
app/javascript/components/util/InfoTooltip.js
app/models/patient.rb
docs/api/api-release-notes.md
lib/tasks/demo.rake
test/controllers/public_health_controller_test.rb
test/fixtures/files/fhir_invalid_patient.json
test/system/roles/enroller/enrollment/form_validator.rb
test/system/roles/public_health/dashboard/import_verifier.rb
test/system/roles/public_health/public_health_patient_page_test.rb

Jira Ticket: [SARAALERT-428](https://tracker.codev.mitre.org/browse/SARAALERT-428)
Increases allowed length of assigned user field to 6

SARAALERT-428: Increase digit length of assigned user field to 6

---

docs/api/api-coming-soon.md
docs/api/api-release-notes.md

This updates the API documentation in preparation for the release of 1.22.0.
- Updated to correctly reflect coming soon in 1.23.0
- Added release notes section for  1.22.0

API Documentation Updates for 1.22.0

---

app/javascript/components/patient/Patient.js

Update show details aria-label in monitoree details

Update show monitoree details expander aria-label

---

.gitignore
lib/tasks/demo.rake

Jira Ticket: SaraAlert-1286
Add rake tasks to backup and restore database, as well as a rake task to bulk copy patient resources.

SARAALERT-1286: Add Rake Tasks for Database Backup/Restore & Bulk Duplicate

---

app/javascript/components/layout/CustomTable.js
app/javascript/packs/stylesheets/custom_table.scss
app/models/assessment.rb
app/models/close_contact.rb
app/models/contact_attempt.rb
app/models/history.rb
app/models/laboratory.rb
app/models/transfer.rb
config/sara/sara.yml
test/factories/history.rb
test/models/assessment_test.rb
test/models/close_contact_test.rb
test/models/contact_attempt_test.rb
test/models/history_test.rb
test/models/laboratory_test.rb
test/models/transfer_test.rb

Jira Ticket: [SARAALERT-1240](https://tracker.codev.mitre.org/browse/SARAALERT-1240)
Adding/updating any associated records (labs, close contacts, histories, etc) with a Patient should prevent the patient from being purge eligible

SARAALERT-1240: Update patient updated_at upon modification of associated records

---

app/javascript/components/assessment/steps/SymptomsAssessment.js

Jira Ticket: SARAALERT-1239
In mobile safari there is an IndexSizeError exception that sometimes occurs with boolean checkboxes for symptoms that the monitoree reports.
I was unable to reproduce the issue
I addressed a duplicate key error and changed the if statement when checking the booleans such that if it is undefined it will no longer pass the check

SARAALERT-1239: Investigate Sentry Error related to weblink assessment

---

docs/api/api-coming-soon.md
docs/api/api-release-notes.md
docs/api/walkthrough-testing-the-backend-services-workflow.md

This updates the API documentation to be accurate with respect to the release of 1.23.0. It also adds some minor updates to the backend services workflow walkthrough.
- Update coming soon for 1.24.0
- Update release notes for 1.23.0
`walkthrough-testing-the-backend-services-workflow.md`
- Fix up the example JWTs to be more accurate and slightly more clear

API Documentation Updates for 1.23

---

.github/workflows/static.yml
.github/workflows/test.yml

See issue here: https://github.com/actions/virtual-environments/issues/1816. This should fix failing pipelines. Will separately work on longterm solution.

Reverting runner version back to 18.04 to guarantee correct mysql version.

---

app/models/patient.rb
test/models/patient_test.rb

Jira Ticket: SARAALERT-1249
Use time zone information on the database side to improve the `close_eligible` scope. The existing patient tests for `close_eligible` should not be affected by this. I'd still like to read through those tests and make sure they are as comprehensive as we want them to be.
Depends on: https://github.com/SaraAlert/SaraAlert/pull/634
`patient.rb`
- added `submitted_assessment_today` scope
- added `end_of_monitoring_period` scope
- changed `close_eligible` to ONLY use scopes and not instantiate patients in rails

SARAALERT-1249: Close eligible improvement

---

app/javascript/components/patient/Patient.js

Added an aria label to the monitoree name for screen readers

Added aria-label to monitoree name

---

app/javascript/components/patient/Patient.js
app/models/vaccine.rb
test/models/vaccine_test.rb

Removes date range validation on Vaccine `administration_date` due to issues relating to user timezone.

(Bugfix) Vaccine Administration Date Validation Fix

---

app/javascript/components/close_contact/CloseContact.js
app/javascript/components/laboratory/Laboratory.js
app/views/patients/show.html.erb

Jira Ticket: [SARAALERT-1367](https://tracker.codev.mitre.org/browse/SARAALERT-1367)
Update tables on the monitoree page for consistency.  The following changes were applied to the lab results and close contacts table:
- Move "add button" to above table
- Move actions column to the far left column
- Move notes to the far right column
`CloseContact.js`
- Removed unnecessary left padding (caused the button to not be aligned)
`show.html.erb`
- Made changes listed above to lab and close contact tables …

SARAALERT-1367: Update monitoree tables for consistency

---

app/javascript/components/admin/AuditModal.js
app/javascript/components/analytics/PublicHealthAnalytics.js
app/javascript/components/analytics/widgets/Demographics.js
app/javascript/components/analytics/widgets/ExposureSummary.js
app/javascript/components/analytics/widgets/MonitoreesByEventDate.js
app/javascript/components/assessment/AssessmentTable.js
app/javascript/components/history/History.js
app/javascript/components/laboratory/Laboratory.js
app/javascript/components/patient/vaccines/VaccineModal.js
app/javascript/components/patient/vaccines/VaccineTable.js
app/javascript/components/public_health/PatientsTable.js
app/javascript/components/subject/LastDateExposure.js
app/javascript/components/subject/household_actions/ApplyToHousehold.js
app/javascript/components/subject/household_actions/MoveToHousehold.js
app/javascript/components/util/EligibilityTooltip.js
app/javascript/tests/analytics/PublicHealthAnalytics.test.js
app/javascript/tests/patient/Patient.test.js
app/javascript/tests/subject/household_actions/ApplyToHousehold.test.js
app/javascript/tests/subject/monitoring_actions/PublicHealthAction.test.js
app/javascript/tests/util.js
app/javascript/utils/Analytics.js
app/javascript/utils/DateTime.js
app/views/patients/show.html.erb

Jira Ticket: SARAALERT-654
This PR adds a location for Utility Files. These files will contain functions that are used commonly used in the application. After all, it doesn't make sense for multiple files to define the same function over and over. Not only does this duplicate work, but it makes it likely that inconsistent behavior/bugs could develop. 
Additional changes include some minor tweaks to some Analytics Code (see explanation below), as well as formatting and alphabetizing `import` statements.
`app/javascript/components/admin/AuditModal.js`
- Formatted Import statements and changed the component to use `formatTimestamp()` utility function
`app/javascript/components/analytics/PublicHealthAnalytics.js`
- Formatted Import statements …

SARAALERT-654: Adds Utility Helper Files

---

test/models/patient_test.rb

Fixes failing test introduced in [SARAALERT-711](https://github.com/SaraAlert/SaraAlert/pull/745)
**Submitter:**
@holmesie  :
@ :
@ :

Fix patient tests

---

app/javascript/components/close_contact/CloseContact.js

Jira Ticket: [SARAALERT-1374](https://tracker.codev.mitre.org/browse/SARAALERT-1374)
Replace "reporting method" with "contact method" in info button text.  Text should be: "Please enter at least one name (First Name or Last Name) and at least one contact method (Phone Number or Email)."
`CloseContact.js `
- Changed tooltip text from "reporting method" to "contact method"
**Submitter:**
**Reviewer 1:**
Username: @DPC15038 
**Reviewer 2:**
Username: @hackrm 
**Reviewer 3:**
Username: @dubem7

SARAALERT-1374: update close contact create button tooltip text

---

config/initializers/filter_parameter_logging.rb

Filter out sensitive notes param of contact attempt

Add note param of contact attempt to filtering

---

docs/api/api-coming-soon.md

This updates the API documentation for 1.25.0. Nothing API related is released in 1.25.0, the two planned tasks were pushed to 1.25.0, so the only necessary change is the version number. 
- Update version number to 1.26.0.
**Submitter:**
- (N/A) This PR includes the correct JIRA ticket reference.
- (N/A) Tests are included and test edge cases
- (N/A) Tests have been run locally and pass (remember to update Gemfile when applicable)
- (N/A) Test fixtures updated and documented as necessary
@tstrass

API Documentation Updates for 1.25.0

---

app/javascript/components/public_health/query/AdvancedFilter.js

adds a period to the SMS Blocked advanced filter text

---

app/controllers/export_controller.rb
app/helpers/vaccine_query_helper.rb
app/javascript/components/public_health/CustomExport.js
app/lib/import_export.rb
app/lib/import_export_constants.rb
app/models/history.rb
app/models/laboratory.rb
test/fixtures/vaccines.yml
test/helpers/vaccine_query_helper_test.rb
test/system/roles/public_health/dashboard/export_verifier.rb
test/system/roles/public_health/public_health_custom_export_test.rb

Jira Ticket: [SARAALERT-1261](https://tracker.codev.mitre.org/browse/SARAALERT-1261)
This PR adds support for exporting vaccine table information via:
* Custom Export
* Excel Export for All Monitorees
* Excel Export for Purge-Eligible Monitorees
* Single Monitoree Excel Export
So that users can now export vaccine data to Excel as they can other data.
Vaccinations are now available in custom export:
`export_controller.rb`
- Added vaccination info to `full_history_patients` and `custom_export` functions.
`import_export_constants.rb`
- Added constants containing vaccine fields, headers, and export options.
`import_export.rb`
- Added vaccines to `get_export_data` function.
`export_verifier.rb`
- Updated system test verifiers so that vaccination table export is verified in system tests. …

SARAALERT-1261: Support export of vaccine table information

---

app/javascript/components/public_health/PublicHealthHeader.js

Fixes import guidance link in isolation and uncomment system tests for it
Go to isolation monitoring page and try to download import formatting guidance
Fix url for download
**Submitter:**
@holmesie  :

Fix import guidance link in isolation

---

app/controllers/fhir/r4/api_controller.rb

Jira Ticket: [SARAALERT-1236](https://tracker.codev.mitre.org/browse/SARAALERT-1236)
This wraps saving of Patient/CloseContact and saving of History in a transaction. This way if saving the History fails for some reason, we will roll back the saving of the Patient/CloseContact. This will also align behavior better with client expectations; if a client gets a 500 response, they would not expect the POST request to have succeeded.
We already had transactions in the update method, so this just adds them to the create method as well.
You can manually test this like so:
- Run a `Patient.count` in the rails console
- Add a `throw StandardError` in the Patient Create transaction, _after_ the call to save the Patient.
- Send a valid patient POST request to the API. You should get a 500 response. …

SARAALERT-1236 API Create Transactions

---

lib/tasks/demo.rake
performance/docker/build-push-1m-database-image.sh
performance/generate_performance_db.sh

Please title your PR like `SARAALERT-<Jira number>: <title>`, and include all numbers if the PR covers more than one, e.g. `SARAALERT-1, SARAALERT-2: <title>`. If the PR is not related to a Jira task, just give it a descriptive title.
This fix was tested on the …

Performance population: improve user population

---

app/javascript/components/admin/AdminTable.js

Admin panel only exports the first 25 users as a result of this change: https://github.com/SaraAlert/SaraAlert/pull/756
Default the filter to "All" so we can grab the total number of users (no filters applied) and then use that number on the export
**Submitter:**
@ : @holmesie

Admin Panel Export Bug

---

docs/api/api-coming-soon.md
docs/api/api-release-notes.md

This updates the API documentation (specifically release notes and coming soon) for the 1.26.0 release.
- Document newly released features
- Update version number to 1.27
**Submitter:**
- [N/A] This PR includes the correct JIRA ticket reference.
- [N/A] If UI changes have been made, Chrome Dev Tools Lighthouse accessibility test has been executed to ensure no 508 issues were introduced.
- [N/A] Tests are included and test edge cases
- [N/A] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [N/A] Test fixtures updated and documented as necessary
@tstrass

API Documentation Updates for 1.26.0

---

app/javascript/components/util/DateInput.js

Fix to make min/max dates included in isValid datepicker check
EX: 01/01/1900 is a valid DOB and does not clear out

Datepicker 1/1/1900 bugfix

---

app/javascript/components/layout/Header.js
app/views/layouts/application.html.erb
app/views/layouts/doorkeeper/admin.html.erb
app/views/layouts/doorkeeper/application.html.erb

Fixes an issue with the header routing to `//` instead of just `/`.

removes improper header routing

---

app/controllers/fhir/r4/api_controller.rb

Jira Ticket: [SARAALERT-1236](https://tracker.codev.mitre.org/browse/SARAALERT-1236)
Previous PR where bug was introduced: https://github.com/SaraAlert/SaraAlert/pull/783
This fixes a bug where we were getting errors like this in sidekiq:
```
ActiveJob::DeserializationError: Error while trying to deserialize arguments: Couldn't find Patient with 'id'=11067
```
The problem was that I added a transaction in the `Patient#create` method, and the call to enqueue sending the enrollment message was inside the Transaction scope. The Patient doesn't save until the transaction scope ends, and so the job was trying to access the Patient before it was saved to the database.
- Checkout branch `1.27.0`
- Run sidekiq locally alongside the app
- Insert a `byebug` right after the call to send the …

SARAALERT-1236 API Transaction Bugfix

---

app/javascript/components/enrollment/steps/Address.js

Jira Ticket: SARAALERT-562
Fixes bug where first positive lab is not saved if address is copied in enrollment
- enroll an isolation monitoree
- choose asymptomatic enrollment path and enter a lab result
- on the review screen, go to the address screen
- edit the address, then click "copy from home address"
- go back to the review screen and save the record
- the lab result won't show up
Copy first positive lab over when calling setState
**Submitter:**
@holmesie  :
@sgober  :
@ :

BUGFIX: First positive lab is not saved if monitored address is copied

---

app/javascript/components/assessment/steps/AssessmentCompleted.js
app/javascript/tests/assessment/steps/AssessmentCompleted.test.js

Jira Ticket: [SARAALERT-1373](https://tracker.codev.mitre.org/browse/SARAALERT-1373)
Updated checkmark on successful assessment to be green (see mockups in the JIRA)
To tests this, use the patient id in the URL in the rails console to get their `submission_token` and `jurisdiction` (grab the unique identifier here).  Then go to `/patients/{submission_token}/{jurisdiction uuid}`.
Before:
After:
**Submitter:**
@dubem7  :
@hackrm  :
@holmesie  :

SARAALERT-1373: Make "Report Submitted" Checkmark Green

---

app/helpers/patient_details_helper.rb
app/javascript/components/enrollment/steps/Exposure.js
app/javascript/components/util/InfoTooltip.js
app/javascript/packs/stylesheets/enrollment.scss
app/lib/import_export.rb
app/lib/import_export_constants.rb
lib/tasks/demo.rake
test/system/form_data/monitorees.yml
test/system/roles/enroller/enrollment/form_validator.rb
test/system/roles/enroller/enrollment/steps.rb

PO team wants 'No Symptom History' to be renamed to 'No Reported Symptoms'
**Submitter:**
@holmesie  :
@sgober  :
@tstrass  :

FIX: Rename no_symptom_history to no_reported_symptoms

---

app/controllers/admin_controller.rb
app/javascript/components/admin/AdminTable.js
app/javascript/components/admin/UserModal.js
app/javascript/packs/stylesheets/custom_table.scss
app/javascript/utils/Export.js
app/models/user.rb
db/migrate/20210404213440_add_notes_to_users.rb
db/schema.rb
lib/tasks/demo.rake
test/controllers/admin_controller_test.rb

Jira Ticket: [SARAALERT-1334](https://tracker.codev.mitre.org/browse/SARAALERT-1334)
This ticket adds notes to the users, which can be viewed in the admin panel. 
AdminTable.js - Added the display of the notes. Should be able to expand and collapse nots individually.
UserModal.js - Added the input for notes. It is capped at 5000 characters.
AdminController.rb - Add notes field and modify create_user and edit_user
**Submitter:**
@sgober :
@timwongj  :
@tstrass  :

SARAALERT-1334: Add notes to user

---

docs/api/api-coming-soon.md
docs/api/api-release-notes.md

This updates the API documentation (specifically release notes and coming soon) for the 1.27.0 release.
* Document newly released features
* Update version number to 1.27
* You can see that in the `api-release-notes.md`, I'm moving a bullet from the 1.26.0 release to the 1.27.0 release. This was because I made a mistake on the last set of release notes, that bullet shouldn't have been there.
* I've added both @tstrass and @holmesie as reviewers, but I don't think this needs 2 reviews, just figured whoever saw it first could take it.
**Submitter:**
- N/A This PR includes the correct JIRA ticket reference.
- N/A If UI changes have been made, Chrome Dev Tools Lighthouse accessibility test has been executed to ensure no 508 issues …

API Documentation Updates for 1.27.0

---

app/controllers/fhir/r4/api_controller.rb
app/controllers/vaccines_controller.rb
app/helpers/fhir_helper.rb
app/helpers/validation_helper.rb
app/models/vaccine.rb
app/views/patients/show.html.erb
config/initializers/doorkeeper.rb
config/vaccines.yml
docs/api/api-specification.md
docs/api/index.md
test/controllers/fhir/r4/api_controller_test.rb
test/controllers/fhir/r4/immunization_test.rb
test/controllers/vaccines_controller_test.rb
test/fixtures/vaccines.yml
test/models/vaccine_test.rb

Jira Ticket: [SARAALERT-1262](https://tracker.codev.mitre.org/browse/SARAALERT-1262)
This PR adds support for an [Immunization](https://www.hl7.org/fhir/immunization.html) endpoint on the FHIR API. This endpoint can be used to read and write vaccine data elements.
* Support a `GET` for Immunizations in the `show` method
* Support a `PUT` and `PATCH` for Immunizations in the `update` method
* Support a `POST` for Immunizations in the `create` method
* Support a `GET` for Immunizations  with params in the `search` method
* Update the `all` method to include Immunizations
* Update the `capability_statement` and `well_known` methods to include Immunizations
* Refactor several of the `get_<model>` methods into one function
`fhir_helper.rb`
* Add a `vaccine_as_fhir` method …

SARAALERT-1262: Support vaccines in the API

---

app/controllers/import_controller.rb
app/models/patient.rb

1. Validate user provided jurisdiction path with jurisdictions in db, can't get rid of this one
```
CACHE Jurisdiction Load (0.0ms)  SELECT `jurisdictions`.* FROM `jurisdictions` WHERE `jurisdictions`.`path` = 'USA' ORDER BY `jurisdictions`.`id` ASC LIMIT 1
↳ app/controllers/import_controller.rb:249:in `validate_jurisdiction'
```
2. Calling `Patient.valid?` automatically invokes this query which validates `jurisdiction_id`. This is somewhat redundant and unnecessary, but the only way I know how to remove it is by adding `:validate => false` to `belongs_to :jurisdiction` which I'm not sure if we want to do
```
CACHE Jurisdiction Load (0.0ms)  SELECT `jurisdictions`.* FROM `jurisdictions` WHERE `jurisdictions`.`id` = 1 LIMIT 1
↳ app/controllers/import_controller.rb:91:in …
```

duplicate detection performance improvements

---

app/controllers/fhir/r4/api_controller.rb
app/helpers/fhir_helper.rb

Jira Ticket: [SARAALERT-1392](https://tracker.codev.mitre.org/browse/SARAALERT-1392)
The changes in this PR improve API search performance by utilizing eager loading and removing/consolidating redundant queries
`app/controllers/fhir/r4/api_controller.rb`
- eager loading, remove unnecessary/redundant queries
`app/helpers/fhir_helper.rb`
- replace unnecessary jurisdiction query with `jurisdiction[:path]`
**Submitter:**
@ngfreiter :
@tstrass :
@holmesie :

SARAALERT-1392: API search performance

---

app/views/patients/monitoree_unavailable.html.erb

Updated language per request of the PO team

Monitoree unavailable landing page updates

---

app/mailers/patient_mailer.rb

Very small PR changing `HoH` to "head of household"

HoH -> head of household

---

lib/tasks/demo.rake

Jira Ticket: Follow up on [SARAALERT-1354](https://github.com/SaraAlert/SaraAlert/pull/817)
The changes from [this PR](https://github.com/SaraAlert/SaraAlert/pull/817) were incorrect in that the timestamp of the updated query for existing patients should have been the beginning of the current day instead of the end of the current day - the UTC offset.
1. Run the demo script
2. Run `Patient.first.dependents.size` and notice that it's unexpectedly large
Use `DateTime` instead of `Time` to define the `beginning_of_day` for each loop to get rid of inconsistencies between dates and timestamps, causing some of the querying logic to be off
Run this query in the rails console to make sure no household (especially the first) is unexpectedly too large
```
Patient.group(:responder_id).count.sort_by …
```

BUGFIX: Households in demo script

---

config/twilio/assessment_studio_flow.json

Pull requests into Sara Alert require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.
Prepend your PR title like `SARAALERT-<Jira number>: <title>`, and include all tickets if the PR covers more than one, e.g. `SARAALERT-1, SARAALERT-2: <title>`. If the PR is not related to a Jira task, just give it a descriptive title.
When assigning a reviewer, tag their GitHub username in the reviewer checklist section below.
Insert description for the …

Update studio flow

---

app/controllers/patients_controller.rb

When trying to access an invalid patient, `@patient.jurisdiction` results in an error because `@patient` is `nil`
Visit any patient page and replace patient id in link with an invalid patient id
Access `@patient.jurisdiction` after `nil` check
**Submitter:**
@ :
@ :
@ :

BUGFIX: nil patient jurisdiction error on patient page

---

app/javascript/components/public_health/query/AdvancedFilter.js

Somehow a linter violation got in.

Fix prettier issue in AdvancedFilter.js

---

config/twilio/assessment_studio_flow.json

Pull requests into Sara Alert require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.
Prepend your PR title like `SARAALERT-<Jira number>: <title>`, and include all tickets if the PR covers more than one, e.g. `SARAALERT-1, SARAALERT-2: <title>`. If the PR is not related to a Jira task, just give it a descriptive title.
When assigning a reviewer, tag their GitHub username in the reviewer checklist section below.
Insert description for the …

Add SINGLE_SMS iterator to studio flow json

---

docs/api/api-coming-soon.md
docs/api/api-release-notes.md

This updates the release notes and coming soon for 1.28.0.
* Update coming soon for 1.29.0
* Update release notes with 1.28.0 features.
**Submitter:**
@tstrass 
@holmesie 
As with other doc updates, @holmesie or @tstrass, whichever one of you gets to this first and approves can feel free to merge. I don't think we need 2 reviews.

API Documentation Updates for 1.28.0

---

app/javascript/components/patient/Patient.js
app/javascript/tests/patient/Patient.test.js

Jira Ticket: [SARAALERT-456](https://tracker.codev.mitre.org/browse/SARAALERT-456)
As straightforward as the PR title, added Sara Alert Id to the identification section of the monitoree details. PO team is getting feedback for what exactly is wanted on the dashboard and that will be a separate ticket.
**Submitter:**
@DPC15038 :
@mdube7 :
@holmesie :

SARAALERT-456: Make the Monitoree ID visible from the Details Page

---

db/migrate/20210429200726_update_foreign_key_types.rb
db/schema.rb

Jira Ticket: [SARAALERT-1443](https://tracker.codev.mitre.org/browse/SARAALERT-1443)
Update foreign key types to be consistent with primary key types
**Submitter:**
@jkufro :
@holmesie  :
@bialogs :

SARAALERT-1443: Update foreign key types

---

app/javascript/components/analytics/widgets/MonitoreeFlow.js
app/javascript/components/analytics/widgets/PreferredReportingMethod.js
app/javascript/tests/analytics/widgets/MonitoreeFlow.test.js
app/javascript/utils/Analytics.js

Jira Ticket: [SARAALERT-374](https://tracker.codev.mitre.org/browse/SARAALERT-374)
This ticket was mostly done in #834. This just adds percentages into the table to address feedback from feature review.
Reviewers please verify that the percentages are correct. Percentages should be in the scope of each cell's column and workflow.
`monitoree_flow.js`
- Calculate percentages for each table cell and display them in the table
**Submitter:**
@sgober :
@DPC15038 :
@holmesie :

SARAALERT-374 analytics workflow change percentages

---

config/twilio/assessment_studio_flow.json

Add timeout to SINGLE_SMS and add quotes to retry error_code post

---

app/lib/import_export.rb

The activestorage PR introduced a bug with the exported symptom columns where `nil` symptom names and labels were not being filtered out properly
Perform an export with symptoms
Fix the symptoms query
**Submitter:**
@holmesie  :
@tstrass  :
@Bialogs  :

fix exported symptom columns

---

docs/api/api-coming-soon.md
docs/api/api-release-notes.md
docs/api/nbs-api-specification.md

Jira Ticket: [SARAALERT-1414](https://tracker.codev.mitre.org/browse/SARAALERT-1414)
This PR is just some follow up documentation updates from #823 per comments from the PO team. Some minor grammar tweaks, and the significant change is that we now list out exactly which Sara Alert data elements are exported to PHDC.
`nbs-api-specification.md`
- Grammar tweaks and added a list of which data elements are exported via PHDC
**Submitter:**
@tstrass 
@holmesie

SARAALERT-1414: Bulk PHDC Export (documentation updates)

---

app/controllers/laboratories_controller.rb
app/javascript/components/patient/laboratory/Laboratory.js
app/javascript/components/patient/laboratory/LaboratoryModal.js
app/javascript/components/util/DeleteDialog.js
app/javascript/packs/stylesheets/layout.scss
config/routes.rb
test/controllers/laboratories_controller_test.rb

Jira Ticket: SARAALERT-648
Added delete function for lab results. Test by creating lab results, deleting them and making surer that the information captured in the new history items is correct.
**Submitter:**
@hackrm :
@sgober :
@ :

SARAALERT-648: lab delete

---

performance/benchmark.rb

Pull requests into Sara Alert require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.
Prepend your PR title like `SARAALERT-<Jira number>: <title>`, and include all tickets if the PR covers more than one, e.g. `SARAALERT-1, SARAALERT-2: <title>`. If the PR is not related to a Jira task, just give it a descriptive title.
When assigning a reviewer, tag their GitHub username in the reviewer checklist section below.
Insert description for the …

Rubocop fixes

---

app/javascript/components/public_health/PublicHealthHeader.js

This PR updates the Formatting Guidance Date.

updates the date for the formatting guidance

---

app/controllers/histories_controller.rb
app/controllers/laboratories_controller.rb
test/controllers/histories_controller_test.rb
test/controllers/laboratories_controller_test.rb

Updated history and laboratory controller error firing and updated the controller tests accordingly.  Also added tests for the `before_action` checks in both controllers.
**Submitter:**
@tstrass :
@ :
@ :

History and laboratory controller test updates

---

app/controllers/laboratories_controller.rb
app/controllers/vaccines_controller.rb
app/javascript/components/layout/Breadcrumb.js
app/javascript/components/patient/PatientPage.js
app/javascript/components/patient/assessment/AssessmentTable.js
app/javascript/components/patient/export/DownloadMonitoree.js
app/javascript/components/patient/vaccines/VaccineModal.js
app/javascript/components/patient/vaccines/VaccineTable.js
app/views/patients/show.html.erb
config/routes.rb
test/controllers/vaccines_controller_test.rb

Jira Ticket: [SARAALERT-1441](https://tracker.codev.mitre.org/browse/SARAALERT-1441)
Supports the ability to delete entries from the vaccine table and tracks deletions with a history item.
https://user-images.githubusercontent.com/35042815/118548735-9d443580-b728-11eb-8c1d-85374b020d71.mov
Added support for deleting a vaccine: `VaccineTable.js`, `vaccines_controller.rb`, `routes.rb`
Updated controller tests to reflect addition of destroy and before_action additions: `vaccines_controller_test.rb`
General vaccination component cleanup (consolidated code, clarified variable names, etc): `VaccineTable.js`, `VaccineModal.js`
Standardized …

SARAALERT-1441: Ability to delete vaccination entries

---

app/javascript/components/patient/vaccines/VaccineTable.js

Fixed missing linting fix in `VaccineTable.js`

spacing fix in vaccine table

---

app/controllers/close_contacts_controller.rb
test/controllers/close_contacts_controller_test.rb

Jira Ticket: SARAALERT-767-Addendum
Adds the enrolled ID to deletion history objects for close contacts.  
- app/controllers/close_contacts_controller.rb - adds the relevant field to the comment string. 
**Submitter:**
@ :
@ :
@ :

added enrolled status to deletion history for enrolled close contacts

---

app/models/concerns/date_validator.rb
test/models/patient_test.rb

If date is numeric, then the date will not be validated properly and may pass a "zero date" to the database and cause strange errors throughout the app. This PR adds an extra validation within the DateValidator and a new test case for it.
"Zero Dates" MySQL docs https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html
SQL Modes docs https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html
1. Set the mysql config to what we think Aurora DB is
https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html
```
mysql -u root
SET GLOBAL sql_mode = '';
SET SESSION sql_mode = '';
SHOW VARIABLES LIKE 'sql_mode';
SELECT @@GLOBAL.sql_mode;
SELECT @@SESSION.sql_mode;
use disease_trakker_development;
select id, date_of_birth from patients where id = 1;
UPDATE `patients` …
```

Add check in DateValidator to ensure value is not numeric

---

app/lib/import_export.rb

Jira Ticket: [SARAALERT-1495](https://tracker.codev.mitre.org/browse/SARAALERT-1495)
Exports for reports that have blank symptoms (e.g. one's created via SMS text or phone call) are incorrectly exporting with values of false instead of blank.
Go to patient page of any patient and find any assessment id and run this in the rails console to clear all the symptom values of that assessment:
```
Assessment.find(5).reported_condition.symptoms.update(bool_value: nil)
```
Perform an individual or some other kind of export which includes assessments and symptoms
Account for case when symptom value is NULL
- Example change (ex: …

symptoms with nil values should be exported as blank instead of false

---

lib/tasks/demo.rake

Fixes issue where `latest_assessment_symptomatic` for patients is incorrect when generating data with demo script. This is because the query responsible for updating this field only sets this value to TRUE (after each day) and does not set it to FALSE if new assessments that are not symptomatic are created
Run the demo script from a clean database:
```
bundle exec rake db:drop db:create db:schema:load admin:import_or_update_jurisdictions demo:setup demo:populate
```
Compare these values in the rails console:
```
Patient.where(latest_assessment_symptomatic: true).size
```
```
s = 0
Patient.all.find_each { |p| s += 1 if p.assessments.last&.symptomatic  }
s
```
Reset `latest_assessment_symptomatic` to FALSE before performing the query for updating it to TRUE for relevant …

BUGFIX: Fix latest_assessment_symptomatic population in demo script

---

.github/workflows/performance.yml
.gitignore
Gemfile
Gemfile.lock
performance/aggregate_benchmark_results.rb
performance/benchmark.rb
performance/benchmarks/output/.gitignore
performance/collect_benchmark_results.rb

For performance benchmarks this PR will make it so that we now generate JSON describing test results and save them to artifacts. This PR also includes two scripts: one that pulls down and unpacks all relevant artifacts, and another that aggregates all of the data into an excel workbook.
To test the scripts, you will need to create a GitHub access token that has "workflow" permissions and set `export PERSONAL_TOKEN='<token value>'`.
`.github/workflows/performance.yml`
- hold artifacts for 14 days
`.gitignore`
- added gitignores for performance stuffs
`performance/collect_benchmark_results.rb`
- Collects all …

SARAALERT-NONE Benchmark artifacts

---

docs/api/api-coming-soon.md

Update coming soon in the API docs.
- Change 1.31 to 1.32
N/A

SARAALERT-NONE: 1.31.0 API Documentation Updates

---

app/controllers/application_api_controller.rb
app/controllers/fhir/r4/api_controller.rb
app/helpers/fhir_helper.rb
app/models/history.rb
config/initializers/doorkeeper.rb
docs/api/fhir-api-specification.md
docs/api/index.md
test/controllers/fhir/r4/api_controller_test.rb
test/controllers/fhir/r4/provenance_test.rb

Jira Ticket: SARAALERT-1425
Adds the ability for users to access history items via the api, returning FHIR Provenance resources (IG: https://www.hl7.org/fhir/provenance.html). They can be accessed directly by local ID using /fhir/r4/Provenance/[:id], can be searched for by Patient, and are part of the $everything for patients to which they belong. 
-api_controller.rb: the meat of the changes, adds functionality to show specific histories and search for them via the api, as well as adding them as content to the $everything endpoint for patients. 
-fhir_helper.rb: adds code to convert our histories into FHIR Provenance resources. 
**Submitter:**
@ngfreiter 
@tstrass  :
@holmesie  :

SARAALERT-1425: Support ability for users to read history in API

---

app/views/patient_mailer/assessment_email.html.erb
app/views/patient_mailer/enrollment_email.html.erb

Jira Ticket: [SARAALERT-1428](https://tracker.codev.mitre.org/browse/SARAALERT-1428)
This is an addition to the recent [PR for 1428](https://github.com/SaraAlert/SaraAlert/pull/925)
The jurisdiction contact info was displaying after each member of the household. The PO team would like it to appear just once, at the bottom.
Use rails console to send reports. 
Contact info in English:
```
user = User.new(email: 'foobar@foobar.foo', password: 'foobarfoobar2')
test_patient = Patient.new(creator: user)
test_patient.responder = test_patient
test_patient.email = '<test_email>'
test_patient.submission_token = SecureRandom.urlsafe_base64[0, 10]
test_patient.jurisdiction = Jurisdiction.where(name: 'County 1').first
test_patient.save!
test_patient2 = Patient.new(creator: user) …
```

SARAALERT-1428: bugfix Fix contact info for HoH emails

---

app/javascript/components/enrollment/steps/Exposure.js
app/javascript/components/patient/assessment/actions/ClearAssessments.js
app/javascript/components/patient/assessment/actions/CurrentStatus.js
app/javascript/components/patient/assessment/actions/MonitoringPeriod.js
app/javascript/components/patient/assessment/actions/SymptomOnset.js
app/javascript/components/patient/laboratory/LaboratoryModal.js
app/javascript/components/util/DeleteDialog.js
app/javascript/components/util/InfoTooltip.js
app/javascript/data/advancedFilterOptions.js
app/javascript/tests/patient/assessment/actions/ClearAssessments.test.js
app/javascript/tests/patient/assessment/actions/CurrentStatus.test.js
app/javascript/tests/util/DeleteDialog.test.js
app/models/history.rb

Jira Ticket: [SARAALERT-1436](https://tracker.codev.mitre.org/browse/SARAALERT-1436)
- "Symptom Onset Date" should be capitalized everywhere in the app
- No sympton onset/positive lab should be a soft warning instead
Slack thread for context: https://mitrecorp.slack.com/archives/C01A6P94R9B/p1624031526110400
**Submitter:**
@sgober :
@holmesie :
@tstrass :

SARAALERT-1436: address follow-up feedback from PO team

---

app/helpers/patient_details_helper.rb
app/lib/import_export_constants.rb

Jira Ticket: [SARAALERT-1474](https://tracker.codev.mitre.org/browse/SARAALERT-1474)
Export follow-up reason and follow-up note.
- Only in custom export
- New grouping for "Follow-up Flag"
This is follow-on work to #899.
`import_export_constants.rb`
- Add new follow-up fields and grouping in custom export
**Submitter:**
@hackrm:
@jkufro:
@holmesie:

SARAALERT-1474: Export Follow-up Flag

---

config/credential_handler.rb

When we verify the `aud` value that is sent to `/oauth/token`, we check that value against the URL that the client is making their POST request to. When that POST URL contains URL encoded params, we were not correctly ignoring those params when checking against the `aud`, so the `aud` value would never be able to match the POST URL, since it is sent as a parameter that is part of the POST URL. This fixes that bug by ignoring the params of the URL when comparing to the `aud`. 
To replicate, it is easiest to just add a URL parameter to the URL you are POSTing to when making an auth request. The param does not need to be relevant, it can just be something like: `http://localhost:3000/oauth/token?test=hello`. If you try this on `1.33.0`, you will see that the auth fails with …

SARAALERT-NONE: Fix aud authentication bug

---

app/helpers/validation_helper.rb
app/javascript/tests/mocks/mockMonitoringReasons.js

Jira Ticket: [SARAALERT-1469](https://tracker.codev.mitre.org/browse/SARAALERT-1469)
Added new reason for closure: "Fully Vaccinated."
`app/helpers/validation_helper.rb`
`app/javascript/tests/mocks/mockMonitoringReasons.js`
- new reason for closure: "Fully Vaccinated."
**Submitter:**
@DPC15038 :
@ashankland  :
@tstrass  :

SARAALERT-1469: New reason for closure - Fully Vaccinated

---

docs/api/api-coming-soon.md
docs/api/api-release-notes.md
docs/api/walkthrough-testing-the-backend-services-workflow.md

Update the API docs for the release of 1.32.0.
- Add coming soon for 1.33.0
- Document new features for 1.32.0
`walkthrough-testing-the-backend-services-workflow.md`
- Fix a confusing usage of "http" vs "https" when describing the `aud` field
N/A

SARAALERT-NONE: 1.32.0 API Documentation Updates

---

app/javascript/components/patient/assessment/actions/MonitoringPeriod.js

Jira Ticket: [SARAALERT-1436](https://tracker.codev.mitre.org/browse/SARAALERT-1436)
Remove isolation ineligible for RRR warning from exposure
Visit the patient page of a monitoree in exposure without SO date or positive lab
Add isolation check
**Submitter:**
@ :
@ :
@ :

BUGFIX: Remove isolation ineligible for RRR warning from exposure

---

app/controllers/admin_controller.rb
app/controllers/analytics_controller.rb
app/controllers/patients_controller.rb
app/controllers/public_health_controller.rb
app/views/layouts/_html_head.html.erb

Jira Ticket: [SARAALERT-1466](https://tracker.codev.mitre.org/browse/SARAALERT-1466)
Sara Alert HTML titles are currently always set to `'Sara Alert'`. This PR allows any controller to specify a custom title for a page by setting the `@title` variable. This PR also implements this in the patients show page by setting the title to the initals-age of the patient.
I'm waiting on a response from the UI channel to let me know if this is still exactly how the patient show page title should be formatted, as well as if there are any other custom titles that should be set - such as dashboards.
`patient_controller.rb#show`
- Set `@title` equal to …

SARAALERT-1466: Better HTML title usage

---

app/javascript/components/admin/AdminTable.js
app/javascript/components/public_health/PatientsTable.js
app/javascript/packs/stylesheets/custom_table.scss

Jira Ticket: [SARAALERT-1546](https://tracker.codev.mitre.org/browse/SARAALERT-1546)
This Pull Request adds the same styling that was added to the patients table to the admin table.
`app/javascript/components/admin/AdminTable.js`
- Wraps the admin table in a new class to provide the styling
`app/javascript/packs/stylesheets/custom_table.scss`
- Adds the new admin-table class
**Submitter:**
@ngfreiter  :
@jkufro  :
@holmesie  :

SARAALERT-1546: Admin Table Styling

---

db/migrate/20210616203622_add_threshold_hash_to_jurisdictions.rb

Jira Ticket: [SARAALERT-1501](https://tracker.codev.mitre.org/browse/SARAALERT-1501)
Follow-on to #930
[Slack context](https://mitrecorp.slack.com/archives/GSV87B6BB/p1625249383106500)
This migration depends on previous migrations that add columns to the
jurisdictions table. Therefore, you need to reload the class so that it
doesn't attempt to use the cached version, which doesn't have the
columns added by previous migrations, in the event that you run all the
migrations at once (e.g. with db:migrate:reset).
On branch `1.33.0` run `rake db:migrate:reset`
Explained above.
**Submitter:**
@holmesie:
@timwongj:
@Bialogs:

SARAALERT-1501: Fix issue with threshold hash migration

---

Gemfile.lock

Update addressable gem to fix CVE https://github.com/advisories/GHSA-jxhc-q857-3j6g
**Submitter:**
@ :

Update addressable gem from 2.7.0 -> 2.8.0 to address CVE

---

performance/collect_benchmark_results.rb

Jira Ticket: [SARAALERT-NONE](https://tracker.codev.mitre.org/browse/SARAALERT-NONE)
If there was ever an empty artifact ZIP from GH Actions collected by the `performance/collect_benchmark_results_file.rb` then the script would fail. This PR addresses this issue by passing an additional option to the unzip open method
see above
see above
`performance/collect_benchmark_results_file.rb`
- Pass create argument to ZIP open method
Issue can be replicated by running `bundle exec ruby performance/collect_benchmark_results.rb` on both 1.34.0 and this branch
**Submitter:**
@ :
@ :
@ :

SARAALERT-NONE - Empty artifact zip fix

---

app/helpers/patient_query_helper.rb
app/models/patient.rb
test/controllers/public_health_controller_test.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-1029](https://tracker.codev.mitre.org/browse/SARAALERT-1029)
https://www.cdc.gov/coronavirus/2019-ncov/science/science-briefs/scientific-brief-options-to-reduce-quarantine.html?CDC_AA_refVal=https%3A%2F%2Fwww.cdc.gov%2Fcoronavirus%2F2019-ncov%2Fmore%2Fscientific-brief-options-to-reduce-quarantine.html
This contains a test fix as well as scope changes for both the 7 and 10 day quarantine periods. This is part of the intermittent test fixes work, but I think this specific case deserves its own PR and discussion.
This was one of the intermittent tests that was affected by the time of day that it was run at. You can replicate the test failures by changing your system time (best to try late at night or early in the morning).
Before this change we were calculating the …

SARAALERT-1029 - 10 and 7 day quarantine fix

---

app/models/patient.rb
test/models/patient_test.rb

Jira Ticket: [SARAALERT-1553](https://tracker.codev.mitre.org/browse/SARAALERT-1553)
Add this condition to the auto-closure logic for the Non-Reporting Isolation line list.
- a moniotoree on the Non-Reporting Isolation line list has their "Extend Isolation To" field set, they should only be eligible for auto-closure if it's been at least 2 day after the "Extend Isolation To" date. This way, the monitoree has the chance to be moved back to the RRR line list if they are eligible for that.
`patient.rb`
- split out isolation and exposure no_recent_activity helpers into two separate variables to help readability
- added isolation …

SARAALERT-1553: Isolation close edge case

---

app/controllers/patients_controller.rb
test/controllers/patients_controller_test.rb

Jira Ticket: [SARAALERT-1515](https://tracker.codev.mitre.org/browse/SARAALERT-1515)
Updates histories generated when users add monitorees to a household, remove them from a household, or change the HOH to specify "Sara Alert ID" in the message for clarity. 
`app/controllers/patients_controller.rb` 
- changes the comment lines for the relevant history generations to include the clarifying language
`test/controllers/patients_controller_test.rb`
- changes the test suite to reflect the new language. 
Make sure to check that the message is correctly generated for all three cases, and is propagated to other household members appropriately (e.g. when the HOH is changed)
**Submitter:**
@ngfreiter 
@ :
@ :

SARAALERT-1515: Specify "Sara Alert ID" when adding or removing monitoree from a household or changing HOH

---

app/javascript/components/public_health/CustomExport.js
app/javascript/packs/stylesheets/dashboard.scss

Jira Ticket: [SARAALERT-1550](https://tracker.codev.mitre.org/browse/SARAALERT-1550)
Fixes the way advanced filters are displayed in the custom export modal, see mockup [here](https://mitre.sharepoint.com/:b:/r/sites/CoVDT/Shared%20Documents/General/Product%20Own[…]Value%20Display%20Jul%2013%202021.pdf?csf=1&web=1&e=XIlzUS).
Before checking out this branch, create an advanced filter with filters for lab results, apply it, then attempt to perform a custom export
The multi-select advanced filter type was added after the creation of the custom export modal, which didn't include logic to properly handle displaying multi-select values …

SARAALERT-1550: Fix custom export not displaying advanced filters properly

---

performance/docker/build-push-1m-database-image.sh

This just adds some more guidance on updating the performance docker image based on how I did it today.

SARAALERT-NONE - Add supporting comments to performance docker image script

---

app/helpers/patient_details_helper.rb
app/lib/import_export.rb
app/lib/import_export_constants.rb
test/controllers/fhir/r4/patient_test.rb
test/fixtures/patients.yml

Jira Ticket: [SARAALERT-1521](https://tracker.codev.mitre.org/browse/SARAALERT-1521)
This PR includes changes to fix the api tests
**Submitter:**
@tstrass :
@dubem7 :
@ngfreiter :

SARAALERT-1521: Fix api tests related to follow up reason and note

---

.rubocop.yml

Jira Ticket: [SARAALERT-NONE](https://tracker.codev.mitre.org/browse/SARAALERT-NONE)
This PR just enables the new Rubocop cops that appear in rubocop warnings when running the tool. We were already in compliance with the new rules so there are no required code changes.
`rubocop.yml`
- added new cops
run `rubocop` locally to ensure that all checks pass
**Submitter:**
@holmesie  :
@tstrass  :

SARAALERT-NONE Enable new Rubocop cops

---

app/helpers/patient_details_helper.rb
app/models/history.rb
app/models/patient.rb
app/models/transfer.rb
test/controllers/patients_controller_test.rb
test/fixtures/patients.yml
test/jobs/close_patients_job_test.rb
test/models/assessment_test.rb
test/models/history_test.rb
test/models/transfer_test.rb

Jira Ticket: [SARAALERT-1029](https://tracker.codev.mitre.org/browse/SARAALERT-1029)
This PR is fixes tests that fail after around 7pm EST. 
This PR fixes various bugs that become present when your system local time does is a different date than UTC. You can replicate these issues by changing your system time to near the end of the day (for example I'm in mountain time and I changed to 7 or 9pm local time).
Many of the test fixes are just making sure that time calculations respect patient local time vs UTC time differences, or just force some logic to always use UTC. I made inline comments in the diff where the fix was different than this / was more complex.
**Submitter:**
@ :
@ :
@ :

SARAALERT-1029: Fix time sensitive tests

---

app/mailers/patient_mailer.rb
app/models/history.rb
test/mailers/patient_mailer_test.rb
test/models/history_test.rb

Language updates based on UAT feedback for [SA-1188](https://tracker.codev.mitre.org/browse/SARAALERT-1188)
Feedback: https://mitrecorp.slack.com/archives/C01A6P94R9B/p1627505622007800

SARAALERT-1188: history language update

---

app/javascript/tests/mocks/mockTabs.js
app/views/public_health/global.html.erb

Jira Ticket: [SARAALERT-1567](https://tracker.codev.mitre.org/browse/SARAALERT-1567)
The description for the Global Non-Reporting line list isn't exactly right, since technically you can be on the Symptomatic, PUI, or RRR lists even if you failed to report in the past day. New text should be:
"All monitorees on the Non-Reporting line list in all workflows."
**Submitter:**
@holmesie :
@ngfreiter :
@annmarieb1 :

SARAALERT-1567: Update Description Text for Global Non-Reporting Line List

---

docs/api/api-coming-soon.md

Jira Ticket: NONE
Update API docs for 1.35.0.

SARAALERT-NONE: 1.35.0 API Documentation Updates

---

app/models/user.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into User model
Related https://github.com/SaraAlert/SaraAlert/pull/1028
`User.rb`
- `dependent: nil` is the same behavior as current
- `dependent: destroy` will remove the associated record when the User is destroyed. I figured it would be fine to remove their presets, filters, downloads, and exports since that user does not exist.
Use the following [rubocop.txt](https://github.com/SaraAlert/SaraAlert/files/6955967/rubocop.txt) to test similar to last time.
**Submitter:**
@ngfreiter 
@tstrass  :
@ :

SARAALERT-1470: User Model Changes

---

app/models/transfer.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into Transfer model.
Related #1028
`Transfer.rb`
- Line length
- Reorder callback functions
**Submitter:**
@ :
@ :
@ :

SARAALERT-1470: Transfer Model Changes

---

app/models/laboratory.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into Laboratory model.
Related #1028
`Laboratory`
- Reorder callback functions
**Submitter:**
@ :
@ :
@ :

SARAALERT-1470: Laboratory Model Changes

---

app/javascript/components/public_health/query/AdvancedFilter.js
app/javascript/data/advancedFilterOptions.js
app/javascript/tests/public_health/query/AdvancedFilter.test.js

Jira Ticket: [SARAALERT-1020](https://tracker.codev.mitre.org/browse/SARAALERT-1020)
Updated tooltip for jurisdiction and assigned user advanced filters based on UAT feedback
**Submitter:**
@timwongj :
@tstrass :
@ngfreiter :

SARAALERT-1020: Updated multi advanced filter tooltip language

---

app/models/patient.rb

Jira Ticket: [SARAALERT-###](https://tracker.codev.mitre.org/browse/SARAALERT-513)
Update history message for preferred contact time from saved value to displayed value
Update preferred contact time
**Submitter:**
@ :
@ :
@ :

update history message for preferred contact time

---

app/javascript/data/advancedFilterOptions.js

Jira Ticket: [SARAALERT-1020](https://tracker.codev.mitre.org/browse/SARAALERT-1020)
Makes a minor update to the tooltip language for accuracy. Since the filter allows all accessible jurisdictions as selections, even if that jurisdiction is not used on any patients, the tooltip should reflect that.
`advancedFilterOptions.js`
- Update the tooltip 
Do an advanced filter on multi-select jurisdictions, and check out the tooltip, it should be updated to more accurately reflect that all accessible jurisdictions are available.
**Submitter:**
@tstrass 
@sgober 
@timwongj

SARAALERT-1020: Update jurisdiction advanced filter tooltip

---

docs/api/api-coming-soon.md
docs/api/api-release-notes.md

Update the documentation for the 1.36.0 release.
- Update the coming soon for 1.37.0
- Document new bulk data export added in 1.36.0

1.36.0 API Documentation Updates

---

app/models/jwt_identifier.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into JwtIdentifier model.
Related #1028
`JwtIdentifier`
- Use `Time.zone` to make the operation's time zone explicit
**Submitter:**
@ :
@ :
@ :

SARAALERT-1470 JwtIdentifier

---

app/models/history.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into History model.
Related #1028
`History`
- Favor `if xyz.present?` over `unless xyz.blank?`
- Add rubocop disable for bypassing validation since bypassing is required.
**Submitter:**
@ :
@ :
@ :

SARAALERT-1470 History

---

app/models/condition.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into Condition model.
Related #1028
`Condition`
- Specify dependent action as `dependent: nil` keeping the same behavior, just making it explicit.
**Submitter:**
@ :
@ :
@ :

SARAALERT-1470 Condition

---

app/models/assessment.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into Assessment model.
Related #1028
`Assessment`
- Replace `map ... .to_h` with `index_by`
- Specify dependent action as dependent: nil keeping the same behavior, just making it explicit.
**Submitter:**
@ :
@ :
@ :

SARAALERT-1470 Assessment

---

app/models/analytic.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into Analytic model.
Related #1028
`Analytic`
- Specify dependent action as dependent: nil keeping the same behavior, just making it explicit.
**Submitter:**
@ :
@ :
@ :

SARAALERT-1470 Analytic

---

app/javascript/components/public_health/Import.js

Jira Ticket: [SARAALERT-1602](https://tracker.codev.mitre.org/browse/SARAALERT-1602)
This PR updates the progress bar on import so that it accurately reflects the status of the import. The previous approach had an error with parentheses placement, so the value rendered in the bar was not accurate. This fixes that. 
On `master` import a large amount of monitorees, something around 100, you should see that after hitting "Import All", the progress bar almost immediately goes to 100%, even though the import still takes a while after that.
On this branch, doing the same import should show a progress bar that smoothly goes from 0 to 100% as records are imported.
Fix the order of operations in our calculation of what percent of records are imported.
`Import.js`
- Add parentheses so division is …

SARAALERT-1602: Fix progress bar status on import

---

app/javascript/components/enrollment/steps/Identification.js
app/javascript/tests/mocks/mockTranslations.js
app/javascript/tests/patient/assessment/steps/AssessmentCompleted.test.js
app/javascript/utils/Languages.js
app/models/assessment.rb
config/locales/zho.yml
config/twilio/assessment_studio_flow.json
lib/assets/languages.yml
lib/tasks/stats.rake

Jira Ticket: [SARAALERT-629](https://tracker.codev.mitre.org/browse/SARAALERT-629)
Offer chinese mandarin language to monitorees
Translations: https://teams.microsoft.com/l/file/B7FEC298-550C-43CC-8FB4-1F79ABC432A1?tenantId=c620dc48-1d50-4952-8b39-df4d54d74d82&fileType=xlsx&objectUrl=https%3A%2F%2Fmitre.sharepoint.com%2Fsites%2FCoVDT%2FShared%20Documents%2FGeneral%2FProduct%20Owner%20Materials%2FTranslations%2FTranslation%20Feedback%2FFinal%20Translations%2007_2021.xlsx&baseUrl=https%3A%2F%2Fmitre.sharepoint.com%2Fsites%2FCoVDT&serviceName=teams&threadId=19:00d3d45c64ca457795d58c2764d517cd@thread.skype&groupId=7de0f318-3170-4f1c-82eb-95bfe132bfe9
Please list important files (meaning substantial or integral to the PR) …

SARAALERT-629: Offer chinese mandarin language to monitorees

---

test/jobs/purge_job_test.rb

On seed 64648 the purge_job test was erroring because we were not resetting the delivery queue but checking the length.
I also just cleaned up the resetting of the email batch size.

SARAALERT-NONE: Add delivery clear and email batch setting reset to test setup

---

app/models/jurisdiction.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into Jurisdiction model.
Related #1028
`Jurisdiction`
- Specify dependent actions for associations when Jurisdictions are deleted. `dependent: nil` keeps the same behavior as current, it's just explicit about it.
- Switch from `pluck` to `select` within a `where` (reference https://www.rubydoc.info/gems/rubocop-rails/RuboCop/Cop/Rails/PluckInWhere)
**Submitter:**
@ :
@ …

SARAALERT-1470 Jurisdiction

---

app/models/concerns/isolation_symptom_onset_validator.rb
app/models/concerns/laboratory_date_validator.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into Validators.
Related #1028
`IsolationSymptomOnsetValidator`
- Switch from not blank to present
`LaboratoryDateValidator`
- Use Time.zone.today to explicitly use the application's configured timezone.
**Submitter:**
@tstrass  :
@ngfreiter  :
@timwongj  :

SARAALERT-1470: Validators

---

app/mailers/patient_mailer.rb
app/mailers/user_mailer.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into Mailers.
Related #1028
`PatientMailer`
- Change map to collect
- Utilize `find_by(attribute: )` instead of `find_by_attribute()`
`UserMailer`
- change `unless present?` to `if blank?`
**Submitter:**
@tstrass :
@ngfreiter  :
@timwongj  :

SARAALERT-1470: Mailers

---

app/helpers/export_helper.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into Export helper.
Related #1028
`export_helper`
- `Unless present` -> `if blank`
**Submitter:**
@tstrass  :
@timwongj  :
@ngfreiter  :

SARAALERT-1470: import export

---

app/jobs/cache_analytics_job.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into CacheAnalytics Job.
Related #1028
`cache_analytics_job`
- Use SQL.squish to eliminate additional space/tab characters in server SQL logs.
**Submitter:**
@timwongj  :
@tstrass  :
@ngfreiter  :

SARAALERT-1470: Cache Analytics 

---

app/javascript/components/public_health/PublicHealthHeader.js
public/Sara Alert Import Format.xlsx

Jira Ticket: [SARAALERT-1408](https://tracker.codev.mitre.org/browse/SARAALERT-1408)
Updates the import guidance to state that case status is not required in isolation.
`public/Sara Alert Import Format`
- Updated language
- Examine the spreadsheet to ensure the fields are preset to the correct starting value
- Make sure the import guidance is correct/consistent with the ticket
- Review the changelog
**Submitter:**
@sgober  :
@timwongj  :
@ngfreiter  :

SARAALERT-1408: Update Import Guidance case status

---

.dockerignore
nginx.conf

Include these settings to mirror production environment.

SARAALERT-NONE: Update nginx.conf to include proxy_read, send, and connect timeouts

---

app/controllers/histories_controller.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into HistoriesController.
Related #1028
`histories_controller`
- Replace find_by_attr with find_by(attr:)
**Submitter:**
@timwongj  :
@tstrass  :
@ngfreiter  :

SARAALERT-1470 histories controller

---

app/controllers/fhir/r4/api_controller.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into Fhir::R4::ApiController
Related #1028
`api_controller`
- Use find_by(attr:) instead of dynamic find_by
- if present instead of unless blank
- use exclude instead of not include
- use key? instead of keys.include?
**Submitter:**
@timwongj  :
@tstrass  :
@ngfreiter  :

SARAALERT-1470: Fhir::R4::ApiController

---

app/controllers/errors_controller.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into ErrorsController Job.
Related #1028
`errors_controller`
- Use HTTP status symbol instead of number code
**Submitter:**
@timwongj  :
@tstrass  :
@ngfreiter  :

SARAALERT-1470: ErrorsController

---

app/controllers/export_controller.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into ExportController Job.
Related #1028
`export_controller`
- Use HTTP status symbol instead of code
- Use key? instead of keys.include?
**Submitter:**
@timwongj  :
@tstrass  :
@ngfreiter  :

SARAALERT-1470: ExportController

---

app/controllers/close_contacts_controller.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into CloseContactsController
Related #1028
`close_contacts_controller`
- change unless blank to if present
- change dynamic find by to find_by(attr:)
**Submitter:**
@timwongj  :
@tstrass  :
@ngfreiter  :

SARAALERT-1470: CloseContactsController

---

app/controllers/assessments_controller.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into AssessmentsController.
Related #1028
`assessments_controller`
- unless blank to if present
- use enumerable pluck instead of mapping to get the value
- use index_by instead of map.to_h
**Submitter:**
@timwongj  :
@tstrass  :
@ngfreiter  :

SARAALERT-1470 assessments controller

---

app/controllers/analytics_controller.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into AdminController.
Related #1028
`admin_controller`
- Use Rails.root.join to build file path instead of manually
- Use Time.zone instead of Time.now to make dependency of time zone on calculation explicit
**Submitter:**
@timwongj  :
@tstrass  :
@ngfreiter  :

SARAALERT-1470: AnalyticsController

---

app/controllers/admin_controller.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into AdminController
Related #1028
`admin_controller`
- Use Time.zone to make dependency on zone explicit
- Use find_by(attr:) instead of dynamic find_by_attr
- remove redundant nil and empty checking when using blank? method
- change not blank? to present?
**Submitter:**
@timwongj  :
@tstrass  :
@ngfreiter  :

SARAALERT-1470: admin controller

---

app/helpers/patient_query_helper.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into PatientQueryHelper.
Related #1028
`patient_query_helper`
- Remove redundant `nil` checking
- Change not blank to `present`
- Use `Enumerable#pluck` instead of `map`
- Use `tr` instead of `gsub` for single character replace
- Use Object#presence to return the object instead of an if statement
- Disable Rails/PluckInWhere because I was seeing better performance without 
Use the following [rubocop.txt](https://github.com/SaraAlert/SaraAlert/files/6956507/rubocop.txt) to test similar to last …

SARAALERT-1470 Patient Query Helper

---

package.json
yarn.lock

About a week ago we started getting a popover error with the react-bootstrap tooltip.  This was an error with react-bootstrap and was fixed in the latest version (see below).
Hover over any tooltip (the advanced filter button has one) and this error will fire:
Bug with `react-bootstrap` that was fixed in v1.6.4.  See [here](https://github.com/react-bootstrap/react-bootstrap/issues/6017) for bug documentation.
You likely will have to blow out your node modules folder and run a yarn install.  If you're still seeing the error and you're running the webpack-dev-server, turn that off and do a fresh webpack compile.
**Submitter:**
@tstrass :
@timwongj :
@ngfreiter :

SARAALERT-NONE: Upgrade react-bootstrap

---

app/controllers/users_controller.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into UsersController
Related #1028
`users_controller`
- change unless present to if blank
- remove redundant nil checking when using blank
- change unless include to if exclude
- 
**Submitter:**
@timwongj  :
@tstrass  :
@ngfreiter  :

SARAALERT-1470 users controller

---

app/controllers/import_controller.rb

Incorporates Rubocop/Rails and Rubocop/Performance updates into ImportController.
Related #1028
`import_controller`
- Use Rails.root.join instead of creating a path string
- use value.presence instead of import_email_field, etc.
- use key? instead of keys.include for performance
- use casecmp instead of downcase then compare
**Submitter:**
@timwongj  :
@tstrass  :
@ngfreiter  :

SARAALERT-1470 import controller

---

.rubocop.yml
app/controllers/contact_attempts_controller.rb
app/controllers/patients_controller.rb
app/helpers/close_contact_query_helper.rb
app/lib/roles.rb
app/models/history.rb
app/models/patient.rb
app/models/symptom.rb
app/models/transfer.rb
app/views/patients/_patients.html.erb
test/controllers/fhir/r4/bulk_export_test.rb
test/controllers/fhir/r4/patient_test.rb
test/helpers/patient_query_helper_test.rb
test/system/roles/public_health/dashboard/import_verifier.rb

Jira Ticket: [SARAALERT-1470]https://tracker.codev.mitre.org/browse/SARAALERT-1470)
This PR includes the full rubocop.yml without anything from Performance or Rails disabled.
Please list any recommendations regarding what reviewers should test and if there is any specific guidance on how to test certain aspects of the PR. Be sure to mention edge cases that should be …

Enables all Rubocop/Performance and Rubocop/Rails cops.

---

app/lib/import_export_constants.rb

Jira Ticket: [SARAALERT-1641](https://tracker.codev.mitre.org/browse/SARAALERT-1641)
To the Monitorees List Sheet, add:
- Reason for Closure
- Closed At
- Expected Purge Date
Please list any recommendations regarding what reviewers should test and if there is any specific guidance on how to test certain aspects of the PR. Be sure to mention edge cases that should be …

SARAALERT-1641: Add Reason for Closure, Closed At, and Expected Purge Date to all Excel Export Formats

---

app/helpers/patient_query_helper.rb
app/javascript/components/patient/household/actions/MoveToHousehold.js
app/javascript/components/public_health/PatientsTable.js

Jira Ticket: [SARAALERT-1631](https://tracker.codev.mitre.org/browse/SARAALERT-1631)
Per UAT feedback, make phone number column sortable in the patients table and in the move to household modal
Test sorting the phone number column in the two tables listed above.
**Submitter:**
@tstrass :
@deastman :
@hackrm :

SARAALERT-1631: Sortable Phone Number Column

---

public/Sara Alert Import Format.xlsx

Jira Ticket: [SARAALERT-1648](https://tracker.codev.mitre.org/browse/SARAALERT-1648)
Updated "Member of Common Exposure Cohort" example to use true/false instead of yes/no in SaraAlert Import Format file
Check to make sure the values in the SaraAlert Import Format file match what is requested in the JIRA ticket
**Submitter:**
@tstrass :
@timwongj :
@deastman :

SARAALERT-1648: Revise the Import Template Example monitorees to valid "Exposure Cohort" values

---

app/javascript/components/admin/AdminTable.js
app/javascript/components/layout/CustomTable.js
app/javascript/components/patient/assessment/AssessmentTable.js
app/javascript/components/patient/close_contacts/CloseContactTable.js
app/javascript/components/patient/household/HouseholdMemberTable.js
app/javascript/components/patient/vaccines/VaccineTable.js
app/javascript/components/public_health/PatientsTable.js
app/javascript/packs/stylesheets/layout.scss
app/javascript/tests/layout/CustomTable.test.js
app/javascript/tests/patient/household/HouseholdMemberTable.test.js

Jira Ticket: [SARAALERT-1530](https://tracker.codev.mitre.org/browse/SARAALERT-1530)
Adds full test suite for the `CustomTable` component
`CustomTable.test.js`: Added full test suite for the CustomTable Component
`CustomTable.js`: Fixed a bug where sorting columns (if you click on a new column it would not always default to asc order) and general cleanup
`AdminTable.js`, `AssessmentTable.js`, `CloseContactTable.js`, `HouseholdMemberTable.js`, `Vaccine.js`: Set the default sort to reflect what's actually in the table
`PatientsTable.js`: General cleanup
`HouseholdMemberTable.test.js`: Fix tests that were broken by setting the default sort …

SARAALERT-1530: Custom Table Tests

---

app/helpers/validation_helper.rb
app/javascript/tests/mocks/mockMonitoringReasons.js

Jira Ticket: [SARAALERT-1651](https://tracker.codev.mitre.org/browse/SARAALERT-1651)
Additional Closure Reason: Refused Monitoring - While "Other" has been recommended for non-standard closure reasons, more than a few monitorees have been choosing to NOT monitor via Sara Alert. The request to standardize this closure reason would eliminate the use of Advanced Filters building to capture/eliminate monitorees that were closed with Other and having to distinguish the closure notation associated. Priority: Medium-High
Please list any recommendations regarding what reviewers …

SARAALERT-1651: Add "Refused Monitoring" as reason for closure

---

app/views/user_mailer/welcome_email.html.erb

Jira Ticket: [SARAALERT-1645](https://tracker.codev.mitre.org/browse/SARAALERT-1645)
Revising the New User Email to include links to saraalert.org and the User forum
`app/helpers/assessment_query_helper.rb`
- Updated to match the language drafted in [SARAALERT-1645](https://tracker.codev.mitre.org/browse/SARAALERT-1645)
- Attempt to generate a sample New User email and validate the formatting.
- Validate the language in the email matches the language in the Jira ticket
**Submitter:**
@sgober  :
@tstrass  :
@deastman  :

SARAALERT-1645: Revision to New User Email

---

app/mailers/patient_mailer.rb
app/models/jurisdiction.rb
app/models/symptom.rb
config/locales/eng.yml
config/locales/fra.yml
config/locales/kor.yml
config/locales/som.yml
config/locales/spa-pr.yml
config/locales/spa.yml
config/locales/vie.yml
test/mailers/patient_mailer_test.rb

Jira Ticket: [SARAALERT-1600](https://tracker.codev.mitre.org/browse/SARAALERT-1600)
We have stripped the Spanish, Puerto Rican Spanish, and French translations of their special characters for the sake of more efficient segmentation in SMS messaging. Email, weblink, and voice share some translations with SMS, but it's no issue for those mediums to still have special characters. So for this task, reintroduce the special characters for those mediums while still leaving them out of SMS messages.
`app/mailers/patient_mailer.rb`, `app/models/jurisdiction.rb`, `app/models/symptom.rb`
- use simplified translations for sms medium …

SARAALERT-1600: Reintroduce language special characters for non-SMS mediums

---

app/javascript/tests/patient/assessment/actions/CurrentStatus.test.js

Added missing prop that breaks CurrentStatus tests which was introduced by [SARAALERT-1662](https://tracker.codev.mitre.org/browse/SARAALERT-1662)
**Submitter:**
@timwongj :
@tstrass :

SARAALERT-NONE: Fix Frontend Tests

---

Gemfile.lock

Upgrade sidekiq
**Submitter:**
@tstrass :
@timwongj :

SARAALERT-NONE: Fix Bundle Vulnerabilities

---

app/helpers/patient_query_helper.rb
app/javascript/components/public_health/query/AdvancedFilter.js
app/javascript/data/advancedFilterOptions.js
app/javascript/tests/mocks/mockFilters.js
app/javascript/tests/public_health/query/AdvancedFilter.test.js
db/migrate/20211222192244_update_combined_advanced_filters.rb
test/helpers/patient_query_helper_test.rb

Jira Ticket: [SARAALERT-1646](https://tracker.codev.mitre.org/browse/SARAALERT-1646)
Instead of having separate filters for the same field that have different filter functionality, combine them to one and utilize the additionalFilterOption functionality.  This should be done for:
- Address (domestic/foreign)
- Combine these filters into a combination filter so that the user is still able to set both a domestic and foreign address in their filter if they choose to
- Name (first/middle/last)
- Combine these filters into a combination filter so that the user is still able to set a first, last, and middle name in their filter if they choose to
- Telephone (exact match/contains) 
- Combine these filters to be the same format as the current "Close Contact with a Known Case ID" filter option …

SARAALERT-1646: Combine advanced filters

---

README.md

Update license to add 2022 to copyright
**Submitter:**
@ :
@ :
@ :

Include 2022 in README Copyright

---

app/javascript/components/public_health/query/AdvancedFilter.js

Jira Ticket: [SARAALERT-1686](https://tracker.codev.mitre.org/browse/SARAALERT-1686)
When the window height is smaller than a certain size where the advanced filter options do not fit on the screen when opened, the page automatically autoscrolls as an attempt to display all the options.
1. Resize the window to be relatively small
2. Open the advanced filter modal
3. Click on the dropdown of options
4. Notice the page scrolling down a bit
Remove the `menuPortalTarget` prop which binds the select options to the document body instead of the modal
Please list any …

SARAALERT-1686: Clicking Advanced Filter Drop-down causes Dashboard to Scroll

---

app/helpers/patient_query_helper.rb

Jira Ticket: [SARAALERT-1687](https://tracker.codev.mitre.org/browse/SARAALERT-1687)
This advanced filter currently returns no patients because the back end code is written incorrectly
Apply an advanced filter with the jurisdiction option
Reference `filter[:value]`
**Submitter:**
@sgober :
@hackrm :
@deastman :

SARAALERT-1687: Fix the "Jurisdiction (Multi-select)" advanced filter

---

audit-ci.json

Update yarn vulnerability allowlist (these will be removed with the completion of [SARAALERT-1688](https://tracker.codev.mitre.org/browse/SARAALERT-1688)
**Submitter:**
@tstrass :
@timwongj :

SARAALERT-NONE: Fix Yarn Vulnerabilities

---

.env-prod-assessment-example
.env-prod-enrollment-example
README.md
app/javascript/components/layout/Header.js
app/views/layouts/application.html.erb
app/views/layouts/doorkeeper/admin.html.erb
app/views/layouts/doorkeeper/application.html.erb
config/sara/sara.yml

Jira Ticket: [SARAALERT-1684](https://tracker.codev.mitre.org/browse/SARAALERT-1684)
For this ticket, make the following configureable:
- Whether the banner is displayed or not (or it could be set up that if a message is configured, the banner automatically appears)
- The message that should be displayed in the banner
`README.md`
- Only the section regarding the `SHOW_DEMO_WARNNG_BG` env variable was changed, the rest of the changes came from the automatic formatting in vscode upon save
Set the environment variable(s) before starting the server: `DEMO_WARNING_MSG=asdf rails s`
**Submitter:**
@tstrass :
@sgober :
@hackrm :

SARAALERT-1684: Make demo warning banner configurable

---

app/javascript/components/patient/assessment/actions/CurrentStatus.js

Open up patient page for a monitoree in isolation RRR (asymptomatic non test based) and see that the tooltip does not show up
Fixed spelling of `data-for` which the tooltip uses to place it's location on the screen 
**Submitter:**
@tstrass :
@timwongj :

SARAALERT-NONE: Status Tooltip Bugfix

---

.github/workflows/performance.yml

Fixes failing jmeter benchmark by updating the version
**Submitter:**
@tstrass :
@timwongj :

SARAALERT-NONE: Fix jmeter benchmark

---

app/javascript/components/util/InfoTooltip.js

Jira Ticket: [SARAALERT-1697](https://tracker.codev.mitre.org/browse/SARAALERT-1697)
Revising the tooltip language for Monitoring Plan and Exposure Risk assessment to: "Can be used to prioritize responses to symptomatic and non-reporting individuals. This element does not impact the type or frequency of messages sent by the system to monitorees."
- Revised language displayed of the tooltips
In the profile view for a monitoree & in the final enrollment screen for a monitoree, ensure the tooltips for MOnitoring Plan and Exposure Risk Assessment both display the following langage: "Can be used to prioritize responses to symptomatic and non-reporting individuals. This element does not impact the type or frequency of messages sent by the system …

SARAALERT-1697: Revising Tooltip language for Monitoring fields

---

.github/workflows/test.yml
README.md
db/schema.rb
lib/tasks/demo.rake

Jira Ticket: [SARAALERT-1683](https://tracker.codev.mitre.org/browse/SARAALERT-1683)
Upgrade database documentation based on MySQL 8 exploration
`.github/workflows/test.yml`
- upgrade testing image to `mysql:8.0`
`README.md`
- update documentation from MySQL 5.7 to 8.0 (most of the diff is just the automatic code formatting from VSCode)
`db/schema.rb`
- `utf8` encoding which is equivalent to `utf8mb3` is automatically explicitly defined, will need to upgrade to `utf8mb4` in the future
`lib/tasks/demo.rake`
- generate purged patients in `demo:populate` task
- create new `populate_purged_patients` task to quickly generate many purged patients for testing
Please list any recommendations regarding what reviewers should test and if there is any specific guidance on how to test certain aspects …

SARAALERT-1683: Upgrade database documentation based on MySQL 8 exploration

---

config/sara/README.md
config/sara/jurisdictions.yml

Jira Ticket: [SARAALERT-1698](https://tracker.codev.mitre.org/browse/SARAALERT-1698)
There is a README in the [config directory](https://github.com/SaraAlert/SaraAlert/tree/master/config/sara) on Github that is quite outdated. Update the README to provide information on the new configurations that have been added to the config files.
**Submitter:**
@tstrass :
@sgober :
@deastman :

SARAALERT-1698: Revise the README in the Github config directory
